"""
Batch-operation discovery.

Exposes the write vocabulary of each feature's batch builder so that generic
API clients (e.g. the VyMCP server) can construct ``/vyos/<feature>/batch``
operations without hard-coding every op. The vocabulary is derived by
introspecting the builder classes, so it stays in sync with the builders
automatically.

The op vocabulary is static, non-sensitive metadata, so these endpoints require
only authentication (enforced by AuthenticationMiddleware) — not per-instance
RBAC or an active instance.
"""

import inspect
from typing import Any

from fastapi import APIRouter, HTTPException, Request

from vyos_builders import (
    AccessListBatchBuilder,
    AsPathListBatchBuilder,
    BabelBatchBuilder,
    BfdBatchBuilder,
    BgpBatchBuilder,
    CommunityListBatchBuilder,
    DHCPBatchBuilder,
    ExtCommunityListBatchBuilder,
    FirewallGlobalOptionsBatchBuilder,
    FirewallIPv4BatchBuilder,
    FirewallIPv6BatchBuilder,
    FirewallZonesBatchBuilder,
    LargeCommunityListBatchBuilder,
    LocalRouteBatchBuilder,
    NAT64BatchBuilder,
    NAT66BatchBuilder,
    NATBatchBuilder,
    OspfBatchBuilder,
    Ospfv3BatchBuilder,
    PrefixListBatchBuilder,
    RipBatchBuilder,
    RipNgBatchBuilder,
    RouteMapBatchBuilder,
    RpkiBatchBuilder,
    StaticRoutesBatchBuilder,
    SystemBatchBuilder,
    TrafficEngineeringBatchBuilder,
    VrfBatchBuilder,
)
from vyos_builders import (
    BondingBatchBuilder,
    DummyBatchBuilder,
    GeneveBatchBuilder,
    InputBatchBuilder,
    L2TPv3BatchBuilder,
    LoopbackBatchBuilder,
    MacsecBatchBuilder,
    OpenvpnBatchBuilder,
    PppoeBatchBuilder,
    PseudoEthernetBatchBuilder,
    SstpcBatchBuilder,
    VirtualEthernetBatchBuilder,
    VppBatchBuilder,
    VtiBatchBuilder,
    WirelessBatchBuilder,
)
from vyos_builders.broadcast_relay import BroadcastRelayBatchBuilder
from vyos_builders.config_sync import ConfigSyncBatchBuilder
from vyos_builders.conntrack_sync import ConntrackSyncBatchBuilder
from vyos_builders.console_server import ConsoleServerBatchBuilder
from vyos_builders.container import ContainerBatchBuilder
from vyos_builders.dhcp_relay import DHCPRelayBatchBuilder
from vyos_builders.dhcpv6_relay import DHCPv6RelayBatchBuilder
from vyos_builders.dhcpv6_server import DHCPv6ServerBatchBuilder
from vyos_builders.dns_dynamic import DNSDynamicBatchBuilder
from vyos_builders.dns_forwarding import DNSForwardingBatchBuilder
from vyos_builders.event_handler import EventHandlerBatchBuilder
from vyos_builders.failover import FailoverBatchBuilder
from vyos_builders.firewall import FlowtablesBatchBuilder
from vyos_builders.high_availability import HighAvailabilityBatchBuilder
from vyos_builders.https import HTTPSBatchBuilder
from vyos_builders.igmp_proxy import IgmpProxyBatchBuilder
from vyos_builders.interfaces.wwan import WwanInterfaceBatchBuilder
from vyos_builders.ipoe_server import IPoEServerBatchBuilder
from vyos_builders.ipsec import IPSecBatchBuilder
from vyos_builders.isis import IsisBatchBuilder
from vyos_builders.l2tp import L2TPBatchBuilder
from vyos_builders.lldp import LLDPBatchBuilder
from vyos_builders.load_balancing import LoadBalancingBatchBuilder
from vyos_builders.mpls import MplsBatchBuilder
from vyos_builders.ndp_proxy import NdpProxyBatchBuilder
from vyos_builders.nhrp import NhrpBatchBuilder
from vyos_builders.ntp import NTPBatchBuilder
from vyos_builders.openfabric import OpenfabricBatchBuilder
from vyos_builders.pim import PimBatchBuilder
from vyos_builders.pim6 import Pim6BatchBuilder
from vyos_builders.pki import PKIBatchBuilder
from vyos_builders.pppoe_server import PPPoEServerBatchBuilder
from vyos_builders.qos import QoSBatchBuilder
from vyos_builders.router_advert import RouterAdvertBatchBuilder
from vyos_builders.salt_minion import SaltMinionBatchBuilder
from vyos_builders.service_monitoring import ServiceMonitoringBatchBuilder
from vyos_builders.sla import SLABatchBuilder
from vyos_builders.snmp import SNMPBatchBuilder
from vyos_builders.ssh import SSHBatchBuilder
from vyos_builders.tftp_server import TFTPServerBatchBuilder
from vyos_builders.tunnel import TunnelBatchBuilder
from vyos_builders.vxlan import VxlanBatchBuilder
from vyos_builders.webproxy import WebProxyBatchBuilder

router = APIRouter(prefix="/vyos/operations", tags=["operations"])

# Builder infrastructure methods that are not configuration operations.
_INTERNAL_BUILDER_METHODS = frozenset({
    "add_set", "add_delete", "get_operations", "is_empty", "clear",
    "operation_count", "get_capabilities", "get_version", "build",
})

# feature slug -> batch builder class. Generated by introspecting the routers;
# extend when a new feature router is added.
#
# Only features whose batch handler dispatches generically (getattr(builder, op)
# with the op value as the method args) are listed — the introspected vocabulary
# matches their real op contract. Excluded:
#   - Interface sub-types, which use the service.create_*_batch() factory.
#   - Explicit-dispatch handlers (firewall/groups, firewall/bridge, route, which
#     inject top-level body fields into builder calls), where the builder
#     signature would not match how ops are actually invoked.
_BUILDER_REGISTRY: dict[str, type] = {
    "access-list": AccessListBatchBuilder,
    "as-path-list": AsPathListBatchBuilder,
    "babel": BabelBatchBuilder,
    "bfd": BfdBatchBuilder,
    "bgp": BgpBatchBuilder,
    "broadcast-relay": BroadcastRelayBatchBuilder,
    "community-list": CommunityListBatchBuilder,
    "config-sync": ConfigSyncBatchBuilder,
    "conntrack-sync": ConntrackSyncBatchBuilder,
    "console-server": ConsoleServerBatchBuilder,
    "container": ContainerBatchBuilder,
    "dhcp": DHCPBatchBuilder,
    "dhcp-relay": DHCPRelayBatchBuilder,
    "dhcpv6-relay": DHCPv6RelayBatchBuilder,
    "dhcpv6-server": DHCPv6ServerBatchBuilder,
    "dns-dynamic": DNSDynamicBatchBuilder,
    "dns-forwarding": DNSForwardingBatchBuilder,
    "event-handler": EventHandlerBatchBuilder,
    "extcommunity-list": ExtCommunityListBatchBuilder,
    "failover": FailoverBatchBuilder,
    "firewall/flowtables": FlowtablesBatchBuilder,
    "firewall/global-options": FirewallGlobalOptionsBatchBuilder,
    "firewall/ipv4": FirewallIPv4BatchBuilder,
    "firewall/ipv6": FirewallIPv6BatchBuilder,
    "firewall/zones": FirewallZonesBatchBuilder,
    "high-availability": HighAvailabilityBatchBuilder,
    "https": HTTPSBatchBuilder,
    "igmp-proxy": IgmpProxyBatchBuilder,
    "ipoe-server": IPoEServerBatchBuilder,
    "isis": IsisBatchBuilder,
    "large-community-list": LargeCommunityListBatchBuilder,
    "lldp": LLDPBatchBuilder,
    "load-balancing": LoadBalancingBatchBuilder,
    "local-route": LocalRouteBatchBuilder,
    "mpls": MplsBatchBuilder,
    "nat": NATBatchBuilder,
    "nat64": NAT64BatchBuilder,
    "nat66": NAT66BatchBuilder,
    "ndp-proxy": NdpProxyBatchBuilder,
    "nhrp": NhrpBatchBuilder,
    "ntp": NTPBatchBuilder,
    "openfabric": OpenfabricBatchBuilder,
    "ospf": OspfBatchBuilder,
    "ospfv3": Ospfv3BatchBuilder,
    "pim": PimBatchBuilder,
    "pim6": Pim6BatchBuilder,
    "pki": PKIBatchBuilder,
    "pppoe-server": PPPoEServerBatchBuilder,
    "prefix-list": PrefixListBatchBuilder,
    "qos": QoSBatchBuilder,
    "rip": RipBatchBuilder,
    "ripng": RipNgBatchBuilder,
    "route-map": RouteMapBatchBuilder,
    "router-advert": RouterAdvertBatchBuilder,
    "rpki": RpkiBatchBuilder,
    "salt-minion": SaltMinionBatchBuilder,
    "service-monitoring": ServiceMonitoringBatchBuilder,
    "sla": SLABatchBuilder,
    "snmp": SNMPBatchBuilder,
    "ssh": SSHBatchBuilder,
    "static-routes": StaticRoutesBatchBuilder,
    "system": SystemBatchBuilder,
    "tftp-server": TFTPServerBatchBuilder,
    "traffic-engineering": TrafficEngineeringBatchBuilder,
    "tunnel": TunnelBatchBuilder,
    "vpn/ipsec": IPSecBatchBuilder,
    "vpn/l2tp": L2TPBatchBuilder,
    "vrf": VrfBatchBuilder,
    "vxlan": VxlanBatchBuilder,
    "webproxy": WebProxyBatchBuilder,
    "wwan": WwanInterfaceBatchBuilder,
    # Interface sub-types — "subject injection": their batch handler injects a
    # top-level field (the interface name) as the first arg of every op. See
    # _SUBJECT_FIELDS. (ethernet uses explicit dispatch and is excluded.)
    "bonding": BondingBatchBuilder,
    "dummy": DummyBatchBuilder,
    "geneve": GeneveBatchBuilder,
    "input": InputBatchBuilder,
    "l2tpv3": L2TPv3BatchBuilder,
    "loopback": LoopbackBatchBuilder,
    "macsec": MacsecBatchBuilder,
    "openvpn": OpenvpnBatchBuilder,
    "pppoe": PppoeBatchBuilder,
    "pseudo-ethernet": PseudoEthernetBatchBuilder,
    "sstpc": SstpcBatchBuilder,
    "virtual-ethernet": VirtualEthernetBatchBuilder,
    "vpp": VppBatchBuilder,
    "vti": VtiBatchBuilder,
    "wireless": WirelessBatchBuilder,
}

# Features whose batch handler injects a top-level body field as the first
# positional arg of every op (so an op's value supplies args AFTER the subject).
# A generic client must send this field and provide arg_count-1 value args.
_SUBJECT_FIELDS: dict[str, str] = {
    "bonding": "interface_name",
    "dummy": "interface",
    "geneve": "interface",
    "input": "interface",
    "l2tpv3": "interface",
    "loopback": "interface",
    "macsec": "interface",
    "openvpn": "interface",
    "pppoe": "interface",
    "pseudo-ethernet": "interface",
    "sstpc": "interface",
    "virtual-ethernet": "interface",
    "vpp": "interface",
    "vti": "interface",
    "wireless": "interface",
}


def describe_batch_builder(builder_cls: type, max_args: int = 2) -> list[dict[str, Any]]:
    """Introspect a batch builder into its callable operation vocabulary.

    Generic-dispatch features cap at 2 args (the dispatcher's limit). Subject
    features inject one arg from a top-level field and their VLAN ops take more,
    so they pass a higher max_args.
    """
    operations: list[dict[str, Any]] = []
    for name, method in inspect.getmembers(builder_cls, inspect.isfunction):
        if name.startswith("_") or name in _INTERNAL_BUILDER_METHODS:
            continue
        params = [p for p in inspect.signature(method).parameters if p != "self"]
        if len(params) > max_args:
            continue
        doc = inspect.getdoc(method)
        operations.append({
            "op": name,
            "args": params,
            "arg_count": len(params),
            "description": doc.splitlines()[0] if doc else None,
        })
    operations.sort(key=lambda o: o["op"])
    return operations


@router.get("")
async def list_discoverable_features(request: Request) -> dict[str, Any]:
    """List the features whose batch operation vocabulary can be introspected."""
    return {"features": sorted(_BUILDER_REGISTRY)}


@router.get("/{feature:path}")
async def get_feature_operations(feature: str, request: Request) -> dict[str, Any]:
    """Return the batch operation vocabulary for a single feature.

    ``subject_field``, when present, is the top-level body field the handler
    injects as each op's first arg; an op's value then supplies the remaining args.
    """
    slug = feature.strip("/")
    builder_cls = _BUILDER_REGISTRY.get(slug)
    if builder_cls is None:
        raise HTTPException(
            status_code=404,
            detail=f"No operation vocabulary for feature '{feature}'.",
        )
    subject_field = _SUBJECT_FIELDS.get(slug)
    max_args = 5 if subject_field else 2
    return {
        "feature": feature,
        "subject_field": subject_field,
        "operations": describe_batch_builder(builder_cls, max_args=max_args),
    }
