"""Golden (method, args, op, expected_path) cases for PseudoEthernetInterfaceBuilderMixin.

Paths checked with validateTmplPath on 1.4 (100.64.64.50) and 1.5 (100.64.64.5).
Generated for issue #721; edit the tables directly if the mapper changes.
"""

import pytest

from vyos_builders.interfaces.pseudo_ethernet import PseudoEthernetInterfaceBuilderMixin


def _run(version, method, args, op, expected_path):
    builder = PseudoEthernetInterfaceBuilderMixin(version=version)
    getattr(builder, method)(*args)
    operations = builder.get_operations()
    assert [(item["op"], item["path"]) for item in operations] == [(op, expected_path)]

COMMON_CASES = [
    ('delete_address', ('peth0', '192.0.2.1'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'address', '192.0.2.1']),
    ('delete_addresses', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'address']),
    ('delete_description', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'description']),
    ('delete_dhcp_options', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options']),
    ('delete_dhcp_options_client_id', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'client-id']),
    ('delete_dhcp_options_no_default_route', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'no-default-route']),
    ('delete_dhcp_options_reject', ('peth0', '192.0.2.1'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'reject', '192.0.2.1']),
    ('delete_dhcpv6_options', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options']),
    ('delete_dhcpv6_options_no_release', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'no-release']),
    ('delete_dhcpv6_options_parameters_only', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'parameters-only']),
    ('delete_dhcpv6_options_pd_instance', ('peth0', '5'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'pd', '5']),
    ('delete_dhcpv6_options_rapid_commit', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'rapid-commit']),
    ('delete_dhcpv6_options_temporary', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'temporary']),
    ('delete_disable', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'disable']),
    ('delete_disable_link_detect', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'disable-link-detect']),
    ('delete_interface', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0']),
    ('delete_ip_adjust_mss', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'adjust-mss']),
    ('delete_ip_arp_cache_timeout', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'arp-cache-timeout']),
    ('delete_ip_disable_arp_filter', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'disable-arp-filter']),
    ('delete_ip_disable_forwarding', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'disable-forwarding']),
    ('delete_ip_enable_arp_accept', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-arp-accept']),
    ('delete_ip_enable_arp_announce', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-arp-announce']),
    ('delete_ip_enable_arp_ignore', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-arp-ignore']),
    ('delete_ip_enable_directed_broadcast', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-directed-broadcast']),
    ('delete_ip_enable_proxy_arp', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-proxy-arp']),
    ('delete_ip_proxy_arp_pvlan', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'proxy-arp-pvlan']),
    ('delete_ip_settings', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip']),
    ('delete_ip_source_validation', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'source-validation']),
    ('delete_ipv6_accept_dad', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'accept-dad']),
    ('delete_ipv6_address_autoconf', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'address', 'autoconf']),
    ('delete_ipv6_address_eui64', ('peth0', '2001:db8::/32'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'address', 'eui64', '2001:db8::/32']),
    ('delete_ipv6_address_no_default_link_local', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'address', 'no-default-link-local']),
    ('delete_ipv6_adjust_mss', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'adjust-mss']),
    ('delete_ipv6_base_reachable_time', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'base-reachable-time']),
    ('delete_ipv6_disable_forwarding', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'disable-forwarding']),
    ('delete_ipv6_dup_addr_detect_transmits', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'dup-addr-detect-transmits']),
    ('delete_ipv6_settings', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6']),
    ('delete_ipv6_source_validation', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'source-validation']),
    ('delete_mac', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'mac']),
    ('delete_mirror_egress', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'mirror', 'egress']),
    ('delete_mirror_ingress', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'mirror', 'ingress']),
    ('delete_mode', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'mode']),
    ('delete_mtu', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'mtu']),
    ('delete_redirect', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'redirect']),
    ('delete_source_interface', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'source-interface']),
    ('delete_vif', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10']),
    ('delete_vif_address', ('peth0', '10', '192.0.2.1'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'address', '192.0.2.1']),
    ('delete_vif_addresses', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'address']),
    ('delete_vif_c', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10']),
    ('delete_vif_c_address', ('peth0', '10', '10', '192.0.2.1'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'address', '192.0.2.1']),
    ('delete_vif_c_addresses', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'address']),
    ('delete_vif_c_description', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'description']),
    ('delete_vif_c_disable', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'disable']),
    ('delete_vif_c_mac', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'mac']),
    ('delete_vif_c_mirror_egress', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'egress']),
    ('delete_vif_c_mirror_ingress', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'ingress']),
    ('delete_vif_c_mtu', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'mtu']),
    ('delete_vif_c_redirect', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'redirect']),
    ('delete_vif_c_vrf', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'vrf']),
    ('delete_vif_description', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'description']),
    ('delete_vif_disable', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'disable']),
    ('delete_vif_disable_link_detect', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'disable-link-detect']),
    ('delete_vif_egress_qos', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'egress-qos']),
    ('delete_vif_ingress_qos', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'ingress-qos']),
    ('delete_vif_mac', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'mac']),
    ('delete_vif_mirror_egress', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'mirror', 'egress']),
    ('delete_vif_mirror_ingress', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'mirror', 'ingress']),
    ('delete_vif_mtu', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'mtu']),
    ('delete_vif_redirect', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'redirect']),
    ('delete_vif_s', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10']),
    ('delete_vif_s_address', ('peth0', '10', '192.0.2.1'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'address', '192.0.2.1']),
    ('delete_vif_s_addresses', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'address']),
    ('delete_vif_s_description', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'description']),
    ('delete_vif_s_disable', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'disable']),
    ('delete_vif_s_mac', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'mac']),
    ('delete_vif_s_mirror_egress', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'mirror', 'egress']),
    ('delete_vif_s_mirror_ingress', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'mirror', 'ingress']),
    ('delete_vif_s_mtu', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'mtu']),
    ('delete_vif_s_redirect', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'redirect']),
    ('delete_vif_s_vrf', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vrf']),
    ('delete_vif_vrf', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'vrf']),
    ('delete_vrf', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vrf']),
    ('set_address', ('peth0', '192.0.2.1'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'address', '192.0.2.1']),
    ('set_description', ('peth0', 'lab'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'description', 'lab']),
    ('set_dhcp_options_client_id', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'client-id', '5']),
    ('set_dhcp_options_default_route_distance', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'default-route-distance', '5']),
    ('set_dhcp_options_host_name', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'host-name', '5']),
    ('set_dhcp_options_mtu', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'mtu']),
    ('set_dhcp_options_no_default_route', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'no-default-route']),
    ('set_dhcp_options_reject', ('peth0', '192.0.2.1'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'reject', '192.0.2.1']),
    ('set_dhcp_options_user_class', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'user-class', '5']),
    ('set_dhcp_options_vendor_class_id', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcp-options', 'vendor-class-id', '5']),
    ('set_dhcpv6_options_duid', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'duid', '5']),
    ('set_dhcpv6_options_no_release', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'no-release']),
    ('set_dhcpv6_options_parameters_only', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'parameters-only']),
    ('set_dhcpv6_options_pd_instance', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'pd', '5']),
    ('set_dhcpv6_options_pd_interface', ('peth0', '5', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'pd', '5', 'interface', '5']),
    ('set_dhcpv6_options_pd_interface_address', ('peth0', '5', '5', '192.0.2.1'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'address', '192.0.2.1']),
    ('set_dhcpv6_options_pd_interface_sla_id', ('peth0', '5', '5', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'sla-id', '5']),
    ('set_dhcpv6_options_pd_length', ('peth0', '5', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'pd', '5', 'length', '5']),
    ('set_dhcpv6_options_rapid_commit', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'rapid-commit']),
    ('set_dhcpv6_options_temporary', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'dhcpv6-options', 'temporary']),
    ('set_disable', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'disable']),
    ('set_disable_link_detect', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'disable-link-detect']),
    ('set_ip_adjust_mss', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'adjust-mss', '5']),
    ('set_ip_adjust_mss_clamp_to_pmtu', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'adjust-mss', 'clamp-mss-to-pmtu']),
    ('set_ip_arp_cache_timeout', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'arp-cache-timeout', '5']),
    ('set_ip_disable_arp_filter', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'disable-arp-filter']),
    ('set_ip_disable_forwarding', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'disable-forwarding']),
    ('set_ip_enable_arp_accept', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-arp-accept']),
    ('set_ip_enable_arp_announce', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-arp-announce']),
    ('set_ip_enable_arp_ignore', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-arp-ignore']),
    ('set_ip_enable_directed_broadcast', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-directed-broadcast']),
    ('set_ip_enable_proxy_arp', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'enable-proxy-arp']),
    ('set_ip_proxy_arp_pvlan', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'proxy-arp-pvlan']),
    ('set_ip_source_validation', ('peth0', 'nat'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ip', 'source-validation', 'nat']),
    ('set_ipv6_accept_dad', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'accept-dad', '5']),
    ('set_ipv6_address_autoconf', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'address', 'autoconf']),
    ('set_ipv6_address_eui64', ('peth0', '2001:db8::/32'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'address', 'eui64', '2001:db8::/32']),
    ('set_ipv6_address_no_default_link_local', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'address', 'no-default-link-local']),
    ('set_ipv6_adjust_mss', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'adjust-mss', '5']),
    ('set_ipv6_adjust_mss_clamp_to_pmtu', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'adjust-mss', 'clamp-mss-to-pmtu']),
    ('set_ipv6_base_reachable_time', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'base-reachable-time', '5']),
    ('set_ipv6_disable_forwarding', ('peth0',), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'disable-forwarding']),
    ('set_ipv6_dup_addr_detect_transmits', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_ipv6_source_validation', ('peth0', 'nat'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'source-validation', 'nat']),
    ('set_mac', ('peth0', '00:11:22:33:44:55'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'mac', '00:11:22:33:44:55']),
    ('set_mirror_egress', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'mirror', 'egress', '5']),
    ('set_mirror_ingress', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'mirror', 'ingress', '5']),
    ('set_mode', ('peth0', 'nat'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'mode', 'nat']),
    ('set_mtu', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'mtu', '5']),
    ('set_redirect', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'redirect', '5']),
    ('set_source_interface', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'source-interface', '5']),
    ('set_vif', ('peth0', '10'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10']),
    ('set_vif_address', ('peth0', '10', '192.0.2.1'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'address', '192.0.2.1']),
    ('set_vif_c', ('peth0', '10', '10'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10']),
    ('set_vif_c_address', ('peth0', '10', '10', '192.0.2.1'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'address', '192.0.2.1']),
    ('set_vif_c_description', ('peth0', '10', '10', 'lab'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'description', 'lab']),
    ('set_vif_c_disable', ('peth0', '10', '10'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'disable']),
    ('set_vif_c_mac', ('peth0', '10', '10', '00:11:22:33:44:55'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'mac', '00:11:22:33:44:55']),
    ('set_vif_c_mirror_egress', ('peth0', '10', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'egress', '5']),
    ('set_vif_c_mirror_ingress', ('peth0', '10', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'ingress', '5']),
    ('set_vif_c_mtu', ('peth0', '10', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'mtu', '5']),
    ('set_vif_c_redirect', ('peth0', '10', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'redirect', '5']),
    ('set_vif_c_vrf', ('peth0', '10', '10', 'red'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'vrf', 'red']),
    ('set_vif_description', ('peth0', '10', 'lab'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'description', 'lab']),
    ('set_vif_disable', ('peth0', '10'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'disable']),
    ('set_vif_disable_link_detect', ('peth0', '10'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'disable-link-detect']),
    ('set_vif_egress_qos', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'egress-qos', '5']),
    ('set_vif_ingress_qos', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'ingress-qos', '5']),
    ('set_vif_mac', ('peth0', '10', '00:11:22:33:44:55'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'mac', '00:11:22:33:44:55']),
    ('set_vif_mirror_egress', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'mirror', 'egress', '5']),
    ('set_vif_mirror_ingress', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'mirror', 'ingress', '5']),
    ('set_vif_mtu', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'mtu', '5']),
    ('set_vif_redirect', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'redirect', '5']),
    ('set_vif_s', ('peth0', '10'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10']),
    ('set_vif_s_address', ('peth0', '10', '192.0.2.1'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'address', '192.0.2.1']),
    ('set_vif_s_description', ('peth0', '10', 'lab'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'description', 'lab']),
    ('set_vif_s_disable', ('peth0', '10'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'disable']),
    ('set_vif_s_mac', ('peth0', '10', '00:11:22:33:44:55'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'mac', '00:11:22:33:44:55']),
    ('set_vif_s_mirror_egress', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'mirror', 'egress', '5']),
    ('set_vif_s_mirror_ingress', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'mirror', 'ingress', '5']),
    ('set_vif_s_mtu', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'mtu', '5']),
    ('set_vif_s_redirect', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'redirect', '5']),
    ('set_vif_s_vrf', ('peth0', '10', 'red'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vrf', 'red']),
    ('set_vif_vrf', ('peth0', '10', 'red'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'vrf', 'red']),
    ('set_vrf', ('peth0', 'red'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vrf', 'red']),
]


@pytest.mark.parametrize("method, args, op, expected_path", COMMON_CASES)
@pytest.mark.parametrize("version", ["1.4", "1.5"])
def test_pseudo_ethernet_common_paths(method, args, op, expected_path, version):
    _run(version, method, args, op, expected_path)

V15_ONLY_CASES = [
    ('delete_ipv6_address_interface_identifier', ('peth0',), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'address', 'interface-identifier']),
    ('delete_vif_c_ipv6_address_interface_identifier', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'interface-identifier']),
    ('delete_vif_c_ipv6_settings', ('peth0', '10', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'ipv6']),
    ('delete_vif_ipv6_address_interface_identifier', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'ipv6', 'address', 'interface-identifier']),
    ('delete_vif_ipv6_settings', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'ipv6']),
    ('delete_vif_s_ipv6_address_interface_identifier', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'ipv6', 'address', 'interface-identifier']),
    ('delete_vif_s_ipv6_settings', ('peth0', '10'), 'delete', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'ipv6']),
    ('set_ipv6_address_interface_identifier', ('peth0', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_vif_c_ipv6_address_interface_identifier', ('peth0', '10', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_vif_ipv6_address_interface_identifier', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif', '10', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_vif_s_ipv6_address_interface_identifier', ('peth0', '10', '5'), 'set', ['interfaces', 'pseudo-ethernet', 'peth0', 'vif-s', '10', 'ipv6', 'address', 'interface-identifier', '5']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V15_ONLY_CASES)
def test_pseudo_ethernet_v1_5_only_paths(method, args, op, expected_path):
    _run("1.5", method, args, op, expected_path)
