"""Golden (method, args, op, expected_path) cases for BridgeInterfaceBuilderMixin.

Paths checked with validateTmplPath on 1.4 (100.64.64.50) and 1.5 (100.64.64.5).
Generated for issue #721; edit the tables directly if the mapper changes.
"""

import pytest

from vyos_builders.interfaces.bridge import BridgeInterfaceBuilderMixin


def _run(version, method, args, op, expected_path):
    builder = BridgeInterfaceBuilderMixin(version=version)
    getattr(builder, method)(*args)
    operations = builder.get_operations()
    assert [(item["op"], item["path"]) for item in operations] == [(op, expected_path)]

COMMON_CASES = [
    ('delete_aging', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'aging']),
    ('delete_all_dhcp_options', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcp-options']),
    ('delete_all_dhcpv6_options', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcpv6-options']),
    ('delete_all_member_interface_allowed_vlans', ('br0', 'eth0'), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'allowed-vlan']),
    ('delete_all_members', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface']),
    ('delete_dhcp_options_client_id', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'client-id']),
    ('delete_dhcp_options_default_route_distance', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'default-route-distance']),
    ('delete_dhcp_options_host_name', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'host-name']),
    ('delete_dhcp_options_mtu', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'mtu']),
    ('delete_dhcp_options_no_default_route', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'no-default-route']),
    ('delete_dhcp_options_reject', ('br0', '5'), 'delete', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'reject', '5']),
    ('delete_dhcp_options_user_class', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'user-class']),
    ('delete_dhcp_options_vendor_class_id', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'vendor-class-id']),
    ('delete_dhcpv6_options_duid', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'duid']),
    ('delete_dhcpv6_options_no_release', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'no-release']),
    ('delete_dhcpv6_options_parameters_only', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'parameters-only']),
    ('delete_dhcpv6_options_rapid_commit', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'rapid-commit']),
    ('delete_dhcpv6_options_temporary', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'temporary']),
    ('delete_enable_vlan', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'enable-vlan']),
    ('delete_forwarding_delay', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'forwarding-delay']),
    ('delete_hello_time', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'hello-time']),
    ('delete_igmp', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'igmp']),
    ('delete_igmp_querier', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'igmp', 'querier']),
    ('delete_igmp_snooping', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'igmp', 'snooping']),
    ('delete_interface', ('br0',), 'delete', ['interfaces', 'bridge', 'br0']),
    ('delete_interface_address', ('br0', '192.0.2.1'), 'delete', ['interfaces', 'bridge', 'br0', 'address', '192.0.2.1']),
    ('delete_interface_description', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'description']),
    ('delete_interface_disable', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'disable']),
    ('delete_interface_disable_link_detect', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'disable-link-detect']),
    ('delete_interface_mac', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'mac']),
    ('delete_interface_mtu', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'mtu']),
    ('delete_interface_redirect', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'redirect']),
    ('delete_interface_vrf', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'vrf']),
    ('delete_ip_adjust_mss', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'adjust-mss']),
    ('delete_ip_arp_cache_timeout', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'arp-cache-timeout']),
    ('delete_ip_disable_arp_filter', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'disable-arp-filter']),
    ('delete_ip_disable_forwarding', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'disable-forwarding']),
    ('delete_ip_enable_arp_accept', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'enable-arp-accept']),
    ('delete_ip_enable_arp_announce', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'enable-arp-announce']),
    ('delete_ip_enable_arp_ignore', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'enable-arp-ignore']),
    ('delete_ip_enable_directed_broadcast', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'enable-directed-broadcast']),
    ('delete_ip_enable_proxy_arp', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'enable-proxy-arp']),
    ('delete_ip_proxy_arp_pvlan', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'proxy-arp-pvlan']),
    ('delete_ip_source_validation', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ip', 'source-validation']),
    ('delete_ipv6_accept_dad', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'accept-dad']),
    ('delete_ipv6_address_autoconf', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'address', 'autoconf']),
    ('delete_ipv6_address_eui64', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'address', 'eui64']),
    ('delete_ipv6_address_no_default_link_local', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'address', 'no-default-link-local']),
    ('delete_ipv6_adjust_mss', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'adjust-mss']),
    ('delete_ipv6_base_reachable_time', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'base-reachable-time']),
    ('delete_ipv6_disable_forwarding', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'disable-forwarding']),
    ('delete_ipv6_dup_addr_detect_transmits', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'dup-addr-detect-transmits']),
    ('delete_ipv6_source_validation', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'source-validation']),
    ('delete_max_age', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'max-age']),
    ('delete_member_interface', ('br0', 'eth0'), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0']),
    ('delete_member_interface_allowed_vlan', ('br0', 'eth0', '10'), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'allowed-vlan', '10']),
    ('delete_member_interface_cost', ('br0', 'eth0'), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'cost']),
    ('delete_member_interface_isolated', ('br0', 'eth0'), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'isolated']),
    ('delete_member_interface_native_vlan', ('br0', 'eth0'), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'native-vlan']),
    ('delete_member_interface_priority', ('br0', 'eth0'), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'priority']),
    ('delete_mirror_egress', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'mirror', 'egress']),
    ('delete_mirror_ingress', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'mirror', 'ingress']),
    ('delete_priority', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'priority']),
    ('delete_protocol', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'protocol']),
    ('delete_stp', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'stp']),
    ('delete_vif', ('br0', '10'), 'delete', ['interfaces', 'bridge', 'br0', 'vif', '10']),
    ('delete_vif_address', ('br0', '10', '192.0.2.1'), 'delete', ['interfaces', 'bridge', 'br0', 'vif', '10', 'address', '192.0.2.1']),
    ('delete_vif_description', ('br0', '10'), 'delete', ['interfaces', 'bridge', 'br0', 'vif', '10', 'description']),
    ('delete_vif_disable', ('br0', '10'), 'delete', ['interfaces', 'bridge', 'br0', 'vif', '10', 'disable']),
    ('delete_vif_mtu', ('br0', '10'), 'delete', ['interfaces', 'bridge', 'br0', 'vif', '10', 'mtu']),
    ('delete_vif_vrf', ('br0', '10'), 'delete', ['interfaces', 'bridge', 'br0', 'vif', '10', 'vrf']),
    ('set_aging', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'aging', '5']),
    ('set_dhcp_options_client_id', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'client-id', '5']),
    ('set_dhcp_options_default_route_distance', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'default-route-distance', '5']),
    ('set_dhcp_options_host_name', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'host-name', '5']),
    ('set_dhcp_options_mtu', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'mtu']),
    ('set_dhcp_options_no_default_route', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'no-default-route']),
    ('set_dhcp_options_reject', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'reject', '5']),
    ('set_dhcp_options_user_class', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'user-class', '5']),
    ('set_dhcp_options_vendor_class_id', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'dhcp-options', 'vendor-class-id', '5']),
    ('set_dhcpv6_options_duid', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'duid', '5']),
    ('set_dhcpv6_options_no_release', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'no-release']),
    ('set_dhcpv6_options_parameters_only', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'parameters-only']),
    ('set_dhcpv6_options_rapid_commit', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'rapid-commit']),
    ('set_dhcpv6_options_temporary', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'dhcpv6-options', 'temporary']),
    ('set_enable_vlan', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'enable-vlan']),
    ('set_forwarding_delay', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'forwarding-delay', '5']),
    ('set_hello_time', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'hello-time', '5']),
    ('set_igmp_querier', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'igmp', 'querier']),
    ('set_igmp_snooping', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'igmp', 'snooping']),
    ('set_interface', ('br0',), 'set', ['interfaces', 'bridge', 'br0']),
    ('set_interface_address', ('br0', '192.0.2.1'), 'set', ['interfaces', 'bridge', 'br0', 'address', '192.0.2.1']),
    ('set_interface_description', ('br0', 'lab'), 'set', ['interfaces', 'bridge', 'br0', 'description', 'lab']),
    ('set_interface_disable', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'disable']),
    ('set_interface_disable_link_detect', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'disable-link-detect']),
    ('set_interface_mac', ('br0', '00:11:22:33:44:55'), 'set', ['interfaces', 'bridge', 'br0', 'mac', '00:11:22:33:44:55']),
    ('set_interface_mtu', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'mtu', '5']),
    ('set_interface_redirect', ('br0', 'eth1'), 'set', ['interfaces', 'bridge', 'br0', 'redirect', 'eth1']),
    ('set_interface_vrf', ('br0', 'red'), 'set', ['interfaces', 'bridge', 'br0', 'vrf', 'red']),
    ('set_ip_adjust_mss', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'adjust-mss', '5']),
    ('set_ip_arp_cache_timeout', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'arp-cache-timeout', '5']),
    ('set_ip_disable_arp_filter', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'disable-arp-filter']),
    ('set_ip_disable_forwarding', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'disable-forwarding']),
    ('set_ip_enable_arp_accept', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'enable-arp-accept']),
    ('set_ip_enable_arp_announce', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'enable-arp-announce']),
    ('set_ip_enable_arp_ignore', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'enable-arp-ignore']),
    ('set_ip_enable_directed_broadcast', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'enable-directed-broadcast']),
    ('set_ip_enable_proxy_arp', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'enable-proxy-arp']),
    ('set_ip_proxy_arp_pvlan', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'proxy-arp-pvlan']),
    ('set_ip_source_validation', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ip', 'source-validation', '5']),
    ('set_ipv6_accept_dad', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'accept-dad', '5']),
    ('set_ipv6_address_autoconf', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'address', 'autoconf']),
    ('set_ipv6_address_eui64', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'address', 'eui64', '5']),
    ('set_ipv6_address_no_default_link_local', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'address', 'no-default-link-local']),
    ('set_ipv6_adjust_mss', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'adjust-mss', '5']),
    ('set_ipv6_base_reachable_time', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'base-reachable-time', '5']),
    ('set_ipv6_disable_forwarding', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'disable-forwarding']),
    ('set_ipv6_dup_addr_detect_transmits', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_ipv6_source_validation', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'source-validation', '5']),
    ('set_max_age', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'max-age', '5']),
    ('set_member_interface_allowed_vlan', ('br0', 'eth0', '10'), 'set', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'allowed-vlan', '10']),
    ('set_member_interface_cost', ('br0', 'eth0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'cost', '5']),
    ('set_member_interface_isolated', ('br0', 'eth0'), 'set', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'isolated']),
    ('set_member_interface_native_vlan', ('br0', 'eth0', '10'), 'set', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'native-vlan', '10']),
    ('set_member_interface_priority', ('br0', 'eth0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'priority', '5']),
    ('set_mirror_egress', ('br0', 'eth1'), 'set', ['interfaces', 'bridge', 'br0', 'mirror', 'egress', 'eth1']),
    ('set_mirror_ingress', ('br0', 'eth1'), 'set', ['interfaces', 'bridge', 'br0', 'mirror', 'ingress', 'eth1']),
    ('set_priority', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'priority', '5']),
    ('set_protocol', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'protocol', '5']),
    ('set_stp', ('br0',), 'set', ['interfaces', 'bridge', 'br0', 'stp']),
    ('set_vif', ('br0', '10'), 'set', ['interfaces', 'bridge', 'br0', 'vif', '10']),
    ('set_vif_address', ('br0', '10', '192.0.2.1'), 'set', ['interfaces', 'bridge', 'br0', 'vif', '10', 'address', '192.0.2.1']),
    ('set_vif_description', ('br0', '10', 'lab'), 'set', ['interfaces', 'bridge', 'br0', 'vif', '10', 'description', 'lab']),
    ('set_vif_disable', ('br0', '10'), 'set', ['interfaces', 'bridge', 'br0', 'vif', '10', 'disable']),
    ('set_vif_mtu', ('br0', '10', '5'), 'set', ['interfaces', 'bridge', 'br0', 'vif', '10', 'mtu', '5']),
    ('set_vif_vrf', ('br0', '10', 'red'), 'set', ['interfaces', 'bridge', 'br0', 'vif', '10', 'vrf', 'red']),
]


@pytest.mark.parametrize("method, args, op, expected_path", COMMON_CASES)
@pytest.mark.parametrize("version", ["1.4", "1.5"])
def test_bridge_common_paths(method, args, op, expected_path, version):
    _run(version, method, args, op, expected_path)

V15_ONLY_CASES = [
    ('delete_ipv6_address_interface_identifier', ('br0',), 'delete', ['interfaces', 'bridge', 'br0', 'ipv6', 'address', 'interface-identifier']),
    ('delete_member_interface_bpdu_guard', ('br0', 'eth0'), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'bpdu-guard']),
    ('delete_member_interface_root_guard', ('br0', 'eth0'), 'delete', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'root-guard']),
    ('set_ipv6_address_interface_identifier', ('br0', '5'), 'set', ['interfaces', 'bridge', 'br0', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_member_interface_bpdu_guard', ('br0', 'eth0'), 'set', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'bpdu-guard']),
    ('set_member_interface_root_guard', ('br0', 'eth0'), 'set', ['interfaces', 'bridge', 'br0', 'member', 'interface', 'eth0', 'root-guard']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V15_ONLY_CASES)
def test_bridge_v1_5_only_paths(method, args, op, expected_path):
    _run("1.5", method, args, op, expected_path)
