"""Golden (method, args, op, expected_path) cases for OpenvpnInterfaceBuilderMixin.

Paths checked with validateTmplPath on 1.4 (100.64.64.50) and 1.5 (100.64.64.5).
Generated for issue #721; edit the tables directly if the mapper changes.
"""

import pytest

from vyos_builders.interfaces.openvpn import OpenvpnInterfaceBuilderMixin


def _run(version, method, args, op, expected_path):
    builder = OpenvpnInterfaceBuilderMixin(version=version)
    getattr(builder, method)(*args)
    operations = builder.get_operations()
    assert [(item["op"], item["path"]) for item in operations] == [(op, expected_path)]

COMMON_CASES = [
    ('delete_authentication', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'authentication']),
    ('delete_authentication_password', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'authentication', 'password']),
    ('delete_authentication_username', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'authentication', 'username']),
    ('delete_device_type', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'device-type']),
    ('delete_encryption_cipher', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'encryption', 'cipher']),
    ('delete_hash', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'hash']),
    ('delete_interface', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0']),
    ('delete_interface_description', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'description']),
    ('delete_interface_disable', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'disable']),
    ('delete_ip_adjust_mss', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'adjust-mss']),
    ('delete_ip_arp_cache_timeout', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'arp-cache-timeout']),
    ('delete_ip_disable_arp_filter', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'disable-arp-filter']),
    ('delete_ip_disable_forwarding', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'disable-forwarding']),
    ('delete_ip_enable_arp_accept', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-arp-accept']),
    ('delete_ip_enable_arp_announce', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-arp-announce']),
    ('delete_ip_enable_arp_ignore', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-arp-ignore']),
    ('delete_ip_enable_directed_broadcast', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-directed-broadcast']),
    ('delete_ip_enable_proxy_arp', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-proxy-arp']),
    ('delete_ip_proxy_arp_pvlan', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'proxy-arp-pvlan']),
    ('delete_ip_settings', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip']),
    ('delete_ip_source_validation', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ip', 'source-validation']),
    ('delete_ipv6_accept_dad', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'accept-dad']),
    ('delete_ipv6_address_autoconf', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'address', 'autoconf']),
    ('delete_ipv6_address_eui64', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'address', 'eui64']),
    ('delete_ipv6_address_no_default_link_local', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'address', 'no-default-link-local']),
    ('delete_ipv6_adjust_mss', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'adjust-mss']),
    ('delete_ipv6_base_reachable_time', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'base-reachable-time']),
    ('delete_ipv6_disable_forwarding', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'disable-forwarding']),
    ('delete_ipv6_dup_addr_detect_transmits', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'dup-addr-detect-transmits']),
    ('delete_ipv6_settings', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6']),
    ('delete_ipv6_source_validation', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'source-validation']),
    ('delete_keep_alive', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'keep-alive']),
    ('delete_keep_alive_failure_count', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'keep-alive', 'failure-count']),
    ('delete_keep_alive_interval', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'keep-alive', 'interval']),
    ('delete_local_address', ('vtun0', '192.0.2.1'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'local-address', '192.0.2.1']),
    ('delete_local_address_subnet_mask', ('vtun0', '192.0.2.1'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'local-address', '192.0.2.1', 'subnet-mask']),
    ('delete_local_host', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'local-host']),
    ('delete_local_port', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'local-port']),
    ('delete_mirror_egress', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'mirror', 'egress']),
    ('delete_mirror_ingress', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'mirror', 'ingress']),
    ('delete_mode', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'mode']),
    ('delete_offload_dco', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'offload', 'dco']),
    ('delete_openvpn_option', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'openvpn-option', '5']),
    ('delete_openvpn_options', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'openvpn-option']),
    ('delete_persistent_tunnel', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'persistent-tunnel']),
    ('delete_protocol', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'protocol']),
    ('delete_redirect', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'redirect']),
    ('delete_remote_address', ('vtun0', '192.0.2.1'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'remote-address', '192.0.2.1']),
    ('delete_remote_host', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'remote-host', '5']),
    ('delete_remote_port', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'remote-port']),
    ('delete_replace_default_route', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'replace-default-route']),
    ('delete_replace_default_route_local', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'replace-default-route', 'local']),
    ('delete_server', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server']),
    ('delete_server_bridge', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge']),
    ('delete_server_bridge_disable', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'disable']),
    ('delete_server_bridge_gateway', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'gateway']),
    ('delete_server_bridge_start', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'start']),
    ('delete_server_bridge_stop', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'stop']),
    ('delete_server_bridge_subnet_mask', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'subnet-mask']),
    ('delete_server_client', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5']),
    ('delete_server_client_disable', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5', 'disable']),
    ('delete_server_client_ip', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5', 'ip']),
    ('delete_server_client_ip_pool', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ip-pool']),
    ('delete_server_client_ip_pool_disable', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ip-pool', 'disable']),
    ('delete_server_client_ip_pool_start', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ip-pool', 'start']),
    ('delete_server_client_ip_pool_stop', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ip-pool', 'stop']),
    ('delete_server_client_ip_pool_subnet_mask', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ip-pool', 'subnet-mask']),
    ('delete_server_client_ipv6_pool', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ipv6-pool']),
    ('delete_server_client_ipv6_pool_base', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ipv6-pool', 'base']),
    ('delete_server_client_ipv6_pool_disable', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ipv6-pool', 'disable']),
    ('delete_server_client_push_route', ('vtun0', '5', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5', 'push-route', '5']),
    ('delete_server_client_subnet', ('vtun0', '5', '10.0.0.0/8'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5', 'subnet', '10.0.0.0/8']),
    ('delete_server_domain_name', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'domain-name']),
    ('delete_server_max_connections', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'max-connections']),
    ('delete_server_mfa', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa']),
    ('delete_server_mfa_totp_challenge', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'challenge']),
    ('delete_server_mfa_totp_digits', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'digits']),
    ('delete_server_mfa_totp_drift', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'drift']),
    ('delete_server_mfa_totp_slop', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'slop']),
    ('delete_server_mfa_totp_step', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'step']),
    ('delete_server_name_server', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'name-server', '5']),
    ('delete_server_push_route', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'push-route', '5']),
    ('delete_server_push_route_metric', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'push-route', '5', 'metric']),
    ('delete_server_reject_unconfigured_clients', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'reject-unconfigured-clients']),
    ('delete_server_subnet', ('vtun0', '10.0.0.0/8'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'subnet', '10.0.0.0/8']),
    ('delete_server_topology', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'server', 'topology']),
    ('delete_shared_secret_key', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'shared-secret-key']),
    ('delete_tls', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'tls']),
    ('delete_tls_auth_key', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'tls', 'auth-key']),
    ('delete_tls_ca_certificate', ('vtun0', 'G0'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'tls', 'ca-certificate', 'G0']),
    ('delete_tls_certificate', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'tls', 'certificate']),
    ('delete_tls_crypt_key', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'tls', 'crypt-key']),
    ('delete_tls_dh_params', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'tls', 'dh-params']),
    ('delete_tls_peer_fingerprint', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'tls', 'peer-fingerprint', '5']),
    ('delete_tls_role', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'tls', 'role']),
    ('delete_tls_version_min', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'tls', 'tls-version-min']),
    ('delete_use_lzo_compression', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'use-lzo-compression']),
    ('delete_vrf', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'vrf']),
    ('set_authentication_password', ('vtun0', 'secret'), 'set', ['interfaces', 'openvpn', 'vtun0', 'authentication', 'password', 'secret']),
    ('set_authentication_username', ('vtun0', 'user1'), 'set', ['interfaces', 'openvpn', 'vtun0', 'authentication', 'username', 'user1']),
    ('set_device_type', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'device-type', '5']),
    ('set_encryption_cipher', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'encryption', 'cipher', '5']),
    ('set_hash', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'hash', '5']),
    ('set_interface_description', ('vtun0', 'lab'), 'set', ['interfaces', 'openvpn', 'vtun0', 'description', 'lab']),
    ('set_interface_disable', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'disable']),
    ('set_ip_adjust_mss', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'adjust-mss', '5']),
    ('set_ip_adjust_mss_clamp_to_pmtu', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'adjust-mss', 'clamp-mss-to-pmtu']),
    ('set_ip_arp_cache_timeout', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'arp-cache-timeout', '5']),
    ('set_ip_disable_arp_filter', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'disable-arp-filter']),
    ('set_ip_disable_forwarding', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'disable-forwarding']),
    ('set_ip_enable_arp_accept', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-arp-accept']),
    ('set_ip_enable_arp_announce', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-arp-announce']),
    ('set_ip_enable_arp_ignore', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-arp-ignore']),
    ('set_ip_enable_directed_broadcast', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-directed-broadcast']),
    ('set_ip_enable_proxy_arp', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'enable-proxy-arp']),
    ('set_ip_proxy_arp_pvlan', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'proxy-arp-pvlan']),
    ('set_ip_source_validation', ('vtun0', 'nat'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ip', 'source-validation', 'nat']),
    ('set_ipv6_accept_dad', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'accept-dad', '5']),
    ('set_ipv6_address_autoconf', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'address', 'autoconf']),
    ('set_ipv6_address_eui64', ('vtun0', '2001:db8::/32'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'address', 'eui64', '2001:db8::/32']),
    ('set_ipv6_address_no_default_link_local', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'address', 'no-default-link-local']),
    ('set_ipv6_adjust_mss', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'adjust-mss', '5']),
    ('set_ipv6_adjust_mss_clamp_to_pmtu', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'adjust-mss', 'clamp-mss-to-pmtu']),
    ('set_ipv6_base_reachable_time', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'base-reachable-time', '5']),
    ('set_ipv6_disable_forwarding', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'disable-forwarding']),
    ('set_ipv6_dup_addr_detect_transmits', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_ipv6_source_validation', ('vtun0', 'nat'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'source-validation', 'nat']),
    ('set_keep_alive_failure_count', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'keep-alive', 'failure-count', '5']),
    ('set_keep_alive_interval', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'keep-alive', 'interval', '5']),
    ('set_local_address', ('vtun0', '192.0.2.1'), 'set', ['interfaces', 'openvpn', 'vtun0', 'local-address', '192.0.2.1']),
    ('set_local_address_subnet_mask', ('vtun0', '192.0.2.1', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'local-address', '192.0.2.1', 'subnet-mask', '5']),
    ('set_local_host', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'local-host', '5']),
    ('set_local_port', ('vtun0', '8080'), 'set', ['interfaces', 'openvpn', 'vtun0', 'local-port', '8080']),
    ('set_mirror_egress', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'mirror', 'egress', '5']),
    ('set_mirror_ingress', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'mirror', 'ingress', '5']),
    ('set_mode', ('vtun0', 'nat'), 'set', ['interfaces', 'openvpn', 'vtun0', 'mode', 'nat']),
    ('set_offload_dco', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'offload', 'dco']),
    ('set_openvpn_option', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'openvpn-option', '5']),
    ('set_persistent_tunnel', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'persistent-tunnel']),
    ('set_protocol', ('vtun0', 'tcp'), 'set', ['interfaces', 'openvpn', 'vtun0', 'protocol', 'tcp']),
    ('set_redirect', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'redirect', '5']),
    ('set_remote_address', ('vtun0', '192.0.2.1'), 'set', ['interfaces', 'openvpn', 'vtun0', 'remote-address', '192.0.2.1']),
    ('set_remote_host', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'remote-host', '5']),
    ('set_remote_port', ('vtun0', '8080'), 'set', ['interfaces', 'openvpn', 'vtun0', 'remote-port', '8080']),
    ('set_replace_default_route', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'replace-default-route']),
    ('set_replace_default_route_local', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'replace-default-route', 'local']),
    ('set_server_bridge_disable', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'disable']),
    ('set_server_bridge_gateway', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'gateway', '5']),
    ('set_server_bridge_start', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'start', '5']),
    ('set_server_bridge_stop', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'stop', '5']),
    ('set_server_bridge_subnet_mask', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'bridge', 'subnet-mask', '5']),
    ('set_server_client', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5']),
    ('set_server_client_disable', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5', 'disable']),
    ('set_server_client_ip', ('vtun0', '5', '192.0.2.1'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5', 'ip', '192.0.2.1']),
    ('set_server_client_ip_pool_disable', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ip-pool', 'disable']),
    ('set_server_client_ip_pool_start', ('vtun0', '192.0.2.1'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ip-pool', 'start', '192.0.2.1']),
    ('set_server_client_ip_pool_stop', ('vtun0', '192.0.2.1'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ip-pool', 'stop', '192.0.2.1']),
    ('set_server_client_ip_pool_subnet_mask', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ip-pool', 'subnet-mask', '5']),
    ('set_server_client_ipv6_pool_base', ('vtun0', '2001:db8::/32'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ipv6-pool', 'base', '2001:db8::/32']),
    ('set_server_client_ipv6_pool_disable', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client-ipv6-pool', 'disable']),
    ('set_server_client_push_route', ('vtun0', '5', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5', 'push-route', '5']),
    ('set_server_client_subnet', ('vtun0', '5', '10.0.0.0/8'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'client', '5', 'subnet', '10.0.0.0/8']),
    ('set_server_domain_name', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'domain-name', '5']),
    ('set_server_max_connections', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'max-connections', '5']),
    ('set_server_mfa_totp_challenge', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'challenge', '5']),
    ('set_server_mfa_totp_digits', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'digits', '5']),
    ('set_server_mfa_totp_drift', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'drift', '5']),
    ('set_server_mfa_totp_slop', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'slop', '5']),
    ('set_server_mfa_totp_step', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'mfa', 'totp', 'step', '5']),
    ('set_server_name_server', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'name-server', '5']),
    ('set_server_push_route', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'push-route', '5']),
    ('set_server_push_route_metric', ('vtun0', '5', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'push-route', '5', 'metric', '5']),
    ('set_server_reject_unconfigured_clients', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'reject-unconfigured-clients']),
    ('set_server_subnet', ('vtun0', '10.0.0.0/8'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'subnet', '10.0.0.0/8']),
    ('set_server_topology', ('vtun0', 'red'), 'set', ['interfaces', 'openvpn', 'vtun0', 'server', 'topology', 'red']),
    ('set_shared_secret_key', ('vtun0', 'secret'), 'set', ['interfaces', 'openvpn', 'vtun0', 'shared-secret-key', 'secret']),
    ('set_tls_auth_key', ('vtun0', 'secret'), 'set', ['interfaces', 'openvpn', 'vtun0', 'tls', 'auth-key', 'secret']),
    ('set_tls_ca_certificate', ('vtun0', 'G0'), 'set', ['interfaces', 'openvpn', 'vtun0', 'tls', 'ca-certificate', 'G0']),
    ('set_tls_certificate', ('vtun0', 'G0'), 'set', ['interfaces', 'openvpn', 'vtun0', 'tls', 'certificate', 'G0']),
    ('set_tls_crypt_key', ('vtun0', 'secret'), 'set', ['interfaces', 'openvpn', 'vtun0', 'tls', 'crypt-key', 'secret']),
    ('set_tls_dh_params', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'tls', 'dh-params', '5']),
    ('set_tls_peer_fingerprint', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'tls', 'peer-fingerprint', '5']),
    ('set_tls_role', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'tls', 'role', '5']),
    ('set_tls_version_min', ('vtun0', '1.2'), 'set', ['interfaces', 'openvpn', 'vtun0', 'tls', 'tls-version-min', '1.2']),
    ('set_use_lzo_compression', ('vtun0',), 'set', ['interfaces', 'openvpn', 'vtun0', 'use-lzo-compression']),
    ('set_vrf', ('vtun0', 'red'), 'set', ['interfaces', 'openvpn', 'vtun0', 'vrf', 'red']),
]


@pytest.mark.parametrize("method, args, op, expected_path", COMMON_CASES)
@pytest.mark.parametrize("version", ["1.4", "1.5"])
def test_openvpn_common_paths(method, args, op, expected_path, version):
    _run(version, method, args, op, expected_path)

V15_ONLY_CASES = [
    ('delete_encryption_data_cipher', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'encryption', 'data-ciphers', '5']),
    ('delete_encryption_data_ciphers', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'encryption', 'data-ciphers']),
    ('delete_ipv6_address_interface_identifier', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'address', 'interface-identifier']),
    ('set_encryption_data_cipher', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'encryption', 'data-ciphers', '5']),
    ('set_ipv6_address_interface_identifier', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'ipv6', 'address', 'interface-identifier', '5']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V15_ONLY_CASES)
def test_openvpn_v1_5_only_paths(method, args, op, expected_path):
    _run("1.5", method, args, op, expected_path)

V14_ONLY_CASES = [
    ('delete_encryption_data_cipher', ('vtun0', '5'), 'delete', ['interfaces', 'openvpn', 'vtun0', 'encryption', 'ncp-ciphers', '5']),
    ('delete_encryption_data_ciphers', ('vtun0',), 'delete', ['interfaces', 'openvpn', 'vtun0', 'encryption', 'ncp-ciphers']),
    ('set_encryption_data_cipher', ('vtun0', '5'), 'set', ['interfaces', 'openvpn', 'vtun0', 'encryption', 'ncp-ciphers', '5']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V14_ONLY_CASES)
def test_openvpn_v1_4_only_paths(method, args, op, expected_path):
    _run("1.4", method, args, op, expected_path)
