"""Golden (method, args, op, expected_path) cases for WirelessInterfaceBuilderMixin.

Paths checked with validateTmplPath on 1.4 (100.64.64.50) and 1.5 (100.64.64.5).
Generated for issue #721; edit the tables directly if the mapper changes.
"""

import pytest

from vyos_builders.interfaces.wireless import WirelessInterfaceBuilderMixin


def _run(version, method, args, op, expected_path):
    builder = WirelessInterfaceBuilderMixin(version=version)
    getattr(builder, method)(*args)
    operations = builder.get_operations()
    assert [(item["op"], item["path"]) for item in operations] == [(op, expected_path)]

COMMON_CASES = [
    ('delete_cap_he', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he']),
    ('delete_cap_he_antenna_pattern_fixed', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'antenna-pattern-fixed']),
    ('delete_cap_he_bss_color', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'bss-color']),
    ('delete_cap_he_center_channel_freq_1', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'center-channel-freq', 'freq-1']),
    ('delete_cap_he_center_channel_freq_2', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'center-channel-freq', 'freq-2']),
    ('delete_cap_he_channel_set_width', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'channel-set-width']),
    ('delete_cap_he_coding_scheme', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'coding-scheme']),
    ('delete_cap_ht', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht']),
    ('delete_cap_ht_40mhz_incapable', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', '40mhz-incapable']),
    ('delete_cap_ht_auto_powersave', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'auto-powersave']),
    ('delete_cap_ht_channel_set_width', ('wlan0', '5'), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'channel-set-width', '5']),
    ('delete_cap_ht_channel_set_width_all', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'channel-set-width']),
    ('delete_cap_ht_delayed_block_ack', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'delayed-block-ack']),
    ('delete_cap_ht_dsss_cck_40', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'dsss-cck-40']),
    ('delete_cap_ht_greenfield', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'greenfield']),
    ('delete_cap_ht_ldpc', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'ldpc']),
    ('delete_cap_ht_lsig_protection', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'lsig-protection']),
    ('delete_cap_ht_max_amsdu', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'max-amsdu']),
    ('delete_cap_ht_short_gi', ('wlan0', '5'), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'short-gi', '5']),
    ('delete_cap_ht_short_gi_all', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'short-gi']),
    ('delete_cap_ht_smps', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'smps']),
    ('delete_cap_ht_stbc_rx', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'stbc', 'rx']),
    ('delete_cap_ht_stbc_tx', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'stbc', 'tx']),
    ('delete_cap_require_he', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'require-he']),
    ('delete_cap_require_ht', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'require-ht']),
    ('delete_cap_require_vht', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'require-vht']),
    ('delete_cap_vht', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht']),
    ('delete_cap_vht_antenna_count', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'antenna-count']),
    ('delete_cap_vht_antenna_pattern_fixed', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'antenna-pattern-fixed']),
    ('delete_cap_vht_beamform', ('wlan0', 'nat'), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'beamform', 'nat']),
    ('delete_cap_vht_beamform_all', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'beamform']),
    ('delete_cap_vht_center_channel_freq_1', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'center-channel-freq', 'freq-1']),
    ('delete_cap_vht_center_channel_freq_2', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'center-channel-freq', 'freq-2']),
    ('delete_cap_vht_channel_set_width', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'channel-set-width']),
    ('delete_cap_vht_ldpc', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'ldpc']),
    ('delete_cap_vht_link_adaptation', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'link-adaptation']),
    ('delete_cap_vht_max_mpdu', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'max-mpdu']),
    ('delete_cap_vht_max_mpdu_exp', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'max-mpdu-exp']),
    ('delete_cap_vht_short_gi', ('wlan0', '5'), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'short-gi', '5']),
    ('delete_cap_vht_short_gi_all', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'short-gi']),
    ('delete_cap_vht_stbc_rx', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'stbc', 'rx']),
    ('delete_cap_vht_stbc_tx', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'stbc', 'tx']),
    ('delete_cap_vht_tx_powersave', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'tx-powersave']),
    ('delete_cap_vht_vht_cf', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'vht-cf']),
    ('delete_capabilities', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'capabilities']),
    ('delete_disable_broadcast_ssid', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'disable-broadcast-ssid']),
    ('delete_enable_bf_protection', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'enable-bf-protection']),
    ('delete_expunge_failing_stations', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'expunge-failing-stations']),
    ('delete_interface', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0']),
    ('delete_interface_address', ('wlan0', '192.0.2.1'), 'delete', ['interfaces', 'wireless', 'wlan0', 'address', '192.0.2.1']),
    ('delete_interface_channel', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'channel']),
    ('delete_interface_description', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'description']),
    ('delete_interface_disable', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'disable']),
    ('delete_interface_hw_id', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'hw-id']),
    ('delete_interface_mac', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'mac']),
    ('delete_interface_mode', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'mode']),
    ('delete_interface_physical_device', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'physical-device']),
    ('delete_interface_ssid', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'ssid']),
    ('delete_interface_type', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'type']),
    ('delete_interface_vrf', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'vrf']),
    ('delete_ip_arp_cache_timeout', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'ip', 'arp-cache-timeout']),
    ('delete_ip_disable_forwarding', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'ip', 'disable-forwarding']),
    ('delete_ip_enable_proxy_arp', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'ip', 'enable-proxy-arp']),
    ('delete_ip_source_validation', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'ip', 'source-validation']),
    ('delete_ipv6_address_eui64', ('wlan0', '2001:db8::/32'), 'delete', ['interfaces', 'wireless', 'wlan0', 'ipv6', 'address', 'eui64', '2001:db8::/32']),
    ('delete_ipv6_address_eui64_all', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'ipv6', 'address', 'eui64']),
    ('delete_ipv6_address_no_default_link_local', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'ipv6', 'address', 'no-default-link-local']),
    ('delete_ipv6_disable_forwarding', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'ipv6', 'disable-forwarding']),
    ('delete_isolate_stations', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'isolate-stations']),
    ('delete_max_stations', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'max-stations']),
    ('delete_mgmt_frame_protection', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'mgmt-frame-protection']),
    ('delete_mirror_egress', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'mirror', 'egress']),
    ('delete_mirror_ingress', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'mirror', 'ingress']),
    ('delete_per_client_thread', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'per-client-thread']),
    ('delete_redirect', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'redirect']),
    ('delete_reduce_transmit_power', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'reduce-transmit-power']),
    ('delete_security', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security']),
    ('delete_security_station_accept_all', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'station-address', 'accept']),
    ('delete_security_station_accept_mac', ('wlan0', '00:11:22:33:44:55'), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'station-address', 'accept', 'mac', '00:11:22:33:44:55']),
    ('delete_security_station_address_mode', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'station-address', 'mode']),
    ('delete_security_station_deny_all', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'station-address', 'deny']),
    ('delete_security_station_deny_mac', ('wlan0', '00:11:22:33:44:55'), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'station-address', 'deny', 'mac', '00:11:22:33:44:55']),
    ('delete_security_wep', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wep']),
    ('delete_security_wpa', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa']),
    ('delete_security_wpa_cipher', ('wlan0', '5'), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'cipher', '5']),
    ('delete_security_wpa_cipher_all', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'cipher']),
    ('delete_security_wpa_group_cipher', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'group-cipher']),
    ('delete_security_wpa_group_mgmt_cipher', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'group-mgmt-cipher']),
    ('delete_security_wpa_mode', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'mode']),
    ('delete_security_wpa_passphrase', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'passphrase']),
    ('delete_security_wpa_radius_server', ('wlan0', '192.0.2.1'), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'server', '192.0.2.1']),
    ('delete_security_wpa_radius_server_accounting', ('wlan0', '192.0.2.1'), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'server', '192.0.2.1', 'accounting']),
    ('delete_security_wpa_radius_server_disable', ('wlan0', '192.0.2.1'), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'server', '192.0.2.1', 'disable']),
    ('delete_security_wpa_radius_source_address', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'source-address']),
    ('delete_stationary_ap', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'stationary-ap']),
    ('set_cap_he_antenna_pattern_fixed', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'antenna-pattern-fixed']),
    ('set_cap_he_bss_color', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'bss-color', '5']),
    ('set_cap_he_center_channel_freq_1', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'center-channel-freq', 'freq-1', '5']),
    ('set_cap_he_center_channel_freq_2', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'center-channel-freq', 'freq-2', '5']),
    ('set_cap_he_channel_set_width', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'channel-set-width', '5']),
    ('set_cap_he_coding_scheme', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'he', 'coding-scheme', '5']),
    ('set_cap_ht_40mhz_incapable', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', '40mhz-incapable']),
    ('set_cap_ht_auto_powersave', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'auto-powersave']),
    ('set_cap_ht_channel_set_width', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'channel-set-width', '5']),
    ('set_cap_ht_delayed_block_ack', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'delayed-block-ack']),
    ('set_cap_ht_dsss_cck_40', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'dsss-cck-40']),
    ('set_cap_ht_greenfield', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'greenfield']),
    ('set_cap_ht_ldpc', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'ldpc']),
    ('set_cap_ht_lsig_protection', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'lsig-protection']),
    ('set_cap_ht_max_amsdu', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'max-amsdu', '5']),
    ('set_cap_ht_short_gi', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'short-gi', '5']),
    ('set_cap_ht_smps', ('wlan0', 'nat'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'smps', 'nat']),
    ('set_cap_ht_stbc_rx', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'stbc', 'rx', '5']),
    ('set_cap_ht_stbc_tx', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'ht', 'stbc', 'tx']),
    ('set_cap_require_he', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'require-he']),
    ('set_cap_require_ht', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'require-ht']),
    ('set_cap_require_vht', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'require-vht']),
    ('set_cap_vht_antenna_count', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'antenna-count', '5']),
    ('set_cap_vht_antenna_pattern_fixed', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'antenna-pattern-fixed']),
    ('set_cap_vht_beamform', ('wlan0', 'nat'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'beamform', 'nat']),
    ('set_cap_vht_center_channel_freq_1', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'center-channel-freq', 'freq-1', '5']),
    ('set_cap_vht_center_channel_freq_2', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'center-channel-freq', 'freq-2', '5']),
    ('set_cap_vht_channel_set_width', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'channel-set-width', '5']),
    ('set_cap_vht_ldpc', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'ldpc']),
    ('set_cap_vht_link_adaptation', ('wlan0', 'nat'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'link-adaptation', 'nat']),
    ('set_cap_vht_max_mpdu', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'max-mpdu', '5']),
    ('set_cap_vht_max_mpdu_exp', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'max-mpdu-exp', '5']),
    ('set_cap_vht_short_gi', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'short-gi', '5']),
    ('set_cap_vht_stbc_rx', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'stbc', 'rx', '5']),
    ('set_cap_vht_stbc_tx', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'stbc', 'tx']),
    ('set_cap_vht_tx_powersave', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'tx-powersave']),
    ('set_cap_vht_vht_cf', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'capabilities', 'vht', 'vht-cf']),
    ('set_disable_broadcast_ssid', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'disable-broadcast-ssid']),
    ('set_enable_bf_protection', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'enable-bf-protection']),
    ('set_expunge_failing_stations', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'expunge-failing-stations']),
    ('set_interface_address', ('wlan0', '192.0.2.1'), 'set', ['interfaces', 'wireless', 'wlan0', 'address', '192.0.2.1']),
    ('set_interface_channel', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'channel', '5']),
    ('set_interface_description', ('wlan0', 'lab'), 'set', ['interfaces', 'wireless', 'wlan0', 'description', 'lab']),
    ('set_interface_disable', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'disable']),
    ('set_interface_hw_id', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'hw-id', '5']),
    ('set_interface_mac', ('wlan0', '00:11:22:33:44:55'), 'set', ['interfaces', 'wireless', 'wlan0', 'mac', '00:11:22:33:44:55']),
    ('set_interface_mode', ('wlan0', 'nat'), 'set', ['interfaces', 'wireless', 'wlan0', 'mode', 'nat']),
    ('set_interface_physical_device', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'physical-device', '5']),
    ('set_interface_ssid', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'ssid', '5']),
    ('set_interface_type', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'type', '5']),
    ('set_interface_vrf', ('wlan0', 'red'), 'set', ['interfaces', 'wireless', 'wlan0', 'vrf', 'red']),
    ('set_ip_arp_cache_timeout', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'ip', 'arp-cache-timeout', '5']),
    ('set_ip_disable_forwarding', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'ip', 'disable-forwarding']),
    ('set_ip_enable_proxy_arp', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'ip', 'enable-proxy-arp']),
    ('set_ip_source_validation', ('wlan0', 'nat'), 'set', ['interfaces', 'wireless', 'wlan0', 'ip', 'source-validation', 'nat']),
    ('set_ipv6_address_eui64', ('wlan0', '2001:db8::/32'), 'set', ['interfaces', 'wireless', 'wlan0', 'ipv6', 'address', 'eui64', '2001:db8::/32']),
    ('set_ipv6_address_no_default_link_local', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'ipv6', 'address', 'no-default-link-local']),
    ('set_ipv6_disable_forwarding', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'ipv6', 'disable-forwarding']),
    ('set_isolate_stations', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'isolate-stations']),
    ('set_max_stations', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'max-stations', '5']),
    ('set_mgmt_frame_protection', ('wlan0', 'nat'), 'set', ['interfaces', 'wireless', 'wlan0', 'mgmt-frame-protection', 'nat']),
    ('set_mirror_egress', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'mirror', 'egress', '5']),
    ('set_mirror_ingress', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'mirror', 'ingress', '5']),
    ('set_per_client_thread', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'per-client-thread']),
    ('set_redirect', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'redirect', '5']),
    ('set_reduce_transmit_power', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'reduce-transmit-power']),
    ('set_security_station_accept_mac', ('wlan0', '00:11:22:33:44:55'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'station-address', 'accept', 'mac', '00:11:22:33:44:55']),
    ('set_security_station_address_mode', ('wlan0', 'nat'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'station-address', 'mode', 'nat']),
    ('set_security_station_deny_mac', ('wlan0', '00:11:22:33:44:55'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'station-address', 'deny', 'mac', '00:11:22:33:44:55']),
    ('set_security_wep_key', ('wlan0', 'secret'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wep', 'key', 'secret']),
    ('set_security_wpa_cipher', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'cipher', '5']),
    ('set_security_wpa_group_cipher', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'group-cipher', '5']),
    ('set_security_wpa_group_mgmt_cipher', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'group-mgmt-cipher', '5']),
    ('set_security_wpa_mode', ('wlan0', 'nat'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'mode', 'nat']),
    ('set_security_wpa_passphrase', ('wlan0', 'secret'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'passphrase', 'secret']),
    ('set_security_wpa_radius_server', ('wlan0', '192.0.2.1'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'server', '192.0.2.1']),
    ('set_security_wpa_radius_server_accounting', ('wlan0', '192.0.2.1'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'server', '192.0.2.1', 'accounting']),
    ('set_security_wpa_radius_server_disable', ('wlan0', '192.0.2.1'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'server', '192.0.2.1', 'disable']),
    ('set_security_wpa_radius_server_key', ('wlan0', '192.0.2.1:secret'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'server', '192.0.2.1', 'key', 'secret']),
    ('set_security_wpa_radius_server_port', ('wlan0', '192.0.2.1:1812'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'server', '192.0.2.1', 'port', '1812']),
    ('set_security_wpa_radius_source_address', ('wlan0', '192.0.2.1'), 'set', ['interfaces', 'wireless', 'wlan0', 'security', 'wpa', 'radius', 'source-address', '192.0.2.1']),
    ('set_stationary_ap', ('wlan0',), 'set', ['interfaces', 'wireless', 'wlan0', 'stationary-ap']),
]


@pytest.mark.parametrize("method, args, op, expected_path", COMMON_CASES)
@pytest.mark.parametrize("version", ["1.4", "1.5"])
def test_wireless_common_paths(method, args, op, expected_path, version):
    _run(version, method, args, op, expected_path)

V15_ONLY_CASES = [
    ('delete_bssid', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'bssid']),
    ('set_bssid', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'bssid', '5']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V15_ONLY_CASES)
def test_wireless_v1_5_only_paths(method, args, op, expected_path):
    _run("1.5", method, args, op, expected_path)

V14_ONLY_CASES = [
    ('delete_country_code', ('wlan0',), 'delete', ['interfaces', 'wireless', 'wlan0', 'country-code']),
    ('set_country_code', ('wlan0', '5'), 'set', ['interfaces', 'wireless', 'wlan0', 'country-code', '5']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V14_ONLY_CASES)
def test_wireless_v1_4_only_paths(method, args, op, expected_path):
    _run("1.4", method, args, op, expected_path)
