"""Golden (method, args, op, expected_path) cases for L2TPBatchBuilder.

Paths checked with validateTmplPath on 1.4 (100.64.64.50) and 1.5 (100.64.64.5).
Generated for issue #737; edit the tables directly if the mapper changes.
"""

import pytest

from vyos_builders.l2tp.l2tp import L2TPBatchBuilder


def _run(version, method, args, op, expected_path):
    builder = L2TPBatchBuilder(version=version)
    getattr(builder, method)(*args)
    operations = builder.get_operations()
    assert [(item["op"], item["path"]) for item in operations] == [(op, expected_path)]

COMMON_CASES = [
    ('delete_auth_mode', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'mode']),
    ('delete_auth_protocols', ('G0', 'tcp'), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'protocols', 'tcp']),
    ('delete_client_ip_pool', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'client-ip-pool', 'G0']),
    ('delete_client_ip_pool_next_pool', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'client-ip-pool', 'G0', 'next-pool']),
    ('delete_client_ip_pool_range', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'client-ip-pool', 'G0', 'range']),
    ('delete_client_ipv6_pool', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'client-ipv6-pool', 'G0']),
    ('delete_default_ipv6_pool', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'default-ipv6-pool']),
    ('delete_default_pool', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'default-pool']),
    ('delete_description', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'description']),
    ('delete_extended_scripts_on_change', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'extended-scripts', 'on-change']),
    ('delete_extended_scripts_on_down', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'extended-scripts', 'on-down']),
    ('delete_extended_scripts_on_pre_up', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'extended-scripts', 'on-pre-up']),
    ('delete_extended_scripts_on_up', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'extended-scripts', 'on-up']),
    ('delete_gateway_address', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'gateway-address']),
    ('delete_ipsec_auth_mode', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'mode']),
    ('delete_ipsec_esp_group', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'esp-group']),
    ('delete_ipsec_ike_group', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'ike-group']),
    ('delete_ipsec_ike_lifetime', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'ike-lifetime']),
    ('delete_ipsec_lifetime', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'lifetime']),
    ('delete_ipsec_psk', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'pre-shared-secret']),
    ('delete_ipsec_x509_ca_certificate', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'x509', 'ca-certificate']),
    ('delete_ipsec_x509_certificate', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'x509', 'certificate']),
    ('delete_ipsec_x509_passphrase', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'x509', 'passphrase']),
    ('delete_l2tp', ('G0',), 'delete', ['vpn', 'l2tp']),
    ('delete_limits_burst', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'limits', 'burst']),
    ('delete_limits_connection_limit', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'limits', 'connection-limit']),
    ('delete_limits_timeout', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'limits', 'timeout']),
    ('delete_lns_host_name', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'lns', 'host-name']),
    ('delete_lns_shared_secret', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'lns', 'shared-secret']),
    ('delete_local_user', ('user1',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1']),
    ('delete_local_user_disable', ('user1',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1', 'disable']),
    ('delete_local_user_rate_limit_download', ('user1',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1', 'rate-limit', 'download']),
    ('delete_local_user_rate_limit_upload', ('user1',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1', 'rate-limit', 'upload']),
    ('delete_local_user_static_ip', ('user1',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1', 'static-ip']),
    ('delete_log_level', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'log', 'level']),
    ('delete_max_concurrent_sessions', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'max-concurrent-sessions']),
    ('delete_mtu', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'mtu']),
    ('delete_name_server', ('G0', '192.0.2.1'), 'delete', ['vpn', 'l2tp', 'remote-access', 'name-server', '192.0.2.1']),
    ('delete_outside_address', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'outside-address']),
    ('delete_ppp_disable_ccp', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'disable-ccp']),
    ('delete_ppp_interface_cache', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'interface-cache']),
    ('delete_ppp_ipv4', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv4']),
    ('delete_ppp_ipv6', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv6']),
    ('delete_ppp_ipv6_accept_peer_interface_id', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv6-accept-peer-interface-id']),
    ('delete_ppp_ipv6_interface_id', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv6-interface-id']),
    ('delete_ppp_ipv6_peer_interface_id', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv6-peer-interface-id']),
    ('delete_ppp_lcp_echo_failure', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'lcp-echo-failure']),
    ('delete_ppp_lcp_echo_interval', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'lcp-echo-interval']),
    ('delete_ppp_lcp_echo_timeout', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'lcp-echo-timeout']),
    ('delete_ppp_min_mtu', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'min-mtu']),
    ('delete_ppp_mppe', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'mppe']),
    ('delete_ppp_mru', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'mru']),
    ('delete_radius_accounting_interim_interval', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'accounting-interim-interval']),
    ('delete_radius_acct_interim_jitter', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'acct-interim-jitter']),
    ('delete_radius_acct_timeout', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'acct-timeout']),
    ('delete_radius_dae_key', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'dynamic-author', 'key']),
    ('delete_radius_dae_port', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'dynamic-author', 'port']),
    ('delete_radius_dae_server', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'dynamic-author', 'server']),
    ('delete_radius_max_try', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'max-try']),
    ('delete_radius_nas_identifier', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'nas-identifier']),
    ('delete_radius_nas_ip_address', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'nas-ip-address']),
    ('delete_radius_preallocate_vif', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'preallocate-vif']),
    ('delete_radius_rate_limit_attribute', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'rate-limit', 'attribute']),
    ('delete_radius_rate_limit_enable', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'rate-limit', 'enable']),
    ('delete_radius_rate_limit_multiplier', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'rate-limit', 'multiplier']),
    ('delete_radius_rate_limit_vendor', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'rate-limit', 'vendor']),
    ('delete_radius_server', ('G0', '192.0.2.1'), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1']),
    ('delete_radius_server_backup', ('G0', '192.0.2.1'), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'backup']),
    ('delete_radius_server_disable', ('G0', '192.0.2.1'), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'disable']),
    ('delete_radius_server_disable_accounting', ('G0', '192.0.2.1'), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'disable-accounting']),
    ('delete_radius_source_address', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'source-address']),
    ('delete_radius_timeout', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'timeout']),
    ('delete_shaper_fwmark', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'shaper', 'fwmark']),
    ('delete_snmp_master_agent', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'snmp', 'master-agent']),
    ('delete_thread_count', ('G0',), 'delete', ['vpn', 'l2tp', 'remote-access', 'thread-count']),
    ('delete_wins_server', ('G0', '192.0.2.1'), 'delete', ['vpn', 'l2tp', 'remote-access', 'wins-server', '192.0.2.1']),
    ('set_auth_mode', ('G0', 'nat'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'mode', 'nat']),
    ('set_auth_protocols', ('G0', 'tcp'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'protocols', 'tcp']),
    ('set_client_ip_pool_next_pool', ('G0', 'G0'), 'set', ['vpn', 'l2tp', 'remote-access', 'client-ip-pool', 'G0', 'next-pool', 'G0']),
    ('set_client_ip_pool_range', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'client-ip-pool', 'G0', 'range', '5']),
    ('set_client_ipv6_pool_delegate', ('G0', '2001:db8::/32'), 'set', ['vpn', 'l2tp', 'remote-access', 'client-ipv6-pool', 'G0', 'delegate', '2001:db8::/32']),
    ('set_client_ipv6_pool_delegate_prefix', ('G0', '2001:db8::/32|64'), 'set', ['vpn', 'l2tp', 'remote-access', 'client-ipv6-pool', 'G0', 'delegate', '2001:db8::/32', 'delegation-prefix', '64']),
    ('set_client_ipv6_pool_prefix', ('G0', '2001:db8::/32'), 'set', ['vpn', 'l2tp', 'remote-access', 'client-ipv6-pool', 'G0', 'prefix', '2001:db8::/32']),
    ('set_client_ipv6_pool_prefix_mask', ('G0', '2001:db8::/32|64'), 'set', ['vpn', 'l2tp', 'remote-access', 'client-ipv6-pool', 'G0', 'prefix', '2001:db8::/32', 'mask', '64']),
    ('set_default_ipv6_pool', ('G0', 'G0'), 'set', ['vpn', 'l2tp', 'remote-access', 'default-ipv6-pool', 'G0']),
    ('set_default_pool', ('G0', 'G0'), 'set', ['vpn', 'l2tp', 'remote-access', 'default-pool', 'G0']),
    ('set_description', ('G0', 'lab'), 'set', ['vpn', 'l2tp', 'remote-access', 'description', 'lab']),
    ('set_extended_scripts_on_change', ('G0', '/config/scripts/x.sh'), 'set', ['vpn', 'l2tp', 'remote-access', 'extended-scripts', 'on-change', '/config/scripts/x.sh']),
    ('set_extended_scripts_on_down', ('G0', '/config/scripts/x.sh'), 'set', ['vpn', 'l2tp', 'remote-access', 'extended-scripts', 'on-down', '/config/scripts/x.sh']),
    ('set_extended_scripts_on_pre_up', ('G0', '/config/scripts/x.sh'), 'set', ['vpn', 'l2tp', 'remote-access', 'extended-scripts', 'on-pre-up', '/config/scripts/x.sh']),
    ('set_extended_scripts_on_up', ('G0', '/config/scripts/x.sh'), 'set', ['vpn', 'l2tp', 'remote-access', 'extended-scripts', 'on-up', '/config/scripts/x.sh']),
    ('set_gateway_address', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'gateway-address', '192.0.2.1']),
    ('set_ipsec_auth_mode', ('G0', 'nat'), 'set', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'mode', 'nat']),
    ('set_ipsec_esp_group', ('G0', 'G0'), 'set', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'esp-group', 'G0']),
    ('set_ipsec_ike_group', ('G0', 'G0'), 'set', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'ike-group', 'G0']),
    ('set_ipsec_ike_lifetime', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'ike-lifetime', '5']),
    ('set_ipsec_lifetime', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'lifetime', '5']),
    ('set_ipsec_psk', ('G0', 'secret'), 'set', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'pre-shared-secret', 'secret']),
    ('set_ipsec_x509_ca_certificate', ('G0', 'G0'), 'set', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'x509', 'ca-certificate', 'G0']),
    ('set_ipsec_x509_certificate', ('G0', 'G0'), 'set', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'x509', 'certificate', 'G0']),
    ('set_ipsec_x509_passphrase', ('G0', 'secret'), 'set', ['vpn', 'l2tp', 'remote-access', 'ipsec-settings', 'authentication', 'x509', 'passphrase', 'secret']),
    ('set_limits_burst', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'limits', 'burst', '5']),
    ('set_limits_connection_limit', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'limits', 'connection-limit', '5']),
    ('set_limits_timeout', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'limits', 'timeout', '5']),
    ('set_lns_host_name', ('G0', 'G0'), 'set', ['vpn', 'l2tp', 'remote-access', 'lns', 'host-name', 'G0']),
    ('set_lns_shared_secret', ('G0', 'secret'), 'set', ['vpn', 'l2tp', 'remote-access', 'lns', 'shared-secret', 'secret']),
    ('set_local_user_disable', ('user1',), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1', 'disable']),
    ('set_local_user_password', ('user1', 'secret'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1', 'password', 'secret']),
    ('set_local_user_rate_limit_download', ('user1', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1', 'rate-limit', 'download', '5']),
    ('set_local_user_rate_limit_upload', ('user1', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1', 'rate-limit', 'upload', '5']),
    ('set_local_user_static_ip', ('user1', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'local-users', 'username', 'user1', 'static-ip', '192.0.2.1']),
    ('set_log_level', ('G0', '1'), 'set', ['vpn', 'l2tp', 'remote-access', 'log', 'level', '1']),
    ('set_max_concurrent_sessions', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'max-concurrent-sessions', '5']),
    ('set_mtu', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'mtu', '5']),
    ('set_name_server', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'name-server', '192.0.2.1']),
    ('set_outside_address', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'outside-address', '192.0.2.1']),
    ('set_ppp_disable_ccp', ('G0',), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'disable-ccp']),
    ('set_ppp_interface_cache', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'interface-cache', '5']),
    ('set_ppp_ipv4', ('G0', 'nat'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv4', 'nat']),
    ('set_ppp_ipv6', ('G0', 'nat'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv6', 'nat']),
    ('set_ppp_ipv6_accept_peer_interface_id', ('G0',), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv6-accept-peer-interface-id']),
    ('set_ppp_ipv6_interface_id', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv6-interface-id', '5']),
    ('set_ppp_ipv6_peer_interface_id', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'ipv6-peer-interface-id', '5']),
    ('set_ppp_lcp_echo_failure', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'lcp-echo-failure', '5']),
    ('set_ppp_lcp_echo_interval', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'lcp-echo-interval', '5']),
    ('set_ppp_lcp_echo_timeout', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'lcp-echo-timeout', '5']),
    ('set_ppp_min_mtu', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'min-mtu', '5']),
    ('set_ppp_mppe', ('G0', 'nat'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'mppe', 'nat']),
    ('set_ppp_mru', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'ppp-options', 'mru', '5']),
    ('set_radius_accounting_interim_interval', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'accounting-interim-interval', '5']),
    ('set_radius_acct_interim_jitter', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'acct-interim-jitter', '5']),
    ('set_radius_acct_timeout', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'acct-timeout', '5']),
    ('set_radius_dae_key', ('G0', 'secret'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'dynamic-author', 'key', 'secret']),
    ('set_radius_dae_port', ('G0', '8080'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'dynamic-author', 'port', '8080']),
    ('set_radius_dae_server', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'dynamic-author', 'server', '192.0.2.1']),
    ('set_radius_max_try', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'max-try', '5']),
    ('set_radius_nas_identifier', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'nas-identifier', '5']),
    ('set_radius_nas_ip_address', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'nas-ip-address', '192.0.2.1']),
    ('set_radius_preallocate_vif', ('G0',), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'preallocate-vif']),
    ('set_radius_rate_limit_attribute', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'rate-limit', 'attribute', '5']),
    ('set_radius_rate_limit_enable', ('G0',), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'rate-limit', 'enable']),
    ('set_radius_rate_limit_multiplier', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'rate-limit', 'multiplier', '5']),
    ('set_radius_rate_limit_vendor', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'rate-limit', 'vendor', '5']),
    ('set_radius_server_acct_port', ('G0', '192.0.2.1|1813'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'acct-port', '1813']),
    ('set_radius_server_backup', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'backup']),
    ('set_radius_server_disable', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'disable']),
    ('set_radius_server_disable_accounting', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'disable-accounting']),
    ('set_radius_server_fail_time', ('G0', '192.0.2.1|5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'fail-time', '5']),
    ('set_radius_server_key', ('G0', '192.0.2.1|secret'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'key', 'secret']),
    ('set_radius_server_port', ('G0', '192.0.2.1|1812'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'port', '1812']),
    ('set_radius_server_priority', ('G0', '192.0.2.1|5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'server', '192.0.2.1', 'priority', '5']),
    ('set_radius_source_address', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'source-address', '192.0.2.1']),
    ('set_radius_timeout', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'authentication', 'radius', 'timeout', '5']),
    ('set_shaper_fwmark', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'shaper', 'fwmark', '5']),
    ('set_snmp_master_agent', ('G0',), 'set', ['vpn', 'l2tp', 'remote-access', 'snmp', 'master-agent']),
    ('set_thread_count', ('G0', '5'), 'set', ['vpn', 'l2tp', 'remote-access', 'thread-count', '5']),
    ('set_wins_server', ('G0', '192.0.2.1'), 'set', ['vpn', 'l2tp', 'remote-access', 'wins-server', '192.0.2.1']),
]


@pytest.mark.parametrize("method, args, op, expected_path", COMMON_CASES)
@pytest.mark.parametrize("version", ["1.4", "1.5"])
def test_l2tp_common_paths(method, args, op, expected_path, version):
    _run(version, method, args, op, expected_path)
