"""Golden (method, args, op, expected_path) cases for LoadBalancingBatchBuilder.

Paths checked with validateTmplPath on 1.4 (100.64.64.50) and 1.5 (100.64.64.5).
1.4 uses load-balancing reverse-proxy. 1.5 uses load-balancing haproxy.
Version-split leaves raise on 1.4. WAN rule group deletes stay unguarded on
1.4; that path is lab-rejected, so it is asserted only on 1.5.
"""

import inspect

import pytest

from vyos_builders.load_balancing import LoadBalancingBatchBuilder


def _run(version, method, args, op, expected_path):
    builder = LoadBalancingBatchBuilder(version=version)
    getattr(builder, method)(*args)
    operations = builder.get_operations()
    assert [(item["op"], item["path"]) for item in operations] == [(op, expected_path)]


COMMON_CASES = [
    ('create_wan_interface_health', ('eth0',), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0']),
    ('create_wan_interface_health_test', ('eth0', '1'), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0', 'test', '1']),
    ('create_wan_rule', ('10',), 'set', ['load-balancing', 'wan', 'rule', '10']),
    ('delete_wan_disable_source_nat', ('',), 'delete', ['load-balancing', 'wan', 'disable-source-nat']),
    ('delete_wan_enable_local_traffic', ('',), 'delete', ['load-balancing', 'wan', 'enable-local-traffic']),
    ('delete_wan_flush_connections', ('',), 'delete', ['load-balancing', 'wan', 'flush-connections']),
    ('delete_wan_hook', ('',), 'delete', ['load-balancing', 'wan', 'hook']),
    ('delete_wan_interface_health', ('eth0',), 'delete', ['load-balancing', 'wan', 'interface-health', 'eth0']),
    ('delete_wan_interface_health_failure_count', ('eth0',), 'delete', ['load-balancing', 'wan', 'interface-health', 'eth0', 'failure-count']),
    ('delete_wan_interface_health_nexthop', ('eth0',), 'delete', ['load-balancing', 'wan', 'interface-health', 'eth0', 'nexthop']),
    ('delete_wan_interface_health_success_count', ('eth0',), 'delete', ['load-balancing', 'wan', 'interface-health', 'eth0', 'success-count']),
    ('delete_wan_interface_health_test', ('eth0', '1'), 'delete', ['load-balancing', 'wan', 'interface-health', 'eth0', 'test', '1']),
    ('delete_wan_rule', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10']),
    ('delete_wan_rule_description', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'description']),
    ('delete_wan_rule_destination', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'destination']),
    ('delete_wan_rule_destination_address', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'destination', 'address']),
    ('delete_wan_rule_destination_port', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'destination', 'port']),
    ('delete_wan_rule_exclude', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'exclude']),
    ('delete_wan_rule_failover', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'failover']),
    ('delete_wan_rule_inbound_interface', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'inbound-interface']),
    ('delete_wan_rule_interface', ('10', 'eth0'), 'delete', ['load-balancing', 'wan', 'rule', '10', 'interface', 'eth0']),
    ('delete_wan_rule_limit', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'limit']),
    ('delete_wan_rule_per_packet_balancing', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'per-packet-balancing']),
    ('delete_wan_rule_protocol', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'protocol']),
    ('delete_wan_rule_source', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'source']),
    ('delete_wan_rule_source_address', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'source', 'address']),
    ('delete_wan_rule_source_port', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'source', 'port']),
    ('delete_wan_sticky_connections', ('',), 'delete', ['load-balancing', 'wan', 'sticky-connections']),
    ('set_wan_disable_source_nat', ('',), 'set', ['load-balancing', 'wan', 'disable-source-nat']),
    ('set_wan_enable_local_traffic', ('',), 'set', ['load-balancing', 'wan', 'enable-local-traffic']),
    ('set_wan_flush_connections', ('',), 'set', ['load-balancing', 'wan', 'flush-connections']),
    ('set_wan_hook', ('', '/config/scripts/wlb-hook.sh'), 'set', ['load-balancing', 'wan', 'hook', '/config/scripts/wlb-hook.sh']),
    ('set_wan_interface_health_failure_count', ('eth0', '3'), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0', 'failure-count', '3']),
    ('set_wan_interface_health_nexthop', ('eth0', '192.0.2.1'), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0', 'nexthop', '192.0.2.1']),
    ('set_wan_interface_health_success_count', ('eth0', '2'), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0', 'success-count', '2']),
    ('set_wan_interface_health_test_resp_time', ('eth0', '1|5'), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0', 'test', '1', 'resp-time', '5']),
    ('set_wan_interface_health_test_script', ('eth0', '1|/config/scripts/wlb-hook.sh'), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0', 'test', '1', 'test-script', '/config/scripts/wlb-hook.sh']),
    ('set_wan_interface_health_test_target', ('eth0', '1|192.0.2.1'), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0', 'test', '1', 'target', '192.0.2.1']),
    ('set_wan_interface_health_test_ttl_limit', ('eth0', '1|1'), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0', 'test', '1', 'ttl-limit', '1']),
    ('set_wan_interface_health_test_type', ('eth0', '1|ping'), 'set', ['load-balancing', 'wan', 'interface-health', 'eth0', 'test', '1', 'type', 'ping']),
    ('set_wan_rule_description', ('10', 'lab'), 'set', ['load-balancing', 'wan', 'rule', '10', 'description', 'lab']),
    ('set_wan_rule_destination_address', ('10', '198.51.100.0/24'), 'set', ['load-balancing', 'wan', 'rule', '10', 'destination', 'address', '198.51.100.0/24']),
    ('set_wan_rule_destination_port', ('10', '443'), 'set', ['load-balancing', 'wan', 'rule', '10', 'destination', 'port', '443']),
    ('set_wan_rule_exclude', ('10',), 'set', ['load-balancing', 'wan', 'rule', '10', 'exclude']),
    ('set_wan_rule_failover', ('10',), 'set', ['load-balancing', 'wan', 'rule', '10', 'failover']),
    ('set_wan_rule_inbound_interface', ('10', 'eth1'), 'set', ['load-balancing', 'wan', 'rule', '10', 'inbound-interface', 'eth1']),
    ('set_wan_rule_interface', ('10', 'eth0'), 'set', ['load-balancing', 'wan', 'rule', '10', 'interface', 'eth0']),
    ('set_wan_rule_interface_weight', ('10', 'eth0|1'), 'set', ['load-balancing', 'wan', 'rule', '10', 'interface', 'eth0', 'weight', '1']),
    ('set_wan_rule_limit_burst', ('10', '5'), 'set', ['load-balancing', 'wan', 'rule', '10', 'limit', 'burst', '5']),
    ('set_wan_rule_limit_period', ('10', 'second'), 'set', ['load-balancing', 'wan', 'rule', '10', 'limit', 'period', 'second']),
    ('set_wan_rule_limit_rate', ('10', '10'), 'set', ['load-balancing', 'wan', 'rule', '10', 'limit', 'rate', '10']),
    ('set_wan_rule_limit_threshold', ('10', '5'), 'set', ['load-balancing', 'wan', 'rule', '10', 'limit', 'threshold', '5']),
    ('set_wan_rule_per_packet_balancing', ('10',), 'set', ['load-balancing', 'wan', 'rule', '10', 'per-packet-balancing']),
    ('set_wan_rule_protocol', ('10', 'tcp'), 'set', ['load-balancing', 'wan', 'rule', '10', 'protocol', 'tcp']),
    ('set_wan_rule_source_address', ('10', '192.0.2.0/24'), 'set', ['load-balancing', 'wan', 'rule', '10', 'source', 'address', '192.0.2.0/24']),
    ('set_wan_rule_source_port', ('10', '80'), 'set', ['load-balancing', 'wan', 'rule', '10', 'source', 'port', '80']),
    ('set_wan_sticky_connections_inbound', ('',), 'set', ['load-balancing', 'wan', 'sticky-connections', 'inbound']),
]


@pytest.mark.parametrize("method, args, op, expected_path", COMMON_CASES)
@pytest.mark.parametrize("version", ["1.4", "1.5"])
def test_load_balancing_common_paths(method, args, op, expected_path, version):
    _run(version, method, args, op, expected_path)


V14_CASES = [
    ('create_rp_backend', ('bk',), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk']),
    ('create_rp_backend_rule', ('bk', '10'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10']),
    ('create_rp_backend_server', ('bk', 's1'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1']),
    ('create_rp_service', ('svc',), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc']),
    ('create_rp_service_rule', ('svc', '10'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10']),
    ('delete_rp_backend', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk']),
    ('delete_rp_backend_balance', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'balance']),
    ('delete_rp_backend_description', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'description']),
    ('delete_rp_backend_health_check', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'health-check']),
    ('delete_rp_backend_http_check', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'http-check']),
    ('delete_rp_backend_http_response_header', ('bk', 'X-Test'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'http-response-headers', 'X-Test']),
    ('delete_rp_backend_logging_facility', ('bk', 'local0'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'logging', 'facility', 'local0']),
    ('delete_rp_backend_mode', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'mode']),
    ('delete_rp_backend_rule', ('bk', '10'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10']),
    ('delete_rp_backend_rule_domain_name', ('bk', '10|example.com'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'domain-name', 'example.com']),
    ('delete_rp_backend_rule_set', ('bk', '10'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'set']),
    ('delete_rp_backend_rule_ssl', ('bk', '10'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'ssl']),
    ('delete_rp_backend_rule_url_path', ('bk', '10'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'url-path']),
    ('delete_rp_backend_server', ('bk', 's1'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1']),
    ('delete_rp_backend_server_backup', ('bk', 's1'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'backup']),
    ('delete_rp_backend_server_check', ('bk', 's1'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'check']),
    ('delete_rp_backend_server_port', ('bk', 's1'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'port']),
    ('delete_rp_backend_server_send_proxy', ('bk', 's1'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'send-proxy']),
    ('delete_rp_backend_server_send_proxy_v2', ('bk', 's1'), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'send-proxy-v2']),
    ('delete_rp_backend_ssl', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'ssl']),
    ('delete_rp_backend_ssl_ca_certificate', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'ssl', 'ca-certificate']),
    ('delete_rp_backend_ssl_no_verify', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'ssl', 'no-verify']),
    ('delete_rp_backend_timeout_check', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'timeout', 'check']),
    ('delete_rp_backend_timeout_connect', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'timeout', 'connect']),
    ('delete_rp_backend_timeout_server', ('bk',), 'delete', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'timeout', 'server']),
    ('delete_rp_global_logging_facility', ('', 'local0'), 'delete', ['load-balancing', 'reverse-proxy', 'global-parameters', 'logging', 'facility', 'local0']),
    ('delete_rp_global_max_connections', ('',), 'delete', ['load-balancing', 'reverse-proxy', 'global-parameters', 'max-connections']),
    ('delete_rp_global_ssl_bind_cipher', ('', 'ECDHE-RSA-AES128-GCM-SHA256'), 'delete', ['load-balancing', 'reverse-proxy', 'global-parameters', 'ssl-bind-ciphers', 'ECDHE-RSA-AES128-GCM-SHA256']),
    ('delete_rp_global_ssl_bind_ciphers', ('',), 'delete', ['load-balancing', 'reverse-proxy', 'global-parameters', 'ssl-bind-ciphers']),
    ('delete_rp_global_tls_version_min', ('',), 'delete', ['load-balancing', 'reverse-proxy', 'global-parameters', 'tls-version-min']),
    ('delete_rp_service', ('svc',), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc']),
    ('delete_rp_service_backend', ('svc', 'bk'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'backend', 'bk']),
    ('delete_rp_service_description', ('svc',), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'description']),
    ('delete_rp_service_http_response_header', ('svc', 'X-Test'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'http-response-headers', 'X-Test']),
    ('delete_rp_service_listen_address', ('svc', '192.0.2.1'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'listen-address', '192.0.2.1']),
    ('delete_rp_service_logging_facility', ('svc', 'local0'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'logging', 'facility', 'local0']),
    ('delete_rp_service_mode', ('svc',), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'mode']),
    ('delete_rp_service_port', ('svc',), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'port']),
    ('delete_rp_service_redirect_http_to_https', ('svc',), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'redirect-http-to-https']),
    ('delete_rp_service_rule', ('svc', '10'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10']),
    ('delete_rp_service_rule_domain_name', ('svc', '10|example.com'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'domain-name', 'example.com']),
    ('delete_rp_service_rule_set', ('svc', '10'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'set']),
    ('delete_rp_service_rule_ssl', ('svc', '10'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'ssl']),
    ('delete_rp_service_rule_url_path', ('svc', '10'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'url-path']),
    ('delete_rp_service_ssl', ('svc',), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'ssl']),
    ('delete_rp_service_ssl_certificate', ('svc', 'lab-cert'), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'ssl', 'certificate', 'lab-cert']),
    ('delete_rp_service_tcp_request', ('svc',), 'delete', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'tcp-request']),
    ('delete_rp_vrf', ('',), 'delete', ['load-balancing', 'reverse-proxy', 'vrf']),
    ('set_rp_backend_balance', ('bk', 'round-robin'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'balance', 'round-robin']),
    ('set_rp_backend_description', ('bk', 'lab'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'description', 'lab']),
    ('set_rp_backend_health_check', ('bk', 'smtp'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'health-check', 'smtp']),
    ('set_rp_backend_http_check_expect_status', ('bk', '200'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'http-check', 'expect', 'status', '200']),
    ('set_rp_backend_http_check_expect_string', ('bk', 'ok'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'http-check', 'expect', 'string', 'ok']),
    ('set_rp_backend_http_check_method', ('bk', 'get'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'http-check', 'method', 'get']),
    ('set_rp_backend_http_check_uri', ('bk', '/'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'http-check', 'uri', '/']),
    ('set_rp_backend_http_response_header', ('bk', 'X-Test|ok'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'http-response-headers', 'X-Test', 'value', 'ok']),
    ('set_rp_backend_logging_facility_level', ('bk', 'local0|info'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'logging', 'facility', 'local0', 'level', 'info']),
    ('set_rp_backend_mode', ('bk', 'http'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'mode', 'http']),
    ('set_rp_backend_rule_domain_name', ('bk', '10|example.com'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'domain-name', 'example.com']),
    ('set_rp_backend_rule_set_redirect_location', ('bk', '10|https://example.com/'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'set', 'redirect-location', 'https://example.com/']),
    ('set_rp_backend_rule_set_server', ('bk', '10|s1'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'set', 'server', 's1']),
    ('set_rp_backend_rule_ssl', ('bk', '10|req-ssl-sni'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'ssl', 'req-ssl-sni']),
    ('set_rp_backend_rule_url_path_begin', ('bk', '10|/api'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'url-path', 'begin', '/api']),
    ('set_rp_backend_rule_url_path_end', ('bk', '10|.html'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'url-path', 'end', '.html']),
    ('set_rp_backend_rule_url_path_exact', ('bk', '10|/exact'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'rule', '10', 'url-path', 'exact', '/exact']),
    ('set_rp_backend_server_address', ('bk', 's1|192.0.2.1'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'address', '192.0.2.1']),
    ('set_rp_backend_server_backup', ('bk', 's1'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'backup']),
    ('set_rp_backend_server_check', ('bk', 's1'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'check']),
    ('set_rp_backend_server_port', ('bk', 's1|8080'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'port', '8080']),
    ('set_rp_backend_server_send_proxy', ('bk', 's1'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'send-proxy']),
    ('set_rp_backend_server_send_proxy_v2', ('bk', 's1'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'server', 's1', 'send-proxy-v2']),
    ('set_rp_backend_ssl_ca_certificate', ('bk', 'ca-lab'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'ssl', 'ca-certificate', 'ca-lab']),
    ('set_rp_backend_ssl_no_verify', ('bk',), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'ssl', 'no-verify']),
    ('set_rp_backend_timeout_check', ('bk', '5'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'timeout', 'check', '5']),
    ('set_rp_backend_timeout_connect', ('bk', '5'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'timeout', 'connect', '5']),
    ('set_rp_backend_timeout_server', ('bk', '30'), 'set', ['load-balancing', 'reverse-proxy', 'backend', 'bk', 'timeout', 'server', '30']),
    ('set_rp_global_logging_facility_level', ('', 'local0|info'), 'set', ['load-balancing', 'reverse-proxy', 'global-parameters', 'logging', 'facility', 'local0', 'level', 'info']),
    ('set_rp_global_max_connections', ('', '4096'), 'set', ['load-balancing', 'reverse-proxy', 'global-parameters', 'max-connections', '4096']),
    ('set_rp_global_ssl_bind_cipher', ('', 'ECDHE-RSA-AES128-GCM-SHA256'), 'set', ['load-balancing', 'reverse-proxy', 'global-parameters', 'ssl-bind-ciphers', 'ECDHE-RSA-AES128-GCM-SHA256']),
    ('set_rp_global_tls_version_min', ('', '1.2'), 'set', ['load-balancing', 'reverse-proxy', 'global-parameters', 'tls-version-min', '1.2']),
    ('set_rp_service_backend', ('svc', 'bk'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'backend', 'bk']),
    ('set_rp_service_description', ('svc', 'lab'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'description', 'lab']),
    ('set_rp_service_http_response_header', ('svc', 'X-Test|ok'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'http-response-headers', 'X-Test', 'value', 'ok']),
    ('set_rp_service_listen_address', ('svc', '192.0.2.1'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'listen-address', '192.0.2.1']),
    ('set_rp_service_logging_facility_level', ('svc', 'local0|info'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'logging', 'facility', 'local0', 'level', 'info']),
    ('set_rp_service_mode', ('svc', 'http'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'mode', 'http']),
    ('set_rp_service_port', ('svc', '443'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'port', '443']),
    ('set_rp_service_redirect_http_to_https', ('svc',), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'redirect-http-to-https']),
    ('set_rp_service_rule_domain_name', ('svc', '10|example.com'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'domain-name', 'example.com']),
    ('set_rp_service_rule_set_backend', ('svc', '10|bk'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'set', 'backend', 'bk']),
    ('set_rp_service_rule_set_redirect_location', ('svc', '10|https://example.com/'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'set', 'redirect-location', 'https://example.com/']),
    ('set_rp_service_rule_ssl', ('svc', '10|req-ssl-sni'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'ssl', 'req-ssl-sni']),
    ('set_rp_service_rule_url_path_begin', ('svc', '10|/api'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'url-path', 'begin', '/api']),
    ('set_rp_service_rule_url_path_end', ('svc', '10|.html'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'url-path', 'end', '.html']),
    ('set_rp_service_rule_url_path_exact', ('svc', '10|/exact'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'rule', '10', 'url-path', 'exact', '/exact']),
    ('set_rp_service_ssl_certificate', ('svc', 'lab-cert'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'ssl', 'certificate', 'lab-cert']),
    ('set_rp_service_tcp_request_inspect_delay', ('svc', '5'), 'set', ['load-balancing', 'reverse-proxy', 'service', 'svc', 'tcp-request', 'inspect-delay', '5']),
    ('set_rp_vrf', ('', 'default'), 'set', ['load-balancing', 'reverse-proxy', 'vrf', 'default']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V14_CASES)
def test_load_balancing_v1_4_paths(method, args, op, expected_path):
    _run("1.4", method, args, op, expected_path)


V15_CASES = [
    ('create_rp_backend', ('bk',), 'set', ['load-balancing', 'haproxy', 'backend', 'bk']),
    ('create_rp_backend_rule', ('bk', '10'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10']),
    ('create_rp_backend_server', ('bk', 's1'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1']),
    ('create_rp_service', ('svc',), 'set', ['load-balancing', 'haproxy', 'service', 'svc']),
    ('create_rp_service_rule', ('svc', '10'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10']),
    ('delete_rp_backend', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk']),
    ('delete_rp_backend_balance', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'balance']),
    ('delete_rp_backend_description', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'description']),
    ('delete_rp_backend_health_check', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'health-check']),
    ('delete_rp_backend_http_check', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'http-check']),
    ('delete_rp_backend_http_response_header', ('bk', 'X-Test'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'http-response-headers', 'X-Test']),
    ('delete_rp_backend_logging_facility', ('bk', 'local0'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'logging', 'facility', 'local0']),
    ('delete_rp_backend_mode', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'mode']),
    ('delete_rp_backend_rule', ('bk', '10'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10']),
    ('delete_rp_backend_rule_domain_name', ('bk', '10|example.com'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'domain-name', 'example.com']),
    ('delete_rp_backend_rule_set', ('bk', '10'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'set']),
    ('delete_rp_backend_rule_ssl', ('bk', '10'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'ssl']),
    ('delete_rp_backend_rule_url_path', ('bk', '10'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'url-path']),
    ('delete_rp_backend_rule_wildcard_domain', ('bk', '10'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'wildcard-domain']),
    ('delete_rp_backend_server', ('bk', 's1'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1']),
    ('delete_rp_backend_server_backup', ('bk', 's1'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'backup']),
    ('delete_rp_backend_server_check', ('bk', 's1'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'check']),
    ('delete_rp_backend_server_check_port', ('bk', 's1'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'check', 'port']),
    ('delete_rp_backend_server_port', ('bk', 's1'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'port']),
    ('delete_rp_backend_server_send_proxy', ('bk', 's1'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'send-proxy']),
    ('delete_rp_backend_server_send_proxy_v2', ('bk', 's1'), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'send-proxy-v2']),
    ('delete_rp_backend_ssl', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'ssl']),
    ('delete_rp_backend_ssl_ca_certificate', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'ssl', 'ca-certificate']),
    ('delete_rp_backend_ssl_no_verify', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'ssl', 'no-verify']),
    ('delete_rp_backend_timeout_check', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'timeout', 'check']),
    ('delete_rp_backend_timeout_connect', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'timeout', 'connect']),
    ('delete_rp_backend_timeout_server', ('bk',), 'delete', ['load-balancing', 'haproxy', 'backend', 'bk', 'timeout', 'server']),
    ('delete_rp_global_logging_facility', ('', 'local0'), 'delete', ['load-balancing', 'haproxy', 'global-parameters', 'logging', 'facility', 'local0']),
    ('delete_rp_global_max_connections', ('',), 'delete', ['load-balancing', 'haproxy', 'global-parameters', 'max-connections']),
    ('delete_rp_global_ssl_bind_cipher', ('', 'ECDHE-RSA-AES128-GCM-SHA256'), 'delete', ['load-balancing', 'haproxy', 'global-parameters', 'ssl-bind-ciphers', 'ECDHE-RSA-AES128-GCM-SHA256']),
    ('delete_rp_global_ssl_bind_ciphers', ('',), 'delete', ['load-balancing', 'haproxy', 'global-parameters', 'ssl-bind-ciphers']),
    ('delete_rp_global_tls_version_min', ('',), 'delete', ['load-balancing', 'haproxy', 'global-parameters', 'tls-version-min']),
    ('delete_rp_service', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc']),
    ('delete_rp_service_backend', ('svc', 'bk'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'backend', 'bk']),
    ('delete_rp_service_description', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'description']),
    ('delete_rp_service_http_compression', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'http-compression']),
    ('delete_rp_service_http_compression_algorithm', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'http-compression', 'algorithm']),
    ('delete_rp_service_http_compression_mime_type', ('svc', 'text/html'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'http-compression', 'mime-type', 'text/html']),
    ('delete_rp_service_http_response_header', ('svc', 'X-Test'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'http-response-headers', 'X-Test']),
    ('delete_rp_service_listen_address', ('svc', '192.0.2.1'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'listen-address', '192.0.2.1']),
    ('delete_rp_service_listen_address_accept_proxy', ('svc', '192.0.2.1'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'listen-address', '192.0.2.1', 'accept-proxy']),
    ('delete_rp_service_logging_facility', ('svc', 'local0'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'logging', 'facility', 'local0']),
    ('delete_rp_service_mode', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'mode']),
    ('delete_rp_service_port', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'port']),
    ('delete_rp_service_redirect_http_to_https', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'redirect-http-to-https']),
    ('delete_rp_service_rule', ('svc', '10'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10']),
    ('delete_rp_service_rule_domain_name', ('svc', '10|example.com'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'domain-name', 'example.com']),
    ('delete_rp_service_rule_set', ('svc', '10'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'set']),
    ('delete_rp_service_rule_ssl', ('svc', '10'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'ssl']),
    ('delete_rp_service_rule_url_path', ('svc', '10'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'url-path']),
    ('delete_rp_service_rule_wildcard_domain', ('svc', '10'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'wildcard-domain']),
    ('delete_rp_service_ssl', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'ssl']),
    ('delete_rp_service_ssl_certificate', ('svc', 'lab-cert'), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'ssl', 'certificate', 'lab-cert']),
    ('delete_rp_service_tcp_request', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'tcp-request']),
    ('delete_rp_service_timeout', ('svc',), 'delete', ['load-balancing', 'haproxy', 'service', 'svc', 'timeout']),
    ('delete_rp_timeout_check', ('',), 'delete', ['load-balancing', 'haproxy', 'timeout', 'check']),
    ('delete_rp_timeout_client', ('',), 'delete', ['load-balancing', 'haproxy', 'timeout', 'client']),
    ('delete_rp_timeout_connect', ('',), 'delete', ['load-balancing', 'haproxy', 'timeout', 'connect']),
    ('delete_rp_timeout_server', ('',), 'delete', ['load-balancing', 'haproxy', 'timeout', 'server']),
    ('delete_rp_vrf', ('',), 'delete', ['load-balancing', 'haproxy', 'vrf']),
    ('delete_wan_rule_destination_group', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'destination', 'group']),
    ('delete_wan_rule_source_group', ('10',), 'delete', ['load-balancing', 'wan', 'rule', '10', 'source', 'group']),
    ('set_rp_backend_balance', ('bk', 'round-robin'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'balance', 'round-robin']),
    ('set_rp_backend_description', ('bk', 'lab'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'description', 'lab']),
    ('set_rp_backend_health_check', ('bk', 'smtp'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'health-check', 'smtp']),
    ('set_rp_backend_http_check_expect_status', ('bk', '200'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'http-check', 'expect', 'status', '200']),
    ('set_rp_backend_http_check_expect_string', ('bk', 'ok'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'http-check', 'expect', 'string', 'ok']),
    ('set_rp_backend_http_check_method', ('bk', 'get'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'http-check', 'method', 'get']),
    ('set_rp_backend_http_check_uri', ('bk', '/'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'http-check', 'uri', '/']),
    ('set_rp_backend_http_response_header', ('bk', 'X-Test|ok'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'http-response-headers', 'X-Test', 'value', 'ok']),
    ('set_rp_backend_logging_facility_level', ('bk', 'local0|info'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'logging', 'facility', 'local0', 'level', 'info']),
    ('set_rp_backend_mode', ('bk', 'http'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'mode', 'http']),
    ('set_rp_backend_rule_domain_name', ('bk', '10|example.com'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'domain-name', 'example.com']),
    ('set_rp_backend_rule_set_redirect_location', ('bk', '10|https://example.com/'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'set', 'redirect-location', 'https://example.com/']),
    ('set_rp_backend_rule_set_server', ('bk', '10|s1'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'set', 'server', 's1']),
    ('set_rp_backend_rule_ssl', ('bk', '10|req-ssl-sni'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'ssl', 'req-ssl-sni']),
    ('set_rp_backend_rule_url_path_begin', ('bk', '10|/api'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'url-path', 'begin', '/api']),
    ('set_rp_backend_rule_url_path_end', ('bk', '10|.html'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'url-path', 'end', '.html']),
    ('set_rp_backend_rule_url_path_exact', ('bk', '10|/exact'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'url-path', 'exact', '/exact']),
    ('set_rp_backend_rule_wildcard_domain', ('bk', '10'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'rule', '10', 'wildcard-domain']),
    ('set_rp_backend_server_address', ('bk', 's1|192.0.2.1'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'address', '192.0.2.1']),
    ('set_rp_backend_server_backup', ('bk', 's1'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'backup']),
    ('set_rp_backend_server_check', ('bk', 's1'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'check']),
    ('set_rp_backend_server_check_port', ('bk', 's1|8080'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'check', 'port', '8080']),
    ('set_rp_backend_server_port', ('bk', 's1|8080'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'port', '8080']),
    ('set_rp_backend_server_send_proxy', ('bk', 's1'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'send-proxy']),
    ('set_rp_backend_server_send_proxy_v2', ('bk', 's1'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'server', 's1', 'send-proxy-v2']),
    ('set_rp_backend_ssl_ca_certificate', ('bk', 'ca-lab'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'ssl', 'ca-certificate', 'ca-lab']),
    ('set_rp_backend_ssl_no_verify', ('bk',), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'ssl', 'no-verify']),
    ('set_rp_backend_timeout_check', ('bk', '5'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'timeout', 'check', '5']),
    ('set_rp_backend_timeout_connect', ('bk', '5'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'timeout', 'connect', '5']),
    ('set_rp_backend_timeout_server', ('bk', '30'), 'set', ['load-balancing', 'haproxy', 'backend', 'bk', 'timeout', 'server', '30']),
    ('set_rp_global_logging_facility_level', ('', 'local0|info'), 'set', ['load-balancing', 'haproxy', 'global-parameters', 'logging', 'facility', 'local0', 'level', 'info']),
    ('set_rp_global_max_connections', ('', '4096'), 'set', ['load-balancing', 'haproxy', 'global-parameters', 'max-connections', '4096']),
    ('set_rp_global_ssl_bind_cipher', ('', 'ECDHE-RSA-AES128-GCM-SHA256'), 'set', ['load-balancing', 'haproxy', 'global-parameters', 'ssl-bind-ciphers', 'ECDHE-RSA-AES128-GCM-SHA256']),
    ('set_rp_global_tls_version_min', ('', '1.2'), 'set', ['load-balancing', 'haproxy', 'global-parameters', 'tls-version-min', '1.2']),
    ('set_rp_service_backend', ('svc', 'bk'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'backend', 'bk']),
    ('set_rp_service_description', ('svc', 'lab'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'description', 'lab']),
    ('set_rp_service_http_compression_algorithm', ('svc', 'gzip'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'http-compression', 'algorithm', 'gzip']),
    ('set_rp_service_http_compression_mime_type', ('svc', 'text/html'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'http-compression', 'mime-type', 'text/html']),
    ('set_rp_service_http_response_header', ('svc', 'X-Test|ok'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'http-response-headers', 'X-Test', 'value', 'ok']),
    ('set_rp_service_listen_address', ('svc', '192.0.2.1'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'listen-address', '192.0.2.1']),
    ('set_rp_service_listen_address_accept_proxy', ('svc', '192.0.2.1'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'listen-address', '192.0.2.1', 'accept-proxy']),
    ('set_rp_service_logging_facility_level', ('svc', 'local0|info'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'logging', 'facility', 'local0', 'level', 'info']),
    ('set_rp_service_mode', ('svc', 'http'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'mode', 'http']),
    ('set_rp_service_port', ('svc', '443'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'port', '443']),
    ('set_rp_service_redirect_http_to_https', ('svc',), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'redirect-http-to-https']),
    ('set_rp_service_rule_domain_name', ('svc', '10|example.com'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'domain-name', 'example.com']),
    ('set_rp_service_rule_set_backend', ('svc', '10|bk'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'set', 'backend', 'bk']),
    ('set_rp_service_rule_set_redirect_location', ('svc', '10|https://example.com/'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'set', 'redirect-location', 'https://example.com/']),
    ('set_rp_service_rule_ssl', ('svc', '10|req-ssl-sni'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'ssl', 'req-ssl-sni']),
    ('set_rp_service_rule_url_path_begin', ('svc', '10|/api'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'url-path', 'begin', '/api']),
    ('set_rp_service_rule_url_path_end', ('svc', '10|.html'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'url-path', 'end', '.html']),
    ('set_rp_service_rule_url_path_exact', ('svc', '10|/exact'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'url-path', 'exact', '/exact']),
    ('set_rp_service_rule_wildcard_domain', ('svc', '10'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'rule', '10', 'wildcard-domain']),
    ('set_rp_service_ssl_certificate', ('svc', 'lab-cert'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'ssl', 'certificate', 'lab-cert']),
    ('set_rp_service_tcp_request_inspect_delay', ('svc', '5'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'tcp-request', 'inspect-delay', '5']),
    ('set_rp_service_timeout_client', ('svc', '30'), 'set', ['load-balancing', 'haproxy', 'service', 'svc', 'timeout', 'client', '30']),
    ('set_rp_timeout_check', ('', '5'), 'set', ['load-balancing', 'haproxy', 'timeout', 'check', '5']),
    ('set_rp_timeout_client', ('', '30'), 'set', ['load-balancing', 'haproxy', 'timeout', 'client', '30']),
    ('set_rp_timeout_connect', ('', '5'), 'set', ['load-balancing', 'haproxy', 'timeout', 'connect', '5']),
    ('set_rp_timeout_server', ('', '30'), 'set', ['load-balancing', 'haproxy', 'timeout', 'server', '30']),
    ('set_rp_vrf', ('', 'default'), 'set', ['load-balancing', 'haproxy', 'vrf', 'default']),
    ('set_wan_rule_destination_group_address', ('10', 'LAN'), 'set', ['load-balancing', 'wan', 'rule', '10', 'destination', 'group', 'address-group', 'LAN']),
    ('set_wan_rule_destination_group_domain', ('10', 'DOMS'), 'set', ['load-balancing', 'wan', 'rule', '10', 'destination', 'group', 'domain-group', 'DOMS']),
    ('set_wan_rule_destination_group_network', ('10', 'NETS'), 'set', ['load-balancing', 'wan', 'rule', '10', 'destination', 'group', 'network-group', 'NETS']),
    ('set_wan_rule_destination_group_port', ('10', 'WEB'), 'set', ['load-balancing', 'wan', 'rule', '10', 'destination', 'group', 'port-group', 'WEB']),
    ('set_wan_rule_source_group_address', ('10', 'LAN'), 'set', ['load-balancing', 'wan', 'rule', '10', 'source', 'group', 'address-group', 'LAN']),
    ('set_wan_rule_source_group_domain', ('10', 'DOMS'), 'set', ['load-balancing', 'wan', 'rule', '10', 'source', 'group', 'domain-group', 'DOMS']),
    ('set_wan_rule_source_group_network', ('10', 'NETS'), 'set', ['load-balancing', 'wan', 'rule', '10', 'source', 'group', 'network-group', 'NETS']),
    ('set_wan_rule_source_group_port', ('10', 'WEB'), 'set', ['load-balancing', 'wan', 'rule', '10', 'source', 'group', 'port-group', 'WEB']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V15_CASES)
def test_load_balancing_v1_5_paths(method, args, op, expected_path):
    _run("1.5", method, args, op, expected_path)


REJECT_ON_14 = [
    ('delete_rp_backend_rule_wildcard_domain', ('bk', '10')),
    ('delete_rp_backend_server_check_port', ('bk', 's1')),
    ('delete_rp_service_http_compression', ('svc',)),
    ('delete_rp_service_http_compression_algorithm', ('svc',)),
    ('delete_rp_service_http_compression_mime_type', ('svc', 'text/html')),
    ('delete_rp_service_listen_address_accept_proxy', ('svc', '192.0.2.1')),
    ('delete_rp_service_rule_wildcard_domain', ('svc', '10')),
    ('delete_rp_service_timeout', ('svc',)),
    ('delete_rp_timeout_check', ('',)),
    ('delete_rp_timeout_client', ('',)),
    ('delete_rp_timeout_connect', ('',)),
    ('delete_rp_timeout_server', ('',)),
    ('set_rp_backend_rule_wildcard_domain', ('bk', '10')),
    ('set_rp_backend_server_check_port', ('bk', 's1|8080')),
    ('set_rp_service_http_compression_algorithm', ('svc', 'gzip')),
    ('set_rp_service_http_compression_mime_type', ('svc', 'text/html')),
    ('set_rp_service_listen_address_accept_proxy', ('svc', '192.0.2.1')),
    ('set_rp_service_rule_wildcard_domain', ('svc', '10')),
    ('set_rp_service_timeout_client', ('svc', '30')),
    ('set_rp_timeout_check', ('', '5')),
    ('set_rp_timeout_client', ('', '30')),
    ('set_rp_timeout_connect', ('', '5')),
    ('set_rp_timeout_server', ('', '30')),
    ('set_wan_rule_destination_group_address', ('10', 'LAN')),
    ('set_wan_rule_destination_group_domain', ('10', 'DOMS')),
    ('set_wan_rule_destination_group_network', ('10', 'NETS')),
    ('set_wan_rule_destination_group_port', ('10', 'WEB')),
    ('set_wan_rule_source_group_address', ('10', 'LAN')),
    ('set_wan_rule_source_group_domain', ('10', 'DOMS')),
    ('set_wan_rule_source_group_network', ('10', 'NETS')),
    ('set_wan_rule_source_group_port', ('10', 'WEB')),
]


@pytest.mark.parametrize("method, args", REJECT_ON_14)
def test_load_balancing_version_split_rejected_on_1_4(method, args):
    builder = LoadBalancingBatchBuilder(version="1.4")
    with pytest.raises(ValueError):
        getattr(builder, method)(*args)


def test_rp_timeout_capability_follows_the_mapper():
    caps_14 = LoadBalancingBatchBuilder(version="1.4").get_capabilities()["features"]
    caps_15 = LoadBalancingBatchBuilder(version="1.5").get_capabilities()["features"]
    assert caps_14["rp_timeout"]["supported"] is False
    assert caps_15["rp_timeout"]["supported"] is True


def test_every_load_balancing_emitter_is_tabulated():
    proto = LoadBalancingBatchBuilder(version="1.5")
    methods = {
        name
        for name, meth in inspect.getmembers(proto, predicate=inspect.ismethod)
        if not name.startswith("_")
        and name not in {"get_capabilities", "is_empty", "get_operations", "add_set", "add_delete"}
    }
    covered = {item[0] for item in COMMON_CASES + V14_CASES + V15_CASES + REJECT_ON_14}
    assert methods == covered
