"""Golden (method, args, op, expected_path) cases for FirewallIPv4BatchBuilder.

Paths checked with validateTmplPath on 1.4 (100.64.64.50) and 1.5 (100.64.64.5).
Generated for issue #711; edit the tables directly if the mapper changes.
"""

import pytest

from vyos_builders.firewall.ipv4 import FirewallIPv4BatchBuilder


COMMON_CASES = [
    ('delete_base_chain_default_action', ('forward',), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'default-action']),
    ('delete_base_chain_default_log', ('forward',), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'default-log']),
    ('delete_base_chain_description', ('forward',), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'description']),
    ('delete_base_chain_rule', ('forward', 10), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10']),
    ('delete_custom_chain', ('MYCHAIN',), 'delete', ['firewall', 'ipv4', 'name', 'MYCHAIN']),
    ('delete_custom_chain_default_action', ('MYCHAIN',), 'delete', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'default-action']),
    ('delete_custom_chain_default_jump_target', ('MYCHAIN',), 'delete', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'default-jump-target']),
    ('delete_custom_chain_default_log', ('MYCHAIN',), 'delete', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'default-log']),
    ('delete_custom_chain_description', ('MYCHAIN',), 'delete', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'description']),
    ('delete_custom_chain_rule', ('MYCHAIN', 10), 'delete', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'rule', '10']),
    ('delete_rule_action', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'action']),
    ('delete_rule_add_address_to_group', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group']),
    ('delete_rule_add_address_to_group_dst', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'destination-address']),
    ('delete_rule_add_address_to_group_dst_group', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'destination-address', 'address-group']),
    ('delete_rule_add_address_to_group_dst_timeout', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'destination-address', 'timeout']),
    ('delete_rule_add_address_to_group_src', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'source-address']),
    ('delete_rule_add_address_to_group_src_group', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'source-address', 'address-group']),
    ('delete_rule_add_address_to_group_src_timeout', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'source-address', 'timeout']),
    ('delete_rule_connection_mark', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'connection-mark']),
    ('delete_rule_connection_status_nat', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'connection-status', 'nat']),
    ('delete_rule_conntrack_helper', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'conntrack-helper']),
    ('delete_rule_description', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'description']),
    ('delete_rule_destination', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination']),
    ('delete_rule_destination_address', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'address']),
    ('delete_rule_destination_address_mask', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'address-mask']),
    ('delete_rule_destination_fqdn', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'fqdn']),
    ('delete_rule_destination_geoip', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'geoip']),
    ('delete_rule_destination_geoip_country', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'geoip', 'country-code']),
    ('delete_rule_destination_geoip_inverse', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'geoip', 'inverse-match']),
    ('delete_rule_destination_group', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group']),
    ('delete_rule_destination_group_address', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'address-group']),
    ('delete_rule_destination_group_domain', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'domain-group']),
    ('delete_rule_destination_group_dynamic_address', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'dynamic-address-group']),
    ('delete_rule_destination_group_mac', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'mac-group']),
    ('delete_rule_destination_group_network', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'network-group']),
    ('delete_rule_destination_group_port', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'port-group']),
    ('delete_rule_destination_mac_address', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'mac-address']),
    ('delete_rule_destination_port', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'port']),
    ('delete_rule_disable', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'disable']),
    ('delete_rule_dscp', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'dscp']),
    ('delete_rule_dscp_exclude', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'dscp-exclude']),
    ('delete_rule_fragment', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'fragment']),
    ('delete_rule_fragment_match_frag', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'fragment', 'match-frag']),
    ('delete_rule_fragment_match_non_frag', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'fragment', 'match-non-frag']),
    ('delete_rule_hop_limit', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl']),
    ('delete_rule_hop_limit_eq', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'eq']),
    ('delete_rule_hop_limit_gt', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'gt']),
    ('delete_rule_hop_limit_lt', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'lt']),
    ('delete_rule_icmp_code', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'code']),
    ('delete_rule_icmp_type', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'type']),
    ('delete_rule_icmp_type_name', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'type-name']),
    ('delete_rule_icmpv6_code', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'code']),
    ('delete_rule_icmpv6_type', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'type']),
    ('delete_rule_icmpv6_type_name', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'type-name']),
    ('delete_rule_inbound_interface', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'inbound-interface']),
    ('delete_rule_inbound_interface_group', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'inbound-interface', 'group']),
    ('delete_rule_ipsec', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec']),
    ('delete_rule_jump_target', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'jump-target']),
    ('delete_rule_limit', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'limit']),
    ('delete_rule_limit_burst', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'limit', 'burst']),
    ('delete_rule_limit_rate', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'limit', 'rate']),
    ('delete_rule_log', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log']),
    ('delete_rule_log_options', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log-options']),
    ('delete_rule_log_options_group', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log-options', 'group']),
    ('delete_rule_log_options_level', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log-options', 'level']),
    ('delete_rule_log_options_queue_threshold', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log-options', 'queue-threshold']),
    ('delete_rule_log_options_snapshot_length', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log-options', 'snapshot-length']),
    ('delete_rule_mark', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'mark']),
    ('delete_rule_offload_target', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'offload-target']),
    ('delete_rule_outbound_interface', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'outbound-interface']),
    ('delete_rule_outbound_interface_group', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'outbound-interface', 'group']),
    ('delete_rule_packet_length', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'packet-length']),
    ('delete_rule_packet_length_exclude', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'packet-length-exclude']),
    ('delete_rule_packet_type', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'packet-type']),
    ('delete_rule_protocol', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'protocol']),
    ('delete_rule_queue', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'queue']),
    ('delete_rule_queue_options', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'queue-options']),
    ('delete_rule_recent', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'recent']),
    ('delete_rule_recent_count', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'recent', 'count']),
    ('delete_rule_recent_time', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'recent', 'time']),
    ('delete_rule_source', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source']),
    ('delete_rule_source_address', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'address']),
    ('delete_rule_source_address_mask', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'address-mask']),
    ('delete_rule_source_fqdn', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'fqdn']),
    ('delete_rule_source_geoip', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'geoip']),
    ('delete_rule_source_geoip_country', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'geoip', 'country-code']),
    ('delete_rule_source_geoip_inverse', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'geoip', 'inverse-match']),
    ('delete_rule_source_group', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group']),
    ('delete_rule_source_group_address', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'address-group']),
    ('delete_rule_source_group_domain', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'domain-group']),
    ('delete_rule_source_group_dynamic_address', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'dynamic-address-group']),
    ('delete_rule_source_group_mac', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'mac-group']),
    ('delete_rule_source_group_network', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'network-group']),
    ('delete_rule_source_group_port', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'port-group']),
    ('delete_rule_source_mac', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'mac-address']),
    ('delete_rule_source_mac_address', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'mac-address']),
    ('delete_rule_source_port', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'port']),
    ('delete_rule_state_established', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'state', 'established']),
    ('delete_rule_state_invalid', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'state', 'invalid']),
    ('delete_rule_state_new', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'state', 'new']),
    ('delete_rule_state_related', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'state', 'related']),
    ('delete_rule_synproxy', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'synproxy']),
    ('delete_rule_synproxy_tcp_mss', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'synproxy', 'tcp', 'mss']),
    ('delete_rule_synproxy_tcp_window_scale', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'synproxy', 'tcp', 'window-scale']),
    ('delete_rule_tcp_flags', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'tcp', 'flags']),
    ('delete_rule_tcp_mss', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'tcp', 'mss']),
    ('delete_rule_time', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time']),
    ('delete_rule_time_startdate', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'startdate']),
    ('delete_rule_time_starttime', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'starttime']),
    ('delete_rule_time_stopdate', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'stopdate']),
    ('delete_rule_time_stoptime', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'stoptime']),
    ('delete_rule_time_weekdays', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'weekdays']),
    ('delete_rule_ttl', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl']),
    ('delete_rule_ttl_eq', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'eq']),
    ('delete_rule_ttl_gt', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'gt']),
    ('delete_rule_ttl_lt', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'lt']),
    ('set_base_chain_default_action', ('forward', 'accept'), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'default-action', 'accept']),
    ('set_base_chain_default_log', ('forward',), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'default-log']),
    ('set_base_chain_description', ('forward', 'd'), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'description', 'd']),
    ('set_base_chain_rule', ('forward', 10), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10']),
    ('set_custom_chain', ('MYCHAIN',), 'set', ['firewall', 'ipv4', 'name', 'MYCHAIN']),
    ('set_custom_chain_default_action', ('MYCHAIN', 'accept'), 'set', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'default-action', 'accept']),
    ('set_custom_chain_default_jump_target', ('MYCHAIN', '203.0.113.5'), 'set', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'default-jump-target', '203.0.113.5']),
    ('set_custom_chain_default_log', ('MYCHAIN',), 'set', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'default-log']),
    ('set_custom_chain_description', ('MYCHAIN', 'd'), 'set', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'description', 'd']),
    ('set_custom_chain_rule', ('MYCHAIN', 10), 'set', ['firewall', 'ipv4', 'name', 'MYCHAIN', 'rule', '10']),
    ('set_rule_action', ('forward', 10, 'accept', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'action', 'accept']),
    ('set_rule_add_address_to_group_dst_group', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'destination-address', 'address-group', 'G1']),
    ('set_rule_add_address_to_group_dst_timeout', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'destination-address', 'timeout', '5']),
    ('set_rule_add_address_to_group_src_group', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'source-address', 'address-group', 'G1']),
    ('set_rule_add_address_to_group_src_timeout', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'add-address-to-group', 'source-address', 'timeout', '5']),
    ('set_rule_connection_mark', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'connection-mark', '5']),
    ('set_rule_connection_status_nat', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'connection-status', 'nat', '5']),
    ('set_rule_conntrack_helper', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'conntrack-helper', '5']),
    ('set_rule_description', ('forward', 10, 'd', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'description', 'd']),
    ('set_rule_destination_address', ('forward', 10, '203.0.113.10', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'address', '203.0.113.10']),
    ('set_rule_destination_address_mask', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'address-mask', '5']),
    ('set_rule_destination_fqdn', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'fqdn', '5']),
    ('set_rule_destination_geoip_country', ('forward', 10, 'US', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'geoip', 'country-code', 'US']),
    ('set_rule_destination_geoip_inverse', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'geoip', 'inverse-match']),
    ('set_rule_destination_group_address', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'address-group', 'G1']),
    ('set_rule_destination_group_domain', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'domain-group', 'G1']),
    ('set_rule_destination_group_dynamic_address', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'dynamic-address-group', 'G1']),
    ('set_rule_destination_group_mac', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'mac-group', 'G1']),
    ('set_rule_destination_group_network', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'network-group', 'G1']),
    ('set_rule_destination_group_port', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'port-group', 'G1']),
    ('set_rule_destination_mac_address', ('forward', 10, '00:11:22:33:44:55', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'mac-address', '00:11:22:33:44:55']),
    ('set_rule_destination_port', ('forward', 10, '443', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'port', '443']),
    ('set_rule_disable', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'disable']),
    ('set_rule_dscp', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'dscp', '5']),
    ('set_rule_dscp_exclude', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'dscp-exclude', '5']),
    ('set_rule_fragment_match_frag', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'fragment', 'match-frag']),
    ('set_rule_fragment_match_non_frag', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'fragment', 'match-non-frag']),
    ('set_rule_hop_limit_eq', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'eq', '5']),
    ('set_rule_hop_limit_gt', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'gt', '5']),
    ('set_rule_hop_limit_lt', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'lt', '5']),
    ('set_rule_icmp_code', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'code', '5']),
    ('set_rule_icmp_type', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'type', '5']),
    ('set_rule_icmp_type_name', ('forward', 10, '8', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'type-name', '8']),
    ('set_rule_icmpv6_code', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'code', '5']),
    ('set_rule_icmpv6_type', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'type', '5']),
    ('set_rule_icmpv6_type_name', ('forward', 10, 'X', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'icmp', 'type-name', 'X']),
    ('set_rule_inbound_interface', ('forward', 10, 'eth1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'inbound-interface', 'name', 'eth1']),
    ('set_rule_inbound_interface_group', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'inbound-interface', 'group', 'G1']),
    ('set_rule_jump_target', ('forward', 10, '203.0.113.5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'jump-target', '203.0.113.5']),
    ('set_rule_limit_burst', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'limit', 'burst', '5']),
    ('set_rule_limit_rate', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'limit', 'rate', '5']),
    ('set_rule_log', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log']),
    ('set_rule_log_options_group', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log-options', 'group', '5']),
    ('set_rule_log_options_level', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log-options', 'level', '5']),
    ('set_rule_log_options_queue_threshold', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log-options', 'queue-threshold', '5']),
    ('set_rule_log_options_snapshot_length', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'log-options', 'snapshot-length', '5']),
    ('set_rule_mark', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'mark', '5']),
    ('set_rule_offload_target', ('forward', 10, '203.0.113.5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'offload-target', '203.0.113.5']),
    ('set_rule_outbound_interface', ('forward', 10, 'eth1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'outbound-interface', 'name', 'eth1']),
    ('set_rule_outbound_interface_group', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'outbound-interface', 'group', 'G1']),
    ('set_rule_packet_length', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'packet-length', '5']),
    ('set_rule_packet_length_exclude', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'packet-length-exclude', '5']),
    ('set_rule_packet_type', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'packet-type', '5']),
    ('set_rule_protocol', ('forward', 10, 'tcp', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'protocol', 'tcp']),
    ('set_rule_queue', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'queue', '5']),
    ('set_rule_queue_options', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'queue-options', '5']),
    ('set_rule_recent_count', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'recent', 'count', '5']),
    ('set_rule_recent_time', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'recent', 'time', '5']),
    ('set_rule_source_address', ('forward', 10, '203.0.113.10', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'address', '203.0.113.10']),
    ('set_rule_source_address_mask', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'address-mask', '5']),
    ('set_rule_source_fqdn', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'fqdn', '5']),
    ('set_rule_source_geoip_country', ('forward', 10, 'US', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'geoip', 'country-code', 'US']),
    ('set_rule_source_geoip_inverse', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'geoip', 'inverse-match']),
    ('set_rule_source_group_address', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'address-group', 'G1']),
    ('set_rule_source_group_domain', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'domain-group', 'G1']),
    ('set_rule_source_group_dynamic_address', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'dynamic-address-group', 'G1']),
    ('set_rule_source_group_mac', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'mac-group', 'G1']),
    ('set_rule_source_group_network', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'network-group', 'G1']),
    ('set_rule_source_group_port', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'port-group', 'G1']),
    ('set_rule_source_mac', ('forward', 10, '00:11:22:33:44:55', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'mac-address', '00:11:22:33:44:55']),
    ('set_rule_source_mac_address', ('forward', 10, '00:11:22:33:44:55', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'mac-address', '00:11:22:33:44:55']),
    ('set_rule_source_port', ('forward', 10, '443', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'port', '443']),
    ('set_rule_state_established', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'state', 'established']),
    ('set_rule_state_invalid', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'state', 'invalid']),
    ('set_rule_state_new', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'state', 'new']),
    ('set_rule_state_related', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'state', 'related']),
    ('set_rule_synproxy_tcp_mss', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'synproxy', 'tcp', 'mss', '5']),
    ('set_rule_synproxy_tcp_window_scale', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'synproxy', 'tcp', 'window-scale', '5']),
    ('set_rule_tcp_flags', ('forward', 10, 'syn', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'tcp', 'flags', 'syn']),
    ('set_rule_tcp_mss', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'tcp', 'mss', '5']),
    ('set_rule_time_startdate', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'startdate', '5']),
    ('set_rule_time_starttime', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'starttime', '5']),
    ('set_rule_time_stopdate', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'stopdate', '5']),
    ('set_rule_time_stoptime', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'stoptime', '5']),
    ('set_rule_time_weekdays', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'time', 'weekdays', '5']),
    ('set_rule_ttl_eq', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'eq', '5']),
    ('set_rule_ttl_gt', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'gt', '5']),
    ('set_rule_ttl_lt', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ttl', 'lt', '5']),
]

V15_ONLY_CASES = [
    ('delete_prerouting_raw_default_action', (), 'delete', ['firewall', 'ipv4', 'prerouting', 'raw', 'default-action']),
    ('delete_prerouting_raw_default_jump_target', (), 'delete', ['firewall', 'ipv4', 'prerouting', 'raw', 'default-jump-target']),
    ('delete_prerouting_raw_description', (), 'delete', ['firewall', 'ipv4', 'prerouting', 'raw', 'description']),
    ('delete_prerouting_raw_rule', (10,), 'delete', ['firewall', 'ipv4', 'prerouting', 'raw', 'rule', '10']),
    ('delete_rule_destination_group_remote', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'remote-group']),
    ('delete_rule_gre', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre']),
    ('delete_rule_gre_flags_checksum', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'checksum']),
    ('delete_rule_gre_flags_checksum_unset', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'checksum', 'unset']),
    ('delete_rule_gre_flags_key', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'key']),
    ('delete_rule_gre_flags_key_unset', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'key', 'unset']),
    ('delete_rule_gre_flags_sequence', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'sequence']),
    ('delete_rule_gre_flags_sequence_unset', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'sequence', 'unset']),
    ('delete_rule_gre_inner_proto', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'inner-proto']),
    ('delete_rule_gre_key', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'key']),
    ('delete_rule_gre_version', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'version']),
    ('delete_rule_ipsec_match_ipsec_in', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-ipsec-in']),
    ('delete_rule_ipsec_match_ipsec_out', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-ipsec-out']),
    ('delete_rule_ipsec_match_none_in', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-none-in']),
    ('delete_rule_ipsec_match_none_out', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-none-out']),
    ('delete_rule_set', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set']),
    ('delete_rule_set_connection_mark', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'connection-mark']),
    ('delete_rule_set_dscp', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'dscp']),
    ('delete_rule_set_hop_limit', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'ttl']),
    ('delete_rule_set_mark', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'mark']),
    ('delete_rule_set_tcp_mss', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'tcp-mss']),
    ('delete_rule_set_ttl', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'ttl']),
    ('delete_rule_source_group_remote', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'remote-group']),
    ('set_prerouting_raw_default_action', ('accept',), 'set', ['firewall', 'ipv4', 'prerouting', 'raw', 'default-action', 'accept']),
    ('set_prerouting_raw_default_jump_target', ('203.0.113.5',), 'set', ['firewall', 'ipv4', 'prerouting', 'raw', 'default-jump-target', '203.0.113.5']),
    ('set_prerouting_raw_description', ('d',), 'set', ['firewall', 'ipv4', 'prerouting', 'raw', 'description', 'd']),
    ('set_prerouting_raw_rule', (10,), 'set', ['firewall', 'ipv4', 'prerouting', 'raw', 'rule', '10']),
    ('set_rule_destination_group_remote', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'destination', 'group', 'remote-group', 'G1']),
    ('set_rule_gre_flags_checksum', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'checksum']),
    ('set_rule_gre_flags_checksum_unset', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'checksum', 'unset']),
    ('set_rule_gre_flags_key', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'key']),
    ('set_rule_gre_flags_key_unset', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'key', 'unset']),
    ('set_rule_gre_flags_sequence', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'sequence']),
    ('set_rule_gre_flags_sequence_unset', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'flags', 'sequence', 'unset']),
    ('set_rule_gre_inner_proto', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'inner-proto', '5']),
    ('set_rule_gre_key', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'key', '5']),
    ('set_rule_gre_version', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'gre', 'version', '5']),
    ('set_rule_ipsec_match_ipsec_in', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-ipsec-in']),
    ('set_rule_ipsec_match_ipsec_out', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-ipsec-out']),
    ('set_rule_ipsec_match_none_in', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-none-in']),
    ('set_rule_ipsec_match_none_out', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-none-out']),
    ('set_rule_set_connection_mark', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'connection-mark', '5']),
    ('set_rule_set_dscp', ('forward', 10, '10', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'dscp', '10']),
    ('set_rule_set_hop_limit', ('forward', 10, '10', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'ttl', '10']),
    ('set_rule_set_mark', ('forward', 10, '0x10', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'mark', '0x10']),
    ('set_rule_set_tcp_mss', ('forward', 10, '5', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'tcp-mss', '5']),
    ('set_rule_set_ttl', ('forward', 10, '64', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'set', 'ttl', '64']),
    ('set_rule_source_group_remote', ('forward', 10, 'G1', False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'source', 'group', 'remote-group', 'G1']),
]

V14_ONLY_CASES = [
    ('delete_rule_ipsec_match_ipsec', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-ipsec']),
    ('delete_rule_ipsec_match_none', ('forward', 10, False), 'delete', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-none']),
    ('set_rule_ipsec_match_ipsec', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-ipsec']),
    ('set_rule_ipsec_match_none', ('forward', 10, False), 'set', ['firewall', 'ipv4', 'forward', 'filter', 'rule', '10', 'ipsec', 'match-none']),
]


def _run(version, method, args, op, expected_path):
    builder = FirewallIPv4BatchBuilder(version=version)
    getattr(builder, method)(*args)
    operations = builder.get_operations()
    assert [(item["op"], item["path"]) for item in operations] == [(op, expected_path)]


@pytest.mark.parametrize("method, args, op, expected_path", COMMON_CASES)
@pytest.mark.parametrize("version", ["1.4", "1.5"])
def test_ipv4_common_paths(method, args, op, expected_path, version):
    _run(version, method, args, op, expected_path)


@pytest.mark.parametrize("method, args, op, expected_path", V15_ONLY_CASES)
def test_ipv4_v1_5_only_paths(method, args, op, expected_path):
    _run("1.5", method, args, op, expected_path)


@pytest.mark.parametrize("method, args, op, expected_path", V14_ONLY_CASES)
def test_ipv4_v1_4_only_paths(method, args, op, expected_path):
    _run("1.4", method, args, op, expected_path)
