"""Golden (method, args, op, expected_path) cases for EthernetInterfaceBuilderMixin.

Paths checked with validateTmplPath on 1.4 (100.64.64.50) and 1.5 (100.64.64.5).
Generated for issue #721; edit the tables directly if the mapper changes.
"""

import pytest

from vyos_builders.interfaces.ethernet import EthernetInterfaceBuilderMixin


def _run(version, method, args, op, expected_path):
    builder = EthernetInterfaceBuilderMixin(version=version)
    getattr(builder, method)(*args)
    operations = builder.get_operations()
    assert [(item["op"], item["path"]) for item in operations] == [(op, expected_path)]

COMMON_CASES = [
    ('delete_dhcp_options', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'dhcp-options']),
    ('delete_dhcpv6_options', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options']),
    ('delete_disable_flow_control', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'disable-flow-control']),
    ('delete_disable_link_detect', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'disable-link-detect']),
    ('delete_eapol', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'eapol']),
    ('delete_evpn', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'evpn']),
    ('delete_interface', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0']),
    ('delete_interface_address', ('eth0', '192.0.2.1'), 'delete', ['interfaces', 'ethernet', 'eth0', 'address', '192.0.2.1']),
    ('delete_interface_description', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'description']),
    ('delete_interface_disable', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'disable']),
    ('delete_interface_duplex', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'duplex']),
    ('delete_interface_mac', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'mac']),
    ('delete_interface_mtu', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'mtu']),
    ('delete_interface_speed', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'speed']),
    ('delete_interface_vrf', ('eth0', 'red'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vrf', 'red']),
    ('delete_ip_disable_forwarding', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'ip', 'disable-forwarding']),
    ('delete_ip_source_validation', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'ip', 'source-validation']),
    ('delete_ipv6_address_no_default_link_local', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'address', 'no-default-link-local']),
    ('delete_ipv6_source_validation', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'source-validation']),
    ('delete_mirror', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'mirror']),
    ('delete_offload_gro', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'offload', 'gro']),
    ('delete_offload_gso', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'offload', 'gso']),
    ('delete_offload_hw_tc_offload', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'offload', 'hw-tc-offload']),
    ('delete_offload_lro', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'offload', 'lro']),
    ('delete_offload_rfs', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'offload', 'rfs']),
    ('delete_offload_rps', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'offload', 'rps']),
    ('delete_offload_sg', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'offload', 'sg']),
    ('delete_offload_tso', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'offload', 'tso']),
    ('delete_redirect', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'redirect']),
    ('delete_ring_buffer', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'ring-buffer']),
    ('delete_vif', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10']),
    ('delete_vif_address', ('eth0', '10', '192.0.2.1'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'address', '192.0.2.1']),
    ('delete_vif_c', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10']),
    ('delete_vif_c_address', ('eth0', '10', '10', '192.0.2.1'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'address', '192.0.2.1']),
    ('delete_vif_c_description', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'description']),
    ('delete_vif_c_dhcp_options', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options']),
    ('delete_vif_c_dhcpv6_options', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options']),
    ('delete_vif_c_disable', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'disable']),
    ('delete_vif_c_disable_link_detect', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'disable-link-detect']),
    ('delete_vif_c_ip', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip']),
    ('delete_vif_c_mac', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'mac']),
    ('delete_vif_c_mirror', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'mirror']),
    ('delete_vif_c_mtu', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'mtu']),
    ('delete_vif_c_redirect', ('eth0', '10', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'redirect']),
    ('delete_vif_c_vrf', ('eth0', '10', '10', 'red'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'vrf', 'red']),
    ('delete_vif_description', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'description']),
    ('delete_vif_dhcp_options', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcp-options']),
    ('delete_vif_dhcpv6_options', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options']),
    ('delete_vif_disable', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'disable']),
    ('delete_vif_disable_link_detect', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'disable-link-detect']),
    ('delete_vif_egress_qos', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'egress-qos']),
    ('delete_vif_ingress_qos', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ingress-qos']),
    ('delete_vif_ip', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip']),
    ('delete_vif_ip_adjust_mss', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'adjust-mss']),
    ('delete_vif_ip_adjust_mss_clamp_mss_to_pmtu', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'adjust-mss']),
    ('delete_vif_ipv6_adjust_mss', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'adjust-mss']),
    ('delete_vif_ipv6_adjust_mss_clamp_mss_to_pmtu', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'adjust-mss']),
    ('delete_vif_mac', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'mac']),
    ('delete_vif_mirror', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'mirror']),
    ('delete_vif_mtu', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'mtu']),
    ('delete_vif_redirect', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'redirect']),
    ('delete_vif_s', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10']),
    ('delete_vif_s_address', ('eth0', '10', '192.0.2.1'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'address', '192.0.2.1']),
    ('delete_vif_s_description', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'description']),
    ('delete_vif_s_dhcp_options', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcp-options']),
    ('delete_vif_s_dhcpv6_options', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options']),
    ('delete_vif_s_disable', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'disable']),
    ('delete_vif_s_disable_link_detect', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'disable-link-detect']),
    ('delete_vif_s_ip', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip']),
    ('delete_vif_s_mac', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'mac']),
    ('delete_vif_s_mirror', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'mirror']),
    ('delete_vif_s_mtu', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'mtu']),
    ('delete_vif_s_protocol', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'protocol']),
    ('delete_vif_s_redirect', ('eth0', '10'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'redirect']),
    ('delete_vif_s_vrf', ('eth0', '10', 'red'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vrf', 'red']),
    ('delete_vif_vrf', ('eth0', '10', 'red'), 'delete', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'vrf', 'red']),
    ('set_dhcp_options_client_id', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcp-options', 'client-id', '5']),
    ('set_dhcp_options_default_route_distance', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcp-options', 'default-route-distance', '5']),
    ('set_dhcp_options_host_name', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcp-options', 'host-name', '5']),
    ('set_dhcp_options_mtu', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcp-options', 'mtu']),
    ('set_dhcp_options_no_default_route', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcp-options', 'no-default-route']),
    ('set_dhcp_options_reject', ('eth0', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcp-options', 'reject', '192.0.2.1']),
    ('set_dhcp_options_user_class', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcp-options', 'user-class', '5']),
    ('set_dhcp_options_vendor_class_id', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcp-options', 'vendor-class-id', '5']),
    ('set_dhcpv6_options_duid', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'duid', '5']),
    ('set_dhcpv6_options_no_release', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'no-release']),
    ('set_dhcpv6_options_parameters_only', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'parameters-only']),
    ('set_dhcpv6_options_pd', ('eth0', '5', '2001:db8::/32'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'pd', '5']),
    ('set_dhcpv6_options_pd_interface', ('eth0', '5', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'pd', '5', 'interface', '5']),
    ('set_dhcpv6_options_pd_interface_address', ('eth0', '5', '5', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'address', '192.0.2.1']),
    ('set_dhcpv6_options_pd_interface_sla_id', ('eth0', '5', '5', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'sla-id', '5']),
    ('set_dhcpv6_options_pd_length', ('eth0', '5', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'pd', '5', 'length', '5']),
    ('set_dhcpv6_options_rapid_commit', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'rapid-commit']),
    ('set_dhcpv6_options_temporary', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'dhcpv6-options', 'temporary']),
    ('set_disable_flow_control', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'disable-flow-control']),
    ('set_disable_link_detect', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'disable-link-detect']),
    ('set_eapol_passphrase', ('eth0', 'secret'), 'set', ['interfaces', 'ethernet', 'eth0', 'eapol', 'passphrase', 'secret']),
    ('set_evpn_uplink', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'evpn', 'uplink']),
    ('set_interface_address', ('eth0', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'address', '192.0.2.1']),
    ('set_interface_description', ('eth0', 'lab'), 'set', ['interfaces', 'ethernet', 'eth0', 'description', 'lab']),
    ('set_interface_disable', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'disable']),
    ('set_interface_duplex', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'duplex', '5']),
    ('set_interface_mac', ('eth0', '00:11:22:33:44:55'), 'set', ['interfaces', 'ethernet', 'eth0', 'mac', '00:11:22:33:44:55']),
    ('set_interface_mtu', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'mtu', '5']),
    ('set_interface_speed', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'speed', '5']),
    ('set_interface_vrf', ('eth0', 'red'), 'set', ['interfaces', 'ethernet', 'eth0', 'vrf', 'red']),
    ('set_ip_adjust_mss', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'adjust-mss', '5']),
    ('set_ip_adjust_mss_clamp_to_pmtu', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'adjust-mss', 'clamp-mss-to-pmtu']),
    ('set_ip_arp_cache_timeout', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'arp-cache-timeout', '5']),
    ('set_ip_disable_arp_filter', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'disable-arp-filter']),
    ('set_ip_disable_forwarding', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'disable-forwarding']),
    ('set_ip_enable_arp_accept', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'enable-arp-accept']),
    ('set_ip_enable_arp_announce', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'enable-arp-announce']),
    ('set_ip_enable_arp_ignore', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'enable-arp-ignore']),
    ('set_ip_enable_proxy_arp', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'enable-proxy-arp']),
    ('set_ip_proxy_arp_pvlan', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'proxy-arp-pvlan']),
    ('set_ip_source_validation', ('eth0', 'nat'), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'source-validation', 'nat']),
    ('set_ipv6_accept_dad', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'accept-dad', '5']),
    ('set_ipv6_address_autoconf', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'address', 'autoconf']),
    ('set_ipv6_address_eui64', ('eth0', '2001:db8::/32'), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'address', 'eui64', '2001:db8::/32']),
    ('set_ipv6_address_no_default_link_local', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'address', 'no-default-link-local']),
    ('set_ipv6_adjust_mss', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'adjust-mss', '5']),
    ('set_ipv6_adjust_mss_clamp_to_pmtu', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'adjust-mss', 'clamp-mss-to-pmtu']),
    ('set_ipv6_base_reachable_time', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'base-reachable-time', '5']),
    ('set_ipv6_disable_forwarding', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'disable-forwarding']),
    ('set_ipv6_dup_addr_detect_transmits', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_ipv6_source_validation', ('eth0', 'nat'), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'source-validation', 'nat']),
    ('set_mirror_egress', ('eth0', 'eth0'), 'set', ['interfaces', 'ethernet', 'eth0', 'mirror', 'egress', 'eth0']),
    ('set_mirror_ingress', ('eth0', 'eth0'), 'set', ['interfaces', 'ethernet', 'eth0', 'mirror', 'ingress', 'eth0']),
    ('set_offload_gro', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'offload', 'gro']),
    ('set_offload_gso', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'offload', 'gso']),
    ('set_offload_hw_tc_offload', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'offload', 'hw-tc-offload']),
    ('set_offload_lro', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'offload', 'lro']),
    ('set_offload_rfs', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'offload', 'rfs']),
    ('set_offload_rps', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'offload', 'rps']),
    ('set_offload_sg', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'offload', 'sg']),
    ('set_offload_tso', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'offload', 'tso']),
    ('set_redirect', ('eth0', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'redirect', 'eth1']),
    ('set_ring_buffer_rx', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'ring-buffer', 'rx', '5']),
    ('set_ring_buffer_tx', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'ring-buffer', 'tx', '5']),
    ('set_vif', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10']),
    ('set_vif_address', ('eth0', '10', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'address', '192.0.2.1']),
    ('set_vif_c', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10']),
    ('set_vif_c_address', ('eth0', '10', '10', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'address', '192.0.2.1']),
    ('set_vif_c_description', ('eth0', '10', '10', 'lab'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'description', 'lab']),
    ('set_vif_c_dhcp_options_client_id', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'client-id', '5']),
    ('set_vif_c_dhcp_options_default_route_distance', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'default-route-distance', '5']),
    ('set_vif_c_dhcp_options_host_name', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'host-name', '5']),
    ('set_vif_c_dhcp_options_mtu', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'mtu']),
    ('set_vif_c_dhcp_options_no_default_route', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'no-default-route']),
    ('set_vif_c_dhcp_options_reject', ('eth0', '10', '10', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'reject', '192.0.2.1']),
    ('set_vif_c_dhcp_options_user_class', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'user-class', '5']),
    ('set_vif_c_dhcp_options_vendor_class_id', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'vendor-class-id', '5']),
    ('set_vif_c_dhcpv6_options_duid', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'duid', '5']),
    ('set_vif_c_dhcpv6_options_no_release', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'no-release']),
    ('set_vif_c_dhcpv6_options_parameters_only', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'parameters-only']),
    ('set_vif_c_dhcpv6_options_pd', ('eth0', '10', '10', '5', '2001:db8::/32'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5']),
    ('set_vif_c_dhcpv6_options_pd_interface', ('eth0', '10', '10', '5', 'eth0'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5', 'interface', 'eth0']),
    ('set_vif_c_dhcpv6_options_pd_interface_address', ('eth0', '10', '10', '5', 'eth0', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5', 'interface', 'eth0', 'address', '192.0.2.1']),
    ('set_vif_c_dhcpv6_options_pd_interface_sla_id', ('eth0', '10', '10', '5', 'eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5', 'interface', 'eth0', 'sla-id', '5']),
    ('set_vif_c_dhcpv6_options_pd_length', ('eth0', '10', '10', '5', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5', 'length', '5']),
    ('set_vif_c_dhcpv6_options_rapid_commit', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'rapid-commit']),
    ('set_vif_c_dhcpv6_options_temporary', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'temporary']),
    ('set_vif_c_disable', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'disable']),
    ('set_vif_c_disable_link_detect', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'disable-link-detect']),
    ('set_vif_c_ip_adjust_mss', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'adjust-mss', '5']),
    ('set_vif_c_ip_arp_cache_timeout', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'arp-cache-timeout', '5']),
    ('set_vif_c_ip_disable_arp_filter', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'disable-arp-filter']),
    ('set_vif_c_ip_disable_forwarding', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'disable-forwarding']),
    ('set_vif_c_ip_enable_arp_accept', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-arp-accept']),
    ('set_vif_c_ip_enable_arp_announce', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-arp-announce']),
    ('set_vif_c_ip_enable_arp_ignore', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-arp-ignore']),
    ('set_vif_c_ip_enable_directed_broadcast', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-directed-broadcast']),
    ('set_vif_c_ip_enable_proxy_arp', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-proxy-arp']),
    ('set_vif_c_ip_proxy_arp_pvlan', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'proxy-arp-pvlan']),
    ('set_vif_c_ip_source_validation', ('eth0', '10', '10', 'nat'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ip', 'source-validation', 'nat']),
    ('set_vif_c_ipv6_accept_dad', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'accept-dad', '5']),
    ('set_vif_c_ipv6_address_autoconf', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'autoconf']),
    ('set_vif_c_ipv6_address_eui64', ('eth0', '10', '10', '2001:db8::/32'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'eui64', '2001:db8::/32']),
    ('set_vif_c_ipv6_address_no_default_link_local', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'no-default-link-local']),
    ('set_vif_c_ipv6_adjust_mss', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'adjust-mss', '5']),
    ('set_vif_c_ipv6_base_reachable_time', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'base-reachable-time', '5']),
    ('set_vif_c_ipv6_disable_forwarding', ('eth0', '10', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'disable-forwarding']),
    ('set_vif_c_ipv6_dup_addr_detect_transmits', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_vif_c_ipv6_source_validation', ('eth0', '10', '10', 'nat'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'source-validation', 'nat']),
    ('set_vif_c_mac', ('eth0', '10', '10', '00:11:22:33:44:55'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'mac', '00:11:22:33:44:55']),
    ('set_vif_c_mirror_egress', ('eth0', '10', '10', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'egress', 'eth1']),
    ('set_vif_c_mirror_ingress', ('eth0', '10', '10', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'ingress', 'eth1']),
    ('set_vif_c_mtu', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'mtu', '5']),
    ('set_vif_c_redirect', ('eth0', '10', '10', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'redirect', 'eth1']),
    ('set_vif_c_vrf', ('eth0', '10', '10', 'red'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'vrf', 'red']),
    ('set_vif_description', ('eth0', '10', 'lab'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'description', 'lab']),
    ('set_vif_dhcp_options_client_id', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcp-options', 'client-id', '5']),
    ('set_vif_dhcp_options_default_route_distance', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcp-options', 'default-route-distance', '5']),
    ('set_vif_dhcp_options_host_name', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcp-options', 'host-name', '5']),
    ('set_vif_dhcp_options_mtu', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcp-options', 'mtu']),
    ('set_vif_dhcp_options_no_default_route', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcp-options', 'no-default-route']),
    ('set_vif_dhcp_options_reject', ('eth0', '10', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcp-options', 'reject', '192.0.2.1']),
    ('set_vif_dhcp_options_user_class', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcp-options', 'user-class', '5']),
    ('set_vif_dhcp_options_vendor_class_id', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcp-options', 'vendor-class-id', '5']),
    ('set_vif_dhcpv6_options_duid', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'duid', '5']),
    ('set_vif_dhcpv6_options_no_release', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'no-release']),
    ('set_vif_dhcpv6_options_parameters_only', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'parameters-only']),
    ('set_vif_dhcpv6_options_pd', ('eth0', '10', '5', '2001:db8::/32'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'pd', '5']),
    ('set_vif_dhcpv6_options_pd_interface', ('eth0', '10', '5', 'eth0'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'pd', '5', 'interface', 'eth0']),
    ('set_vif_dhcpv6_options_pd_interface_address', ('eth0', '10', '5', 'eth0', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'pd', '5', 'interface', 'eth0', 'address', '192.0.2.1']),
    ('set_vif_dhcpv6_options_pd_interface_sla_id', ('eth0', '10', '5', 'eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'pd', '5', 'interface', 'eth0', 'sla-id', '5']),
    ('set_vif_dhcpv6_options_pd_length', ('eth0', '10', '5', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'pd', '5', 'length', '5']),
    ('set_vif_dhcpv6_options_rapid_commit', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'rapid-commit']),
    ('set_vif_dhcpv6_options_temporary', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'dhcpv6-options', 'temporary']),
    ('set_vif_disable', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'disable']),
    ('set_vif_disable_link_detect', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'disable-link-detect']),
    ('set_vif_egress_qos', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'egress-qos', '5']),
    ('set_vif_ingress_qos', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ingress-qos', '5']),
    ('set_vif_ip_adjust_mss', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'adjust-mss', '5']),
    ('set_vif_ip_adjust_mss_clamp_mss_to_pmtu', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'adjust-mss', 'clamp-mss-to-pmtu']),
    ('set_vif_ip_arp_cache_timeout', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'arp-cache-timeout', '5']),
    ('set_vif_ip_disable_arp_filter', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'disable-arp-filter']),
    ('set_vif_ip_disable_forwarding', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'disable-forwarding']),
    ('set_vif_ip_enable_arp_accept', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'enable-arp-accept']),
    ('set_vif_ip_enable_arp_announce', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'enable-arp-announce']),
    ('set_vif_ip_enable_arp_ignore', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'enable-arp-ignore']),
    ('set_vif_ip_enable_directed_broadcast', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'enable-directed-broadcast']),
    ('set_vif_ip_enable_proxy_arp', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'enable-proxy-arp']),
    ('set_vif_ip_proxy_arp_pvlan', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'proxy-arp-pvlan']),
    ('set_vif_ip_source_validation', ('eth0', '10', 'nat'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ip', 'source-validation', 'nat']),
    ('set_vif_ipv6_accept_dad', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'accept-dad', '5']),
    ('set_vif_ipv6_address_autoconf', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'address', 'autoconf']),
    ('set_vif_ipv6_address_eui64', ('eth0', '10', '2001:db8::/32'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'address', 'eui64', '2001:db8::/32']),
    ('set_vif_ipv6_address_no_default_link_local', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'address', 'no-default-link-local']),
    ('set_vif_ipv6_adjust_mss', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'adjust-mss', '5']),
    ('set_vif_ipv6_adjust_mss_clamp_mss_to_pmtu', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'adjust-mss', 'clamp-mss-to-pmtu']),
    ('set_vif_ipv6_base_reachable_time', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'base-reachable-time', '5']),
    ('set_vif_ipv6_disable_forwarding', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'disable-forwarding']),
    ('set_vif_ipv6_dup_addr_detect_transmits', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_vif_ipv6_source_validation', ('eth0', '10', 'nat'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'source-validation', 'nat']),
    ('set_vif_mac', ('eth0', '10', '00:11:22:33:44:55'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'mac', '00:11:22:33:44:55']),
    ('set_vif_mirror_egress', ('eth0', '10', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'mirror', 'egress', 'eth1']),
    ('set_vif_mirror_ingress', ('eth0', '10', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'mirror', 'ingress', 'eth1']),
    ('set_vif_mtu', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'mtu', '5']),
    ('set_vif_redirect', ('eth0', '10', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'redirect', 'eth1']),
    ('set_vif_s', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10']),
    ('set_vif_s_address', ('eth0', '10', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'address', '192.0.2.1']),
    ('set_vif_s_description', ('eth0', '10', 'lab'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'description', 'lab']),
    ('set_vif_s_dhcp_options_client_id', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcp-options', 'client-id', '5']),
    ('set_vif_s_dhcp_options_default_route_distance', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcp-options', 'default-route-distance', '5']),
    ('set_vif_s_dhcp_options_host_name', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcp-options', 'host-name', '5']),
    ('set_vif_s_dhcp_options_mtu', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcp-options', 'mtu']),
    ('set_vif_s_dhcp_options_no_default_route', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcp-options', 'no-default-route']),
    ('set_vif_s_dhcp_options_reject', ('eth0', '10', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcp-options', 'reject', '192.0.2.1']),
    ('set_vif_s_dhcp_options_user_class', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcp-options', 'user-class', '5']),
    ('set_vif_s_dhcp_options_vendor_class_id', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcp-options', 'vendor-class-id', '5']),
    ('set_vif_s_dhcpv6_options_duid', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'duid', '5']),
    ('set_vif_s_dhcpv6_options_no_release', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'no-release']),
    ('set_vif_s_dhcpv6_options_parameters_only', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'parameters-only']),
    ('set_vif_s_dhcpv6_options_pd', ('eth0', '10', '5', '2001:db8::/32'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5']),
    ('set_vif_s_dhcpv6_options_pd_interface', ('eth0', '10', '5', 'eth0'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5', 'interface', 'eth0']),
    ('set_vif_s_dhcpv6_options_pd_interface_address', ('eth0', '10', '5', 'eth0', '192.0.2.1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5', 'interface', 'eth0', 'address', '192.0.2.1']),
    ('set_vif_s_dhcpv6_options_pd_interface_sla_id', ('eth0', '10', '5', 'eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5', 'interface', 'eth0', 'sla-id', '5']),
    ('set_vif_s_dhcpv6_options_pd_length', ('eth0', '10', '5', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5', 'length', '5']),
    ('set_vif_s_dhcpv6_options_rapid_commit', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'rapid-commit']),
    ('set_vif_s_dhcpv6_options_temporary', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'dhcpv6-options', 'temporary']),
    ('set_vif_s_disable', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'disable']),
    ('set_vif_s_disable_link_detect', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'disable-link-detect']),
    ('set_vif_s_ip_adjust_mss', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'adjust-mss', '5']),
    ('set_vif_s_ip_arp_cache_timeout', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'arp-cache-timeout', '5']),
    ('set_vif_s_ip_disable_arp_filter', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'disable-arp-filter']),
    ('set_vif_s_ip_disable_forwarding', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'disable-forwarding']),
    ('set_vif_s_ip_enable_arp_accept', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'enable-arp-accept']),
    ('set_vif_s_ip_enable_arp_announce', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'enable-arp-announce']),
    ('set_vif_s_ip_enable_arp_ignore', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'enable-arp-ignore']),
    ('set_vif_s_ip_enable_directed_broadcast', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'enable-directed-broadcast']),
    ('set_vif_s_ip_enable_proxy_arp', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'enable-proxy-arp']),
    ('set_vif_s_ip_proxy_arp_pvlan', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'proxy-arp-pvlan']),
    ('set_vif_s_ip_source_validation', ('eth0', '10', 'nat'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ip', 'source-validation', 'nat']),
    ('set_vif_s_ipv6_accept_dad', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'accept-dad', '5']),
    ('set_vif_s_ipv6_address_autoconf', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'address', 'autoconf']),
    ('set_vif_s_ipv6_address_eui64', ('eth0', '10', '2001:db8::/32'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'address', 'eui64', '2001:db8::/32']),
    ('set_vif_s_ipv6_address_no_default_link_local', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'address', 'no-default-link-local']),
    ('set_vif_s_ipv6_adjust_mss', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'adjust-mss', '5']),
    ('set_vif_s_ipv6_base_reachable_time', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'base-reachable-time', '5']),
    ('set_vif_s_ipv6_disable_forwarding', ('eth0', '10'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'disable-forwarding']),
    ('set_vif_s_ipv6_dup_addr_detect_transmits', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_vif_s_ipv6_source_validation', ('eth0', '10', 'nat'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'source-validation', 'nat']),
    ('set_vif_s_mac', ('eth0', '10', '00:11:22:33:44:55'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'mac', '00:11:22:33:44:55']),
    ('set_vif_s_mirror_egress', ('eth0', '10', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'mirror', 'egress', 'eth1']),
    ('set_vif_s_mirror_ingress', ('eth0', '10', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'mirror', 'ingress', 'eth1']),
    ('set_vif_s_mtu', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'mtu', '5']),
    ('set_vif_s_protocol', ('eth0', '10', 'tcp'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'protocol', 'tcp']),
    ('set_vif_s_redirect', ('eth0', '10', 'eth1'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'redirect', 'eth1']),
    ('set_vif_s_vrf', ('eth0', '10', 'red'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vrf', 'red']),
    ('set_vif_vrf', ('eth0', '10', 'red'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'vrf', 'red']),
]


@pytest.mark.parametrize("method, args, op, expected_path", COMMON_CASES)
@pytest.mark.parametrize("version", ["1.4", "1.5"])
def test_ethernet_common_paths(method, args, op, expected_path, version):
    _run(version, method, args, op, expected_path)

V15_ONLY_CASES = [
    ('delete_switchdev', ('eth0',), 'delete', ['interfaces', 'ethernet', 'eth0', 'switchdev']),
    ('set_ip_enable_directed_broadcast', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'ip', 'enable-directed-broadcast']),
    ('set_ipv6_address_interface_identifier', ('eth0', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_switchdev', ('eth0',), 'set', ['interfaces', 'ethernet', 'eth0', 'switchdev']),
    ('set_vif_c_ipv6_address_interface_identifier', ('eth0', '10', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_vif_ipv6_address_interface_identifier', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif', '10', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_vif_s_ipv6_address_interface_identifier', ('eth0', '10', '5'), 'set', ['interfaces', 'ethernet', 'eth0', 'vif-s', '10', 'ipv6', 'address', 'interface-identifier', '5']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V15_ONLY_CASES)
def test_ethernet_v1_5_only_paths(method, args, op, expected_path):
    _run("1.5", method, args, op, expected_path)
