"""Golden (method, args, op, expected_path) cases for BondingInterfaceBuilderMixin.

Paths checked with validateTmplPath on 1.4 (100.64.64.50) and 1.5 (100.64.64.5).
Generated for issue #721; edit the tables directly if the mapper changes.
"""

import pytest

from vyos_builders.interfaces.bonding import BondingInterfaceBuilderMixin


def _run(version, method, args, op, expected_path):
    builder = BondingInterfaceBuilderMixin(version=version)
    getattr(builder, method)(*args)
    operations = builder.get_operations()
    assert [(item["op"], item["path"]) for item in operations] == [(op, expected_path)]

COMMON_CASES = [
    ('delete_all_dhcp_options', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcp-options']),
    ('delete_all_dhcpv6_options', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options']),
    ('delete_arp_monitor', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'arp-monitor']),
    ('delete_arp_monitor_interval', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'arp-monitor', 'interval']),
    ('delete_dhcp_options_client_id', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'client-id']),
    ('delete_dhcp_options_default_route_distance', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'default-route-distance']),
    ('delete_dhcp_options_host_name', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'host-name']),
    ('delete_dhcp_options_mtu', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'mtu']),
    ('delete_dhcp_options_no_default_route', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'no-default-route']),
    ('delete_dhcp_options_reject', ('bond0', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'reject', '5']),
    ('delete_dhcpv6_options_duid', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'duid']),
    ('delete_dhcpv6_options_no_release', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'no-release']),
    ('delete_dhcpv6_options_parameters_only', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'parameters-only']),
    ('delete_dhcpv6_options_rapid_commit', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'rapid-commit']),
    ('delete_dhcpv6_options_temporary', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'temporary']),
    ('delete_evpn', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'evpn']),
    ('delete_evpn_es_df_pref', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'evpn', 'es-df-pref']),
    ('delete_evpn_es_id', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'evpn', 'es-id']),
    ('delete_evpn_es_sys_mac', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'evpn', 'es-sys-mac']),
    ('delete_evpn_uplink', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'evpn', 'uplink']),
    ('delete_hash_policy', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'hash-policy']),
    ('delete_interface', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0']),
    ('delete_interface_address', ('bond0', '192.0.2.1'), 'delete', ['interfaces', 'bonding', 'bond0', 'address', '192.0.2.1']),
    ('delete_interface_description', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'description']),
    ('delete_interface_disable', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'disable']),
    ('delete_interface_disable_link_detect', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'disable-link-detect']),
    ('delete_interface_mac', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'mac']),
    ('delete_interface_mtu', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'mtu']),
    ('delete_interface_redirect', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'redirect']),
    ('delete_interface_vrf', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'vrf']),
    ('delete_ip_adjust_mss', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'adjust-mss']),
    ('delete_ip_arp_cache_timeout', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'arp-cache-timeout']),
    ('delete_ip_disable_arp_filter', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'disable-arp-filter']),
    ('delete_ip_disable_forwarding', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'disable-forwarding']),
    ('delete_ip_enable_arp_accept', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-arp-accept']),
    ('delete_ip_enable_arp_announce', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-arp-announce']),
    ('delete_ip_enable_arp_ignore', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-arp-ignore']),
    ('delete_ip_enable_directed_broadcast', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-directed-broadcast']),
    ('delete_ip_enable_proxy_arp', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-proxy-arp']),
    ('delete_ip_proxy_arp_pvlan', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'proxy-arp-pvlan']),
    ('delete_ip_source_validation', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ip', 'source-validation']),
    ('delete_ipv6_accept_dad', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'accept-dad']),
    ('delete_ipv6_address_autoconf', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'address', 'autoconf']),
    ('delete_ipv6_address_eui64', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'address', 'eui64']),
    ('delete_ipv6_address_no_default_link_local', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'address', 'no-default-link-local']),
    ('delete_ipv6_adjust_mss', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'adjust-mss']),
    ('delete_ipv6_base_reachable_time', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'base-reachable-time']),
    ('delete_ipv6_disable_forwarding', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'disable-forwarding']),
    ('delete_ipv6_dup_addr_detect_transmits', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'dup-addr-detect-transmits']),
    ('delete_ipv6_source_validation', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'source-validation']),
    ('delete_lacp_rate', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'lacp-rate']),
    ('delete_mii_mon_interval', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'mii-mon-interval']),
    ('delete_min_links', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'min-links']),
    ('delete_mirror_egress', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'mirror', 'egress']),
    ('delete_mirror_ingress', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'mirror', 'ingress']),
    ('delete_mode', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'mode']),
    ('delete_primary', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'primary']),
    ('delete_system_mac', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'system-mac']),
    ('delete_vif', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10']),
    ('delete_vif_address', ('bond0', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'address', '5']),
    ('delete_vif_c', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10']),
    ('delete_vif_c_address', ('bond0', '10', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'address', '5']),
    ('delete_vif_c_description', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'description']),
    ('delete_vif_c_dhcp_options', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options']),
    ('delete_vif_c_dhcp_options_client_id', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'client-id']),
    ('delete_vif_c_dhcp_options_default_route_distance', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'default-route-distance']),
    ('delete_vif_c_dhcp_options_host_name', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'host-name']),
    ('delete_vif_c_dhcp_options_mtu', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'mtu']),
    ('delete_vif_c_dhcp_options_no_default_route', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'no-default-route']),
    ('delete_vif_c_dhcp_options_reject', ('bond0', '10', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'reject', '5']),
    ('delete_vif_c_dhcp_options_user_class', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'user-class']),
    ('delete_vif_c_dhcp_options_vendor_class_id', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'vendor-class-id']),
    ('delete_vif_c_dhcpv6_options', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options']),
    ('delete_vif_c_dhcpv6_options_duid', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'duid']),
    ('delete_vif_c_dhcpv6_options_no_release', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'no-release']),
    ('delete_vif_c_dhcpv6_options_parameters_only', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'parameters-only']),
    ('delete_vif_c_dhcpv6_options_pd', ('bond0', '10', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5']),
    ('delete_vif_c_dhcpv6_options_pd_interface', ('bond0', '10', '10', '5', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5', 'interface', '5']),
    ('delete_vif_c_dhcpv6_options_rapid_commit', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'rapid-commit']),
    ('delete_vif_c_dhcpv6_options_temporary', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'temporary']),
    ('delete_vif_c_disable', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'disable']),
    ('delete_vif_c_disable_link_detect', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'disable-link-detect']),
    ('delete_vif_c_ip', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip']),
    ('delete_vif_c_ip_adjust_mss', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'adjust-mss']),
    ('delete_vif_c_ip_arp_cache_timeout', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'arp-cache-timeout']),
    ('delete_vif_c_ip_disable_arp_filter', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'disable-arp-filter']),
    ('delete_vif_c_ip_disable_forwarding', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'disable-forwarding']),
    ('delete_vif_c_ip_enable_arp_accept', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-arp-accept']),
    ('delete_vif_c_ip_enable_arp_announce', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-arp-announce']),
    ('delete_vif_c_ip_enable_arp_ignore', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-arp-ignore']),
    ('delete_vif_c_ip_enable_directed_broadcast', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-directed-broadcast']),
    ('delete_vif_c_ip_enable_proxy_arp', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-proxy-arp']),
    ('delete_vif_c_ip_proxy_arp_pvlan', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'proxy-arp-pvlan']),
    ('delete_vif_c_ip_source_validation', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'source-validation']),
    ('delete_vif_c_ipv6', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6']),
    ('delete_vif_c_ipv6_accept_dad', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'accept-dad']),
    ('delete_vif_c_ipv6_address_autoconf', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'autoconf']),
    ('delete_vif_c_ipv6_address_eui64', ('bond0', '10', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'eui64', '5']),
    ('delete_vif_c_ipv6_address_no_default_link_local', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'no-default-link-local']),
    ('delete_vif_c_ipv6_adjust_mss', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'adjust-mss']),
    ('delete_vif_c_ipv6_base_reachable_time', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'base-reachable-time']),
    ('delete_vif_c_ipv6_disable_forwarding', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'disable-forwarding']),
    ('delete_vif_c_ipv6_dup_addr_detect_transmits', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'dup-addr-detect-transmits']),
    ('delete_vif_c_ipv6_source_validation', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'source-validation']),
    ('delete_vif_c_mac', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'mac']),
    ('delete_vif_c_mirror', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'mirror']),
    ('delete_vif_c_mirror_egress', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'egress']),
    ('delete_vif_c_mirror_ingress', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'ingress']),
    ('delete_vif_c_mtu', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'mtu']),
    ('delete_vif_c_redirect', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'redirect']),
    ('delete_vif_c_vrf', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'vrf']),
    ('delete_vif_description', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'description']),
    ('delete_vif_dhcp_options', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options']),
    ('delete_vif_dhcp_options_client_id', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'client-id']),
    ('delete_vif_dhcp_options_default_route_distance', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'default-route-distance']),
    ('delete_vif_dhcp_options_host_name', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'host-name']),
    ('delete_vif_dhcp_options_mtu', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'mtu']),
    ('delete_vif_dhcp_options_no_default_route', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'no-default-route']),
    ('delete_vif_dhcp_options_reject', ('bond0', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'reject', '5']),
    ('delete_vif_dhcp_options_user_class', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'user-class']),
    ('delete_vif_dhcp_options_vendor_class_id', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'vendor-class-id']),
    ('delete_vif_dhcpv6_options', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options']),
    ('delete_vif_dhcpv6_options_duid', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'duid']),
    ('delete_vif_dhcpv6_options_no_release', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'no-release']),
    ('delete_vif_dhcpv6_options_parameters_only', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'parameters-only']),
    ('delete_vif_dhcpv6_options_pd', ('bond0', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'pd', '5']),
    ('delete_vif_dhcpv6_options_pd_interface', ('bond0', '10', '5', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'pd', '5', 'interface', '5']),
    ('delete_vif_dhcpv6_options_rapid_commit', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'rapid-commit']),
    ('delete_vif_dhcpv6_options_temporary', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'temporary']),
    ('delete_vif_disable', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'disable']),
    ('delete_vif_disable_link_detect', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'disable-link-detect']),
    ('delete_vif_egress_qos', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'egress-qos']),
    ('delete_vif_ingress_qos', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ingress-qos']),
    ('delete_vif_ip', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip']),
    ('delete_vif_ip_adjust_mss', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'adjust-mss']),
    ('delete_vif_ip_arp_cache_timeout', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'arp-cache-timeout']),
    ('delete_vif_ip_disable_arp_filter', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'disable-arp-filter']),
    ('delete_vif_ip_disable_forwarding', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'disable-forwarding']),
    ('delete_vif_ip_enable_arp_accept', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-arp-accept']),
    ('delete_vif_ip_enable_arp_announce', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-arp-announce']),
    ('delete_vif_ip_enable_arp_ignore', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-arp-ignore']),
    ('delete_vif_ip_enable_directed_broadcast', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-directed-broadcast']),
    ('delete_vif_ip_enable_proxy_arp', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-proxy-arp']),
    ('delete_vif_ip_proxy_arp_pvlan', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'proxy-arp-pvlan']),
    ('delete_vif_ip_source_validation', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'source-validation']),
    ('delete_vif_ipv6', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6']),
    ('delete_vif_ipv6_accept_dad', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'accept-dad']),
    ('delete_vif_ipv6_address_autoconf', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'address', 'autoconf']),
    ('delete_vif_ipv6_address_eui64', ('bond0', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'address', 'eui64', '5']),
    ('delete_vif_ipv6_address_no_default_link_local', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'address', 'no-default-link-local']),
    ('delete_vif_ipv6_adjust_mss', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'adjust-mss']),
    ('delete_vif_ipv6_base_reachable_time', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'base-reachable-time']),
    ('delete_vif_ipv6_disable_forwarding', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'disable-forwarding']),
    ('delete_vif_ipv6_dup_addr_detect_transmits', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'dup-addr-detect-transmits']),
    ('delete_vif_ipv6_source_validation', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'source-validation']),
    ('delete_vif_mac', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'mac']),
    ('delete_vif_mirror', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'mirror']),
    ('delete_vif_mirror_egress', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'mirror', 'egress']),
    ('delete_vif_mirror_ingress', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'mirror', 'ingress']),
    ('delete_vif_mtu', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'mtu']),
    ('delete_vif_redirect', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'redirect']),
    ('delete_vif_s', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10']),
    ('delete_vif_s_address', ('bond0', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'address', '5']),
    ('delete_vif_s_description', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'description']),
    ('delete_vif_s_dhcp_options', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options']),
    ('delete_vif_s_dhcp_options_client_id', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'client-id']),
    ('delete_vif_s_dhcp_options_default_route_distance', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'default-route-distance']),
    ('delete_vif_s_dhcp_options_host_name', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'host-name']),
    ('delete_vif_s_dhcp_options_mtu', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'mtu']),
    ('delete_vif_s_dhcp_options_no_default_route', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'no-default-route']),
    ('delete_vif_s_dhcp_options_reject', ('bond0', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'reject', '5']),
    ('delete_vif_s_dhcp_options_user_class', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'user-class']),
    ('delete_vif_s_dhcp_options_vendor_class_id', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'vendor-class-id']),
    ('delete_vif_s_dhcpv6_options', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options']),
    ('delete_vif_s_dhcpv6_options_duid', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'duid']),
    ('delete_vif_s_dhcpv6_options_no_release', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'no-release']),
    ('delete_vif_s_dhcpv6_options_parameters_only', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'parameters-only']),
    ('delete_vif_s_dhcpv6_options_pd', ('bond0', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5']),
    ('delete_vif_s_dhcpv6_options_pd_interface', ('bond0', '10', '5', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5', 'interface', '5']),
    ('delete_vif_s_dhcpv6_options_rapid_commit', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'rapid-commit']),
    ('delete_vif_s_dhcpv6_options_temporary', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'temporary']),
    ('delete_vif_s_disable', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'disable']),
    ('delete_vif_s_disable_link_detect', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'disable-link-detect']),
    ('delete_vif_s_ip', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip']),
    ('delete_vif_s_ip_adjust_mss', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'adjust-mss']),
    ('delete_vif_s_ip_arp_cache_timeout', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'arp-cache-timeout']),
    ('delete_vif_s_ip_disable_arp_filter', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'disable-arp-filter']),
    ('delete_vif_s_ip_disable_forwarding', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'disable-forwarding']),
    ('delete_vif_s_ip_enable_arp_accept', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-arp-accept']),
    ('delete_vif_s_ip_enable_arp_announce', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-arp-announce']),
    ('delete_vif_s_ip_enable_arp_ignore', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-arp-ignore']),
    ('delete_vif_s_ip_enable_directed_broadcast', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-directed-broadcast']),
    ('delete_vif_s_ip_enable_proxy_arp', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-proxy-arp']),
    ('delete_vif_s_ip_proxy_arp_pvlan', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'proxy-arp-pvlan']),
    ('delete_vif_s_ip_source_validation', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'source-validation']),
    ('delete_vif_s_ipv6', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6']),
    ('delete_vif_s_ipv6_accept_dad', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'accept-dad']),
    ('delete_vif_s_ipv6_address_autoconf', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'address', 'autoconf']),
    ('delete_vif_s_ipv6_address_eui64', ('bond0', '10', '5'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'address', 'eui64', '5']),
    ('delete_vif_s_ipv6_address_no_default_link_local', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'address', 'no-default-link-local']),
    ('delete_vif_s_ipv6_adjust_mss', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'adjust-mss']),
    ('delete_vif_s_ipv6_base_reachable_time', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'base-reachable-time']),
    ('delete_vif_s_ipv6_disable_forwarding', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'disable-forwarding']),
    ('delete_vif_s_ipv6_dup_addr_detect_transmits', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'dup-addr-detect-transmits']),
    ('delete_vif_s_ipv6_source_validation', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'source-validation']),
    ('delete_vif_s_mac', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'mac']),
    ('delete_vif_s_mirror', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'mirror']),
    ('delete_vif_s_mirror_egress', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'mirror', 'egress']),
    ('delete_vif_s_mirror_ingress', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'mirror', 'ingress']),
    ('delete_vif_s_mtu', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'mtu']),
    ('delete_vif_s_protocol', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'protocol']),
    ('delete_vif_s_redirect', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'redirect']),
    ('delete_vif_s_vrf', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vrf']),
    ('delete_vif_vrf', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'vrf']),
    ('set_arp_monitor_interval', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'arp-monitor', 'interval', '5']),
    ('set_dhcp_options_client_id', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'client-id', '5']),
    ('set_dhcp_options_default_route_distance', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'default-route-distance', '5']),
    ('set_dhcp_options_host_name', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'host-name', '5']),
    ('set_dhcp_options_mtu', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'mtu']),
    ('set_dhcp_options_no_default_route', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'no-default-route']),
    ('set_dhcp_options_reject', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'dhcp-options', 'reject', '5']),
    ('set_dhcpv6_options_duid', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'duid', '5']),
    ('set_dhcpv6_options_no_release', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'no-release']),
    ('set_dhcpv6_options_parameters_only', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'parameters-only']),
    ('set_dhcpv6_options_rapid_commit', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'rapid-commit']),
    ('set_dhcpv6_options_temporary', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'dhcpv6-options', 'temporary']),
    ('set_evpn_es_df_pref', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'evpn', 'es-df-pref', '5']),
    ('set_evpn_es_id', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'evpn', 'es-id', '5']),
    ('set_evpn_es_sys_mac', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'evpn', 'es-sys-mac', '5']),
    ('set_evpn_uplink', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'evpn', 'uplink']),
    ('set_hash_policy', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'hash-policy', '5']),
    ('set_interface_address', ('bond0', '192.0.2.1'), 'set', ['interfaces', 'bonding', 'bond0', 'address', '192.0.2.1']),
    ('set_interface_description', ('bond0', 'lab'), 'set', ['interfaces', 'bonding', 'bond0', 'description', 'lab']),
    ('set_interface_disable', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'disable']),
    ('set_interface_disable_link_detect', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'disable-link-detect']),
    ('set_interface_mac', ('bond0', '00:11:22:33:44:55'), 'set', ['interfaces', 'bonding', 'bond0', 'mac', '00:11:22:33:44:55']),
    ('set_interface_mtu', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'mtu', '5']),
    ('set_interface_redirect', ('bond0', 'eth1'), 'set', ['interfaces', 'bonding', 'bond0', 'redirect', 'eth1']),
    ('set_interface_vrf', ('bond0', 'red'), 'set', ['interfaces', 'bonding', 'bond0', 'vrf', 'red']),
    ('set_ip_adjust_mss', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'adjust-mss', '5']),
    ('set_ip_arp_cache_timeout', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'arp-cache-timeout', '5']),
    ('set_ip_disable_arp_filter', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'disable-arp-filter']),
    ('set_ip_disable_forwarding', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'disable-forwarding']),
    ('set_ip_enable_arp_accept', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-arp-accept']),
    ('set_ip_enable_arp_announce', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-arp-announce']),
    ('set_ip_enable_arp_ignore', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-arp-ignore']),
    ('set_ip_enable_directed_broadcast', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-directed-broadcast']),
    ('set_ip_enable_proxy_arp', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'enable-proxy-arp']),
    ('set_ip_proxy_arp_pvlan', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'proxy-arp-pvlan']),
    ('set_ip_source_validation', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ip', 'source-validation', '5']),
    ('set_ipv6_accept_dad', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'accept-dad', '5']),
    ('set_ipv6_address_autoconf', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'address', 'autoconf']),
    ('set_ipv6_address_eui64', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'address', 'eui64', '5']),
    ('set_ipv6_address_no_default_link_local', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'address', 'no-default-link-local']),
    ('set_ipv6_adjust_mss', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'adjust-mss', '5']),
    ('set_ipv6_base_reachable_time', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'base-reachable-time', '5']),
    ('set_ipv6_disable_forwarding', ('bond0',), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'disable-forwarding']),
    ('set_ipv6_dup_addr_detect_transmits', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_ipv6_source_validation', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'source-validation', '5']),
    ('set_lacp_rate', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'lacp-rate', '5']),
    ('set_mii_mon_interval', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'mii-mon-interval', '5']),
    ('set_min_links', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'min-links', '5']),
    ('set_mirror_egress', ('bond0', 'eth1'), 'set', ['interfaces', 'bonding', 'bond0', 'mirror', 'egress', 'eth1']),
    ('set_mirror_ingress', ('bond0', 'eth1'), 'set', ['interfaces', 'bonding', 'bond0', 'mirror', 'ingress', 'eth1']),
    ('set_mode', ('bond0', 'nat'), 'set', ['interfaces', 'bonding', 'bond0', 'mode', 'nat']),
    ('set_primary', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'primary', '5']),
    ('set_system_mac', ('bond0', '00:11:22:33:44:55'), 'set', ['interfaces', 'bonding', 'bond0', 'system-mac', '00:11:22:33:44:55']),
    ('set_vif', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10']),
    ('set_vif_address', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'address', '5']),
    ('set_vif_c', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10']),
    ('set_vif_c_address', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'address', '5']),
    ('set_vif_c_description', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'description', '5']),
    ('set_vif_c_dhcp_options_client_id', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'client-id', '5']),
    ('set_vif_c_dhcp_options_default_route_distance', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'default-route-distance', '5']),
    ('set_vif_c_dhcp_options_host_name', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'host-name', '5']),
    ('set_vif_c_dhcp_options_mtu', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'mtu']),
    ('set_vif_c_dhcp_options_no_default_route', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'no-default-route']),
    ('set_vif_c_dhcp_options_reject', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'reject', '5']),
    ('set_vif_c_dhcp_options_user_class', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'user-class', '5']),
    ('set_vif_c_dhcp_options_vendor_class_id', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcp-options', 'vendor-class-id', '5']),
    ('set_vif_c_dhcpv6_options_duid', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'duid', '5']),
    ('set_vif_c_dhcpv6_options_no_release', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'no-release']),
    ('set_vif_c_dhcpv6_options_parameters_only', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'parameters-only']),
    ('set_vif_c_dhcpv6_options_pd_interface_address', ('bond0', '10', '10', '5', '5', '192.0.2.1'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'address', '192.0.2.1']),
    ('set_vif_c_dhcpv6_options_pd_interface_sla_id', ('bond0', '10', '10', '5', '5', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'sla-id', '5']),
    ('set_vif_c_dhcpv6_options_pd_length', ('bond0', '10', '10', '5', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'pd', '5', 'length', '5']),
    ('set_vif_c_dhcpv6_options_rapid_commit', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'rapid-commit']),
    ('set_vif_c_dhcpv6_options_temporary', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'dhcpv6-options', 'temporary']),
    ('set_vif_c_disable', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'disable']),
    ('set_vif_c_disable_link_detect', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'disable-link-detect']),
    ('set_vif_c_ip_adjust_mss', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'adjust-mss', '5']),
    ('set_vif_c_ip_arp_cache_timeout', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'arp-cache-timeout', '5']),
    ('set_vif_c_ip_disable_arp_filter', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'disable-arp-filter']),
    ('set_vif_c_ip_disable_forwarding', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'disable-forwarding']),
    ('set_vif_c_ip_enable_arp_accept', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-arp-accept']),
    ('set_vif_c_ip_enable_arp_announce', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-arp-announce']),
    ('set_vif_c_ip_enable_arp_ignore', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-arp-ignore']),
    ('set_vif_c_ip_enable_directed_broadcast', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-directed-broadcast']),
    ('set_vif_c_ip_enable_proxy_arp', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'enable-proxy-arp']),
    ('set_vif_c_ip_proxy_arp_pvlan', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'proxy-arp-pvlan']),
    ('set_vif_c_ip_source_validation', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ip', 'source-validation', '5']),
    ('set_vif_c_ipv6_accept_dad', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'accept-dad', '5']),
    ('set_vif_c_ipv6_address_autoconf', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'autoconf']),
    ('set_vif_c_ipv6_address_eui64', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'eui64', '5']),
    ('set_vif_c_ipv6_address_no_default_link_local', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'no-default-link-local']),
    ('set_vif_c_ipv6_adjust_mss', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'adjust-mss', '5']),
    ('set_vif_c_ipv6_base_reachable_time', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'base-reachable-time', '5']),
    ('set_vif_c_ipv6_disable_forwarding', ('bond0', '10', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'disable-forwarding']),
    ('set_vif_c_ipv6_dup_addr_detect_transmits', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_vif_c_ipv6_source_validation', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'source-validation', '5']),
    ('set_vif_c_mac', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'mac', '5']),
    ('set_vif_c_mirror_egress', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'egress', '5']),
    ('set_vif_c_mirror_ingress', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'mirror', 'ingress', '5']),
    ('set_vif_c_mtu', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'mtu', '5']),
    ('set_vif_c_redirect', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'redirect', '5']),
    ('set_vif_c_vrf', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'vrf', '5']),
    ('set_vif_description', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'description', '5']),
    ('set_vif_dhcp_options_client_id', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'client-id', '5']),
    ('set_vif_dhcp_options_default_route_distance', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'default-route-distance', '5']),
    ('set_vif_dhcp_options_host_name', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'host-name', '5']),
    ('set_vif_dhcp_options_mtu', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'mtu']),
    ('set_vif_dhcp_options_no_default_route', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'no-default-route']),
    ('set_vif_dhcp_options_reject', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'reject', '5']),
    ('set_vif_dhcp_options_user_class', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'user-class', '5']),
    ('set_vif_dhcp_options_vendor_class_id', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcp-options', 'vendor-class-id', '5']),
    ('set_vif_dhcpv6_options_duid', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'duid', '5']),
    ('set_vif_dhcpv6_options_no_release', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'no-release']),
    ('set_vif_dhcpv6_options_parameters_only', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'parameters-only']),
    ('set_vif_dhcpv6_options_pd_interface_address', ('bond0', '10', '5', '5', '192.0.2.1'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'address', '192.0.2.1']),
    ('set_vif_dhcpv6_options_pd_interface_sla_id', ('bond0', '10', '5', '5', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'sla-id', '5']),
    ('set_vif_dhcpv6_options_pd_length', ('bond0', '10', '5', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'pd', '5', 'length', '5']),
    ('set_vif_dhcpv6_options_rapid_commit', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'rapid-commit']),
    ('set_vif_dhcpv6_options_temporary', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'dhcpv6-options', 'temporary']),
    ('set_vif_disable', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'disable']),
    ('set_vif_disable_link_detect', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'disable-link-detect']),
    ('set_vif_egress_qos', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'egress-qos', '5']),
    ('set_vif_ingress_qos', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ingress-qos', '5']),
    ('set_vif_ip_adjust_mss', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'adjust-mss', '5']),
    ('set_vif_ip_arp_cache_timeout', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'arp-cache-timeout', '5']),
    ('set_vif_ip_disable_arp_filter', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'disable-arp-filter']),
    ('set_vif_ip_disable_forwarding', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'disable-forwarding']),
    ('set_vif_ip_enable_arp_accept', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-arp-accept']),
    ('set_vif_ip_enable_arp_announce', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-arp-announce']),
    ('set_vif_ip_enable_arp_ignore', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-arp-ignore']),
    ('set_vif_ip_enable_directed_broadcast', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-directed-broadcast']),
    ('set_vif_ip_enable_proxy_arp', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'enable-proxy-arp']),
    ('set_vif_ip_proxy_arp_pvlan', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'proxy-arp-pvlan']),
    ('set_vif_ip_source_validation', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ip', 'source-validation', '5']),
    ('set_vif_ipv6_accept_dad', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'accept-dad', '5']),
    ('set_vif_ipv6_address_autoconf', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'address', 'autoconf']),
    ('set_vif_ipv6_address_eui64', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'address', 'eui64', '5']),
    ('set_vif_ipv6_address_no_default_link_local', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'address', 'no-default-link-local']),
    ('set_vif_ipv6_adjust_mss', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'adjust-mss', '5']),
    ('set_vif_ipv6_base_reachable_time', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'base-reachable-time', '5']),
    ('set_vif_ipv6_disable_forwarding', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'disable-forwarding']),
    ('set_vif_ipv6_dup_addr_detect_transmits', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_vif_ipv6_source_validation', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'source-validation', '5']),
    ('set_vif_mac', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'mac', '5']),
    ('set_vif_mirror_egress', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'mirror', 'egress', '5']),
    ('set_vif_mirror_ingress', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'mirror', 'ingress', '5']),
    ('set_vif_mtu', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'mtu', '5']),
    ('set_vif_redirect', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'redirect', '5']),
    ('set_vif_s', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10']),
    ('set_vif_s_address', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'address', '5']),
    ('set_vif_s_description', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'description', '5']),
    ('set_vif_s_dhcp_options_client_id', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'client-id', '5']),
    ('set_vif_s_dhcp_options_default_route_distance', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'default-route-distance', '5']),
    ('set_vif_s_dhcp_options_host_name', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'host-name', '5']),
    ('set_vif_s_dhcp_options_mtu', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'mtu']),
    ('set_vif_s_dhcp_options_no_default_route', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'no-default-route']),
    ('set_vif_s_dhcp_options_reject', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'reject', '5']),
    ('set_vif_s_dhcp_options_user_class', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'user-class', '5']),
    ('set_vif_s_dhcp_options_vendor_class_id', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcp-options', 'vendor-class-id', '5']),
    ('set_vif_s_dhcpv6_options_duid', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'duid', '5']),
    ('set_vif_s_dhcpv6_options_no_release', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'no-release']),
    ('set_vif_s_dhcpv6_options_parameters_only', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'parameters-only']),
    ('set_vif_s_dhcpv6_options_pd_interface_address', ('bond0', '10', '5', '5', '192.0.2.1'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'address', '192.0.2.1']),
    ('set_vif_s_dhcpv6_options_pd_interface_sla_id', ('bond0', '10', '5', '5', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5', 'interface', '5', 'sla-id', '5']),
    ('set_vif_s_dhcpv6_options_pd_length', ('bond0', '10', '5', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'pd', '5', 'length', '5']),
    ('set_vif_s_dhcpv6_options_rapid_commit', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'rapid-commit']),
    ('set_vif_s_dhcpv6_options_temporary', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'dhcpv6-options', 'temporary']),
    ('set_vif_s_disable', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'disable']),
    ('set_vif_s_disable_link_detect', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'disable-link-detect']),
    ('set_vif_s_ip_adjust_mss', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'adjust-mss', '5']),
    ('set_vif_s_ip_arp_cache_timeout', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'arp-cache-timeout', '5']),
    ('set_vif_s_ip_disable_arp_filter', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'disable-arp-filter']),
    ('set_vif_s_ip_disable_forwarding', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'disable-forwarding']),
    ('set_vif_s_ip_enable_arp_accept', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-arp-accept']),
    ('set_vif_s_ip_enable_arp_announce', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-arp-announce']),
    ('set_vif_s_ip_enable_arp_ignore', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-arp-ignore']),
    ('set_vif_s_ip_enable_directed_broadcast', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-directed-broadcast']),
    ('set_vif_s_ip_enable_proxy_arp', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'enable-proxy-arp']),
    ('set_vif_s_ip_proxy_arp_pvlan', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'proxy-arp-pvlan']),
    ('set_vif_s_ip_source_validation', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ip', 'source-validation', '5']),
    ('set_vif_s_ipv6_accept_dad', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'accept-dad', '5']),
    ('set_vif_s_ipv6_address_autoconf', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'address', 'autoconf']),
    ('set_vif_s_ipv6_address_eui64', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'address', 'eui64', '5']),
    ('set_vif_s_ipv6_address_no_default_link_local', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'address', 'no-default-link-local']),
    ('set_vif_s_ipv6_adjust_mss', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'adjust-mss', '5']),
    ('set_vif_s_ipv6_base_reachable_time', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'base-reachable-time', '5']),
    ('set_vif_s_ipv6_disable_forwarding', ('bond0', '10'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'disable-forwarding']),
    ('set_vif_s_ipv6_dup_addr_detect_transmits', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'dup-addr-detect-transmits', '5']),
    ('set_vif_s_ipv6_source_validation', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'source-validation', '5']),
    ('set_vif_s_mac', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'mac', '5']),
    ('set_vif_s_mirror_egress', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'mirror', 'egress', '5']),
    ('set_vif_s_mirror_ingress', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'mirror', 'ingress', '5']),
    ('set_vif_s_mtu', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'mtu', '5']),
    ('set_vif_s_protocol', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'protocol', '5']),
    ('set_vif_s_redirect', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'redirect', '5']),
    ('set_vif_s_vrf', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vrf', '5']),
    ('set_vif_vrf', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'vrf', '5']),
]


@pytest.mark.parametrize("method, args, op, expected_path", COMMON_CASES)
@pytest.mark.parametrize("version", ["1.4", "1.5"])
def test_bonding_common_paths(method, args, op, expected_path, version):
    _run(version, method, args, op, expected_path)

V15_ONLY_CASES = [
    ('delete_eapol', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'eapol']),
    ('delete_eapol_ca_certificate', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'eapol', 'ca-certificate']),
    ('delete_eapol_certificate', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'eapol', 'certificate']),
    ('delete_eapol_passphrase', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'eapol', 'passphrase']),
    ('delete_ipv6_address_interface_identifier', ('bond0',), 'delete', ['interfaces', 'bonding', 'bond0', 'ipv6', 'address', 'interface-identifier']),
    ('delete_vif_c_ipv6_address_interface_identifier', ('bond0', '10', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'interface-identifier']),
    ('delete_vif_ipv6_address_interface_identifier', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'address', 'interface-identifier']),
    ('delete_vif_s_ipv6_address_interface_identifier', ('bond0', '10'), 'delete', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'address', 'interface-identifier']),
    ('set_eapol_ca_certificate', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'eapol', 'ca-certificate', '5']),
    ('set_eapol_certificate', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'eapol', 'certificate', '5']),
    ('set_eapol_passphrase', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'eapol', 'passphrase', '5']),
    ('set_ipv6_address_interface_identifier', ('bond0', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_vif_c_ipv6_address_interface_identifier', ('bond0', '10', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'vif-c', '10', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_vif_ipv6_address_interface_identifier', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif', '10', 'ipv6', 'address', 'interface-identifier', '5']),
    ('set_vif_s_ipv6_address_interface_identifier', ('bond0', '10', '5'), 'set', ['interfaces', 'bonding', 'bond0', 'vif-s', '10', 'ipv6', 'address', 'interface-identifier', '5']),
]


@pytest.mark.parametrize("method, args, op, expected_path", V15_ONLY_CASES)
def test_bonding_v1_5_only_paths(method, args, op, expected_path):
    _run("1.5", method, args, op, expected_path)
