-- ============================================================================
-- Fix FeatureGroup enum: add all 56 feature groups used by the backend
-- ============================================================================

-- Add all missing FeatureGroup enum values
-- (FIREWALL, INTERFACES, DHCP, NAT, MONITORING already exist)

-- Firewall sub-features
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'FIREWALL_GROUPS';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'FIREWALL_POLICIES';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'FIREWALL_ZONES';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'FIREWALL_GLOBAL_OPTIONS';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'FIREWALL_BRIDGE';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'FIREWALL_FLOWTABLES';

-- Network features
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'NETWORK';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'TUNNEL';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'VXLAN';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'VRF';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'LOAD_BALANCING';

-- NAT variants
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'NAT64';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'NAT66';

-- VPN features
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'VPN';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'IPSEC';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'WIREGUARD';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'L2TP';

-- PKI
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'PKI';

-- Routing hierarchy
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'ROUTING';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'UNICAST_PROTOCOLS';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'BGP';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'OSPF';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'OSPFV3';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'ISIS';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'OPENFABRIC';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'RIP';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'RIPNG';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'BABEL';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'STATIC_ROUTES';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'FAILOVER';

-- Routing Infrastructure
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'ROUTING_INFRASTRUCTURE';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'BFD';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'MPLS';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'SEGMENT_ROUTING';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'NHRP';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'RPKI';

-- Routing Policies
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'ROUTING_POLICIES';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'ACCESS_LIST';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'PREFIX_LIST';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'ROUTE_POLICY';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'ROUTE_MAP';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'LOCAL_ROUTE';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'BGP_AS_PATH';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'BGP_COMMUNITY';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'BGP_EXTENDED_COMMUNITY';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'BGP_LARGE_COMMUNITY';

-- Multicast
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'MULTICAST';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'IGMP_PROXY';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'PIM';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'PIM6';

-- System & Platform
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'HIGH_AVAILABILITY';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'SYSTEM';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'POWER';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'CONFIGURATION';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'DASHBOARD';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'SITES_INSTANCES';
ALTER TYPE "FeatureGroup" ADD VALUE IF NOT EXISTS 'USER_MANAGEMENT';

-- ============================================================================
-- Migrate EDITOR → OPERATOR in user_instance_roles
-- ============================================================================
UPDATE "user_instance_roles" SET "role" = 'OPERATOR' WHERE "role" = 'EDITOR';
